import type { Language } from '../../types';

const ADMIN_TEXT = {
  ru: {
    panel_title: 'Lumia Backoffice',
    panel_subtitle: 'Пользователи, экономика, карты и уведомления в одном рабочем пространстве',
    close: 'Закрыть',
    refresh: 'Обновить',

    section_overview: 'Обзор',
    section_users: 'Пользователи',
    section_economy: 'Экономика',
    section_charts: 'Карты',
    section_send: 'Рассылки',
    section_templates: 'Шаблоны',
    section_history: 'История',
    section_automation: 'Авто-уведомления',
    section_ai: 'AI',
    section_assets: 'Контент',

    metric_users: 'Пользователи',
    metric_premium: 'Premium',
    metric_active: 'Активны 7 дн.',
    metric_attention: 'Нужно внимание',
    metric_lumi_economy: 'Lumi (не Premium)',

    search_users: 'Поиск по имени или Telegram ID',
    filter_all: 'Все',
    filter_free: 'Free',
    sort_last_seen: 'Последняя активность',
    sort_created_at: 'Дата создания',
    sort_lumi_balance: 'Баланс Lumi',
    sort_premium_until: 'Premium до',
    sort_saved_charts_count: 'Сохранённые карты',
    sort_name: 'Имя',
    order_asc: 'По возрастанию',
    order_desc: 'По убыванию',

    segment_all: 'Все',
    segment_premium: 'Premium',
    segment_free: 'Free',
    segment_lumi: 'Lumi (баланс > 0)',
    segment_active_7d: 'Активны 7 дн.',
    segment_inactive_3d: 'Не были 3 дня',
    segment_inactive_7d: 'Не были 7 дней',
    segment_inactive_30d: 'Не были 30 дней',
    segment_attention: 'Нужно внимание',

    users_title: 'Пользователи',
    users_subtitle: 'Удобный список с быстрыми действиями по Premium, Lumi и активности.',
    users_empty: 'Пользователи не найдены',
    users_loading: 'Загружаем список пользователей…',
    users_page: 'Страница',
    last_seen: 'Последняя активность',
    created_at: 'Создан',
    detail_back: 'К списку',
    detail_title: 'Карточка пользователя',
    premium_until: 'Premium до',
    lumi: 'Lumi',
    slots_charts: 'Слоты / карты',
    current_device: 'Текущее устройство',
    copy_id: 'Копировать ID',
    copied: 'Telegram ID скопирован',
    premium_granted: 'Premium продлён на 30 дней',
    premium_revoked: 'Premium отключён',
    lumi_added: 'Начислено {amount} Lumi',
    lumi_subtracted: 'Списано {amount} Lumi',
    amount_placeholder: '10',
    note_placeholder: 'Сообщение пользователю (необязательно)',
    notify: 'Уведомить',
    premium_plus: 'Premium +30',
    revoke: 'Отключить',
    add_lumi: '+ Lumi',
    subtract_lumi: '- Lumi',
    working: 'Обработка…',
    user_loading: 'Загружаем карточку пользователя…',
    user_not_found: 'Пользователь не найден',
    economy: 'Экономика',
    economy_subtitle: 'Lumi, движения по балансу и последний платёж Stars.',
    latest_stars: 'Последний платёж Stars',
    no_stars: 'Платежей пока нет',
    no_transactions: 'Транзакций пока нет',
    activity: 'Активность',
    activity_subtitle: 'Последние события, сессии и вопросы в Oracle.',
    last_daily_login: 'Последний бонусный вход',
    oracle_questions: 'Вопросы в Oracle',
    no_questions: 'Вопросов пока нет',
    charts: 'Карты',
    charts_subtitle: 'Основная карта, слоты и сохранённые профили.',
    primary_chart: 'Основная карта',
    no_primary_chart: 'Основная карта пока не найдена',
    saved_charts: 'Сохранённых карт',
    total_slots: 'Всего слотов',
    sessions: 'Сессии',
    sessions_subtitle: 'Последние 3 входа и устройства.',
    no_sessions: 'Сессий пока нет',
    unknown_device: 'Неизвестное устройство',
    platform_missing: 'Платформа не определена',
    show_user_agent: 'Показать user-agent',
    no_data: 'Нет данных',

    send_title: 'Рассылки',
    send_subtitle: 'Личные и массовые сообщения в Telegram с картинкой, шаблоном и превью.',
    audience: 'Кому',
    message_source: 'Из чего',
    content_preview: 'Контент и превью',
    personal: 'Личное',
    broadcast: 'Массовое',
    target_user: 'Telegram ID пользователя',
    target_segment: 'Сегмент получателей',
    no_template: 'Без шаблона',
    title: 'Заголовок',
    body_ru: 'Текст RU',
    body_en: 'Текст EN',
    preview: 'Превью',
    preview_hint_personal: 'Если язык пользователя заранее неизвестен, оператор видит обе локализации.',
    preview_hint_broadcast: 'В рассылке каждый получит подходящую локализацию.',
    send_now: 'Отправить сейчас',
    sending: 'Отправляем…',
    send_success: 'Отправка завершена: {success}/{total} успешно',
    choose_image: 'Картинка',
    no_image: 'Без картинки',
    upload_image: 'Загрузить изображение',
    image_library: 'Медиатека',
    image_uploaded: 'Изображение загружено',

    templates_title: 'Шаблоны',
    templates_subtitle: 'Готовые тексты и сценарии, которые можно быстро использовать в рассылках.',
    template_new: 'Новый шаблон',
    template_edit: 'Редактирование шаблона',
    template_duplicate: 'Дублировать',
    template_use: 'Использовать',
    template_kind: 'Тип шаблона',
    template_active: 'Активен',
    template_disabled: 'Выключен',
    template_save: 'Сохранить шаблон',
    reset: 'Сбросить',
    templates_empty: 'Шаблонов пока нет',

    history_title: 'История отправок',
    history_subtitle: 'Результаты кампаний, ошибки доставки и быстрый повтор отправки.',
    history_empty: 'История отправок пока пуста',
    result_filter: 'Результат',
    result_all: 'Все',
    result_success: 'Успешно',
    result_partial: 'Частично',
    result_failed: 'С ошибками',
    mode_filter: 'Тип',
    sent_count: 'доставлено',
    failed_count: 'ошибок',
    reuse: 'Повторить',
    show_failures: 'Показать ошибки',
    hide_failures: 'Скрыть ошибки',

    automation_title: 'Авто-уведомления',
    automation_subtitle: 'Простой мастер для утренних, дневных и вечерних сценариев плюс доступ к расширенным настройкам.',
    automation_simple: 'Простой режим',
    automation_advanced: 'Расширенный режим',
    automation_slot: 'Слот',
    automation_frequency: 'Частота',
    automation_activate: 'Активность',
    automation_save: 'Сохранить сценарий',
    automation_saved: 'Авто-уведомление сохранено',
    automation_loading: 'Загружаем авто-уведомления…',
    slot_morning: 'Утро',
    slot_day: 'День',
    slot_evening: 'Вечер',
    slot_custom: 'Свой слот',
    frequency_daily: 'Каждый день',
    frequency_weekly: 'Раз в неделю',
    frequency_weekdays: 'По будням',

    assets_title: 'Контент и ассеты',
    assets_subtitle: 'Картинки для уведомлений и быстрый доступ к медиатеке.',
    assets_empty: 'Файлов пока нет',

    overview_title: 'Обзор',
    overview_subtitle: 'Ключевые показатели и быстрые переходы к самым важным сценариям.',
    quick_actions: 'Быстрые действия',
    open_send: 'Открыть рассылки',
    open_automation: 'Открыть авто-уведомления',
    open_assets: 'Открыть контент',
    open_users: 'Открыть пользователей',

    invalid_lumi_amount: 'Введите положительное целое число Lumi',
    load_users_failed: 'Не удалось загрузить пользователей',
    load_user_failed: 'Не удалось загрузить пользователя',
    update_premium_failed: 'Не удалось обновить Premium',
    update_lumi_failed: 'Не удалось обновить Lumi',
    copy_failed: 'Не удалось скопировать Telegram ID',
    notifications_failed: 'Не удалось загрузить уведомления',
    template_title_required: 'У шаблона должен быть заголовок',
    body_required: 'Добавьте текст хотя бы на одном языке',
    notification_title_required: 'Укажите заголовок уведомления',
    target_user_required: 'Укажите Telegram ID пользователя',
    template_save_failed: 'Не удалось сохранить шаблон',
    notification_send_failed: 'Не удалось отправить уведомление',
    save_template: 'Сохранить',
    select_asset_failed: 'Не удалось загрузить список изображений',
  },
  en: {
    panel_title: 'Lumia Backoffice',
    panel_subtitle: 'Users, economy, charts, and notifications in one workspace',
    close: 'Close',
    refresh: 'Refresh',

    section_overview: 'Overview',
    section_users: 'Users',
    section_economy: 'Economy',
    section_charts: 'Charts',
    section_send: 'Send',
    section_templates: 'Templates',
    section_history: 'History',
    section_automation: 'Automation',
    section_ai: 'AI',
    section_assets: 'Assets',

    metric_users: 'Users',
    metric_premium: 'Premium',
    metric_active: 'Active 7d',
    metric_attention: 'Attention',
    metric_lumi_economy: 'Lumi economy',

    search_users: 'Search by name or Telegram ID',
    filter_all: 'All',
    filter_free: 'Free',
    sort_last_seen: 'Last activity',
    sort_created_at: 'Created at',
    sort_lumi_balance: 'Lumi balance',
    sort_premium_until: 'Premium until',
    sort_saved_charts_count: 'Saved charts',
    sort_name: 'Name',
    order_asc: 'Ascending',
    order_desc: 'Descending',

    segment_all: 'All',
    segment_premium: 'Premium',
    segment_free: 'Free',
    segment_lumi: 'Lumi (balance > 0)',
    segment_active_7d: 'Active 7d',
    segment_inactive_3d: 'Inactive 3d',
    segment_inactive_7d: 'Inactive 7d',
    segment_inactive_30d: 'Inactive 30d',
    segment_attention: 'Need attention',

    users_title: 'Users',
    users_subtitle: 'Convenient list with quick Premium, Lumi, and activity actions.',
    users_empty: 'No users found',
    users_loading: 'Loading users…',
    users_page: 'Page',
    last_seen: 'Last seen',
    created_at: 'Created',
    detail_back: 'Back to list',
    detail_title: 'User detail',
    premium_until: 'Premium until',
    lumi: 'Lumi',
    slots_charts: 'Slots / charts',
    current_device: 'Current device',
    copy_id: 'Copy ID',
    copied: 'Telegram ID copied',
    premium_granted: 'Premium extended by 30 days',
    premium_revoked: 'Premium revoked',
    lumi_added: 'Added {amount} Lumi',
    lumi_subtracted: 'Removed {amount} Lumi',
    amount_placeholder: '10',
    note_placeholder: 'Message for user (optional)',
    notify: 'Notify',
    premium_plus: 'Premium +30',
    revoke: 'Revoke',
    add_lumi: '+ Lumi',
    subtract_lumi: '- Lumi',
    working: 'Working…',
    user_loading: 'Loading user details…',
    user_not_found: 'User not found',
    economy: 'Economy',
    economy_subtitle: 'Lumi, balance changes, and latest Stars payment.',
    latest_stars: 'Latest Stars payment',
    no_stars: 'No payments yet',
    no_transactions: 'No transactions yet',
    activity: 'Activity',
    activity_subtitle: 'Recent events, sessions, and Oracle questions.',
    last_daily_login: 'Last daily reward',
    oracle_questions: 'Oracle questions',
    no_questions: 'No questions yet',
    charts: 'Charts',
    charts_subtitle: 'Primary chart, slots, and saved profiles.',
    primary_chart: 'Primary chart',
    no_primary_chart: 'Primary chart is not available yet',
    saved_charts: 'Saved charts',
    total_slots: 'Total slots',
    sessions: 'Sessions',
    sessions_subtitle: 'Last 3 logins and devices.',
    no_sessions: 'No sessions yet',
    unknown_device: 'Unknown device',
    platform_missing: 'Platform not available',
    show_user_agent: 'Show user agent',
    no_data: 'No data',

    send_title: 'Send notifications',
    send_subtitle: 'Personal and broadcast Telegram messages with image, template, and preview.',
    audience: 'Audience',
    message_source: 'Source',
    content_preview: 'Content & preview',
    personal: 'Personal',
    broadcast: 'Broadcast',
    target_user: 'Target user Telegram ID',
    target_segment: 'Recipient segment',
    no_template: 'No template',
    title: 'Title',
    body_ru: 'RU body',
    body_en: 'EN body',
    preview: 'Preview',
    preview_hint_personal: 'If user language is unknown in advance, the operator sees both localizations.',
    preview_hint_broadcast: 'Each recipient will receive the matching localized version.',
    send_now: 'Send now',
    sending: 'Sending…',
    send_success: 'Send finished: {success}/{total} delivered',
    choose_image: 'Image',
    no_image: 'No image',
    upload_image: 'Upload image',
    image_library: 'Media library',
    image_uploaded: 'Image uploaded',

    templates_title: 'Templates',
    templates_subtitle: 'Ready-made texts and scenarios that can be quickly reused in sends.',
    template_new: 'New template',
    template_edit: 'Edit template',
    template_duplicate: 'Duplicate',
    template_use: 'Use',
    template_kind: 'Template kind',
    template_active: 'Active',
    template_disabled: 'Disabled',
    template_save: 'Save template',
    reset: 'Reset',
    templates_empty: 'No templates yet',

    history_title: 'Delivery history',
    history_subtitle: 'Campaign results, delivery failures, and quick reuse.',
    history_empty: 'No history yet',
    result_filter: 'Result',
    result_all: 'All',
    result_success: 'Success',
    result_partial: 'Partial',
    result_failed: 'Failed',
    mode_filter: 'Mode',
    sent_count: 'sent',
    failed_count: 'failed',
    reuse: 'Reuse',
    show_failures: 'Show failures',
    hide_failures: 'Hide failures',

    automation_title: 'Automation',
    automation_subtitle: 'Simple wizard for morning, day, and evening scenarios with advanced controls when needed.',
    automation_simple: 'Simple mode',
    automation_advanced: 'Advanced mode',
    automation_slot: 'Slot',
    automation_frequency: 'Frequency',
    automation_activate: 'Activity',
    automation_save: 'Save automation',
    automation_saved: 'Automation saved',
    automation_loading: 'Loading automations…',
    slot_morning: 'Morning',
    slot_day: 'Day',
    slot_evening: 'Evening',
    slot_custom: 'Custom',
    frequency_daily: 'Daily',
    frequency_weekly: 'Weekly',
    frequency_weekdays: 'Weekdays',

    assets_title: 'Content & assets',
    assets_subtitle: 'Notification images and quick media access.',
    assets_empty: 'No assets yet',

    overview_title: 'Overview',
    overview_subtitle: 'Key metrics and quick access to the most important operator flows.',
    quick_actions: 'Quick actions',
    open_send: 'Open send',
    open_automation: 'Open automation',
    open_assets: 'Open assets',
    open_users: 'Open users',

    invalid_lumi_amount: 'Enter a positive Lumi amount',
    load_users_failed: 'Failed to load users',
    load_user_failed: 'Failed to load user',
    update_premium_failed: 'Failed to update Premium',
    update_lumi_failed: 'Failed to update Lumi',
    copy_failed: 'Failed to copy Telegram ID',
    notifications_failed: 'Failed to load notifications',
    template_title_required: 'Template title is required',
    body_required: 'Add message body in at least one language',
    notification_title_required: 'Notification title is required',
    target_user_required: 'Target user Telegram ID is required',
    template_save_failed: 'Failed to save template',
    notification_send_failed: 'Failed to send notification',
    save_template: 'Save',
    select_asset_failed: 'Failed to load asset library',
  },
} as const;

export type AdminTextKey = keyof typeof ADMIN_TEXT.ru;

export function getAdminText(lang: Language, key: AdminTextKey) {
  return ADMIN_TEXT[lang][key];
}

export function formatAdminText(lang: Language, key: AdminTextKey, params: Record<string, string | number>) {
  let text = String(getAdminText(lang, key));
  for (const [token, value] of Object.entries(params)) {
    text = text.replaceAll(`{${token}}`, String(value));
  }
  return text;
}
