import { defineKnowledgeTopic } from './topicBuilder';
import type { KnowledgeTopicSource } from './types';

const topic = defineKnowledgeTopic;

export const ADVANCED_EXTENDED_TOPICS = [
  topic({
    id: 'black-moon-lilith', category: 'nodes-points',
    title: { ru: 'Лилит / Чёрная Луна', en: 'Lilith / Black Moon' },
    summary: { ru: 'Чёрная Луна Лилит — не планета и не вторая Луна. Обычно так называют расчётную точку, связанную с апогеем лунной орбиты — областью, где Луна находится дальше всего от Земли в выбранной модели.', en: 'Black Moon Lilith is not a planet or second moon; it is a calculated point associated with the lunar apogee.' },
    shortAnswer: { ru: 'Лилит в карте — математическая точка лунной орбиты, которой астрология приписывает символическое значение.', en: 'Lilith is a calculated lunar-orbit point given symbolic meaning in astrology.' },
    aliases: { ru: ['лилит', 'чёрная луна', 'черная луна', 'black moon lilith', 'блэк мун лилит'], en: ['lilith', 'black moon lilith', 'black moon'] },
    keywords: { ru: ['апогей луны', 'математическая точка', 'mean lilith', 'true lilith', 'средняя лилит', 'истинная лилит'], en: ['lunar apogee', 'calculated point', 'mean lilith', 'true lilith'] },
    ruSections: [
      { title: 'Что это на самом деле', kind: 'fact', paragraphs: ['Орбита Луны сложнее идеального эллипса, потому что на неё заметно влияет притяжение Солнца. Поэтому положение наиболее удалённой области орбиты можно рассчитывать разными способами. На карте Лилит обозначает координату, а не наблюдаемый светящийся объект.'] },
      { title: 'Средняя и истинная Лилит', kind: 'calculation', paragraphs: ['Средняя Лилит сглаживает быстрые колебания расчётного апогея и движется более ровно. Истинная, или осциллирующая, пытается учитывать текущие колебания и может заметно отклоняться. Поэтому две программы иногда показывают разные градусы — важно проверить настройку.'] },
      { title: 'Зачем это используют в астрологии', kind: 'astrology', paragraphs: ['В современной астрологии Лилит часто связывают с темами вытеснения, запрета, крайности и сложного отношения к автономии или желанию. Это интерпретационная традиция; точка не излучает особую физическую силу и не доказывает «тёмную сторону» личности.'] },
      { title: 'Откуда название', kind: 'history', depth: 'deep', paragraphs: ['Название отсылает к образу Лилит из ближневосточных и позднейших мифологических традиций. Астрологическое использование этого имени появилось намного позже самих мифов. У современного понятия нет одного общепринятого определения во всех школах.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Black Moon Lilith не равна астероиду Лилит и не равна гипотетической «тёмной Луне», встречающейся в старых текстах. Перед трактовкой нужно уточнить, какой именно объект или расчёт использует программа.'] },
    ],
    relatedTopicIds: ['nodes-overview', 'chart-point-object', 'planet-moon', 'ephemerides', 'degree-and-position'],
    diagram: 'lilith-apogee',
    sourceIds: ['astro-lilith'],
  }),
  topic({
    id: 'chart-point-object', category: 'nodes-points',
    title: { ru: 'Объект и точка карты', en: 'Chart object and calculated point' },
    summary: { ru: 'На астрологической карте рядом могут стоять реальные небесные тела, геометрические пересечения и расчётные точки. Одинаковый значок на круге не делает их объектами одного физического типа.', en: 'A chart can show physical bodies, geometric intersections, and calculated points side by side.' },
    shortAnswer: { ru: 'Солнце, Луна и Хирон можно наблюдать; Асцендент, узлы и Лилит получают из геометрии и расчёта.', en: 'The Sun, Moon, and Chiron are observable bodies; the Ascendant, nodes, and Lilith are calculated.' },
    aliases: { ru: ['точка карты', 'объект карты', 'математическая точка', 'расчётная точка'], en: ['chart point', 'calculated point', 'chart object'] },
    ruSections: [
      { title: 'Реальные небесные тела', kind: 'fact', paragraphs: ['Солнце — звезда, Луна — спутник Земли, планеты и Хирон — объекты Солнечной системы. Для них рассчитывают наблюдаемое положение на небе.'] },
      { title: 'Геометрические и расчётные точки', kind: 'calculation', paragraphs: ['Асцендент возникает на пересечении эклиптики с горизонтом, лунные узлы — на пересечении плоскостей орбит, Лилит связана с моделью лунного апогея. У таких точек нет твёрдой поверхности или собственного света.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['И телам, и точкам приписывают символические значения. Физическая природа объекта и его астрологическая трактовка — два разных слоя объяснения.'] },
    ],
    relatedTopicIds: ['planets-overview', 'ascendant', 'nodes-overview', 'black-moon-lilith', 'planet-chiron'],
  }),
  topic({
    id: 'stellium', category: 'synthesis',
    title: { ru: 'Стеллиум', en: 'Stellium' },
    summary: { ru: 'Стеллиум — скопление нескольких планет в одном знаке или доме, иногда также в тесной группе соединений. Единого количества и орбиса, которые признают все школы, нет.', en: 'A stellium is a cluster of several planets in one sign, house, or tight conjunction group.' },
    shortAnswer: { ru: 'Стеллиум показывает сильную концентрацию факторов карты в одной области, но его точное определение зависит от школы.', en: 'A stellium shows concentrated chart factors, but its exact definition varies by school.' },
    aliases: { ru: ['стеллиум', 'стелиум', 'скопление планет', 'много планет в одном знаке'], en: ['stellium', 'planet cluster'] },
    keywords: { ru: ['соединение планет', 'один знак', 'один дом', 'концентрация карты'], en: ['conjunctions', 'one sign', 'one house', 'chart concentration'] },
    ruSections: [
      { title: 'Как его определяют', kind: 'calculation', paragraphs: ['Одни астрологи требуют минимум три планеты, другие — четыре. Одни считают достаточным общий знак или дом, другие ждут цепочку соединений с небольшими орбисами. Поэтому перед выводом полезно назвать правило, по которому группа признана стеллиумом.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Стеллиум помогает заметить место, где в карте сосредоточено много разных функций. Знак описывает общий способ проявления, дом — область вопросов, а состав планет показывает, какие именно темы соединены.'] },
      { title: 'Как читать состав', kind: 'astrology', paragraphs: ['Три личные планеты обычно делают группу более заметной в повседневном описании, чем три медленные планеты одного поколения. Важно смотреть, есть ли среди них Солнце, Луна, управитель карты и точные аспекты к другим частям карты.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Несколько планет в одном знаке не обязательно находятся в точном соединении: между первой и последней может быть большое расстояние. И наоборот, соединение через границу знаков может быть тесным, хотя планеты записаны в разных знаках.'] },
      { title: 'Откуда слово', kind: 'history', depth: 'deep', paragraphs: ['Название связано с латинским словом stella — «звезда». У понятия нет одного известного автора; правила его употребления менялись и сегодня различаются между школами.'] },
    ],
    relatedTopicIds: ['aspect-conjunction', 'aspect-orb', 'repeated-chart-themes', 'planet-in-house', 'aspect-patterns'],
  }),
  topic({
    id: 'aspect-patterns', category: 'synthesis',
    title: { ru: 'Конфигурации аспектов', en: 'Aspect patterns' },
    summary: { ru: 'Конфигурация аспектов — узнаваемая геометрическая фигура, которую несколько планет образуют линиями аспектов. Её читают как связанную систему, а не как набор независимых пар.', en: 'An aspect pattern is a recognizable geometric figure formed by aspects among several planets.' },
    shortAnswer: { ru: 'Большой тригон, Т-квадрат и Большой крест — разные конфигурации с собственным набором углов.', en: 'Grand trines, T-squares, and Grand Crosses are different multi-planet aspect patterns.' },
    aliases: { ru: ['конфигурация аспектов', 'аспектная фигура', 'фигура в натальной карте'], en: ['aspect pattern', 'aspect configuration'] },
    ruSections: [
      { title: 'Как находят фигуру', kind: 'calculation', paragraphs: ['Сначала рассчитывают обычные аспекты и их орбисы. Затем проверяют, соединяются ли линии в известную схему. Если один аспект слишком широк или отсутствует, полной конфигурации может не быть.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Фигура показывает, что несколько частей карты действуют как связанная конструкция. Планеты называют функции, знаки — способ проявления, дома — области, а геометрия задаёт характер связи.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Красивый рисунок на экране ещё не гарантирует признанную конфигурацию: программы используют разные наборы аспектов и орбисы.'] },
    ],
    relatedTopicIds: ['aspects-overview', 'grand-trine', 't-square', 'grand-cross', 'aspect-orb'],
  }),
  ...([
    ['grand-trine', 'Большой тригон', 'Grand trine', 'три планеты соединены тремя тригонами и образуют на круге треугольник', 'плавную взаимную поддержку трёх функций', ['aspect-trine', 'aspect-patterns', 'sign-elements']],
    ['t-square', 'Т-квадрат', 'T-square', 'две планеты стоят в оппозиции, а третья образует квадрат к каждой из них', 'напряжение, которое ищет выход через вершину фигуры', ['aspect-square', 'aspect-opposition', 'aspect-patterns']],
    ['grand-cross', 'Большой крест', 'Grand Cross', 'четыре точки образуют две оппозиции и четыре квадрата', 'устойчивую систему взаимных требований и противоречий', ['aspect-square', 'aspect-opposition', 'aspect-patterns']],
  ] as const).map(([id, ruTitle, enTitle, geometry, meaning, related]) => topic({
    id, category: 'synthesis', title: { ru: ruTitle, en: enTitle },
    summary: { ru: `${ruTitle} — конфигурация аспектов, в которой ${geometry}.`, en: `${enTitle} is a multi-planet aspect pattern.` },
    shortAnswer: { ru: `${ruTitle} описывает ${meaning}; точный смысл зависит от планет, знаков и домов.`, en: `${enTitle} is read through its planets, signs, houses, and exactness.` },
    aliases: { ru: [ruTitle.toLowerCase(), `${ruTitle.toLowerCase()} в натальной карте`], en: [enTitle.toLowerCase()] },
    ruSections: [
      { title: 'Геометрия', kind: 'calculation', paragraphs: [`В этой фигуре ${geometry}. Каждый входящий аспект должен укладываться в выбранный орбис.`] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: [`Конфигурацию связывают с ${meaning}. Это не готовый ярлык: одинаковая геометрия работает по-разному с разными планетами.`] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Один отдельный аспект того же типа ещё не образует конфигурацию. Для фигуры нужен полный набор связей между несколькими точками.'] },
    ],
    relatedTopicIds: related,
  })),
  topic({
    id: 'rulers-dispositors', category: 'synthesis',
    title: { ru: 'Управители и диспозиторы', en: 'Rulers and dispositors' },
    summary: { ru: 'Управитель — планета, связанная со знаком по правилам школы. Диспозитор планеты — управитель знака, в котором эта планета находится. Так астрологи строят цепочки связей внутри карты.', en: 'A dispositor is the ruler of the sign occupied by a planet; rulers link signs, houses, and planets.' },
    shortAnswer: { ru: 'Управитель карты, управитель дома и диспозитор — связанные, но не одинаковые роли.', en: 'Chart ruler, house ruler, and dispositor are related but distinct roles.' },
    aliases: { ru: ['управитель карты', 'управитель дома', 'диспозитор', 'цепочка диспозиторов', 'управитель'], en: ['chart ruler', 'house ruler', 'dispositor', 'dispositor chain'] },
    ruSections: [
      { title: 'Управитель дома', paragraphs: ['Обычно им называют планету, управляющую знаком на куспиде дома. В системе целых знаков это управитель знака, который образует весь дом.'] },
      { title: 'Управитель карты', paragraphs: ['Чаще всего так называют управителя знака Асцендента. Некоторые школы используют другие определения, поэтому термин стоит уточнять.'] },
      { title: 'Диспозитор', paragraphs: ['Если Венера находится в Овне, её диспозитором считают Марс, потому что Марс управляет Овном. Затем можно посмотреть знак Марса и продолжить цепочку.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Управительство — астрологическое правило символических связей. Оно не означает физического контроля одной планеты над другой.'] },
    ],
    relatedTopicIds: ['sign-rulership', 'house-cusp', 'ascendant', 'planetary-dignities', 'planets-overview'],
  }),
  topic({
    id: 'planetary-dignities', category: 'synthesis',
    title: { ru: 'Достоинства планет', en: 'Planetary dignities' },
    summary: { ru: 'Достоинства — традиционная система оценки того, насколько положение планеты в знаке соответствует приписанной ей роли. Основные термины: обитель, изгнание, экзальтация и падение.', en: 'Planetary dignities are traditional classifications of how a planet is placed by sign: domicile, detriment, exaltation, and fall.' },
    shortAnswer: { ru: 'Достоинство описывает условия символического проявления планеты, а не делает человека достойным или недостойным.', en: 'Dignity describes an astrological condition, not a person’s worth.' },
    aliases: { ru: ['достоинства планет', 'эссенциальные достоинства', 'обитель', 'изгнание', 'экзальтация', 'падение планеты'], en: ['planetary dignities', 'essential dignity', 'domicile', 'detriment', 'exaltation', 'fall'] },
    ruSections: [
      { title: 'Обитель и изгнание', paragraphs: ['В обители планета находится в знаке, которым управляет. Изгнанием называют противоположный знак. Традиционно это описывает более привычные или менее привычные условия для её символики.'] },
      { title: 'Экзальтация и падение', paragraphs: ['Экзальтация — знак особого возвышения функции планеты в традиционной таблице; падение — противоположный знак. Эти пары не выводятся из современной физики планет.'] },
      { title: 'Как это используют', kind: 'astrology', paragraphs: ['Достоинство — только один слой оценки. Астрологи также смотрят дом, аспекты, скорость, близость к Солнцу и роль планеты в конкретной карте.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Планета в падении не означает «плохого человека» или обречённость. Термины описывают правила традиционной техники, а не моральную оценку.'] },
    ],
    relatedTopicIds: ['sign-rulership', 'rulers-dispositors', 'planet-in-sign', 'planets-overview'],
  }),
  topic({
    id: 'composite-chart', category: 'compatibility',
    title: { ru: 'Композит', en: 'Composite chart' },
    summary: { ru: 'Композит — астрологическая карта отношений, построенная из средних точек между одноимёнными положениями двух натальных карт. Она не показывает реальное небо в момент рождения одного из людей.', en: 'A composite chart is built from midpoints between corresponding placements in two natal charts.' },
    shortAnswer: { ru: 'Синастрия сравнивает две реальные карты, а композит создаёт одну расчётную карту пары.', en: 'Synastry compares two charts; a composite creates one calculated relationship chart.' },
    aliases: { ru: ['композит', 'композитная карта', 'карта отношений'], en: ['composite chart', 'relationship composite'] },
    ruSections: [
      { title: 'Как его считают', kind: 'calculation', paragraphs: ['Для каждой пары одноимённых точек находят середину на зодиакальном круге: Солнце с Солнцем, Луну с Луной и так далее. Из этих средних положений собирают новую схему.'] },
      { title: 'Зачем его используют', kind: 'astrology', paragraphs: ['Композит трактуют как символическую структуру самих отношений: их общий стиль, устойчивые темы и противоречия. Индивидуальные карты при этом не исчезают.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['В синастрии смотрят аспекты между планетами двух людей. В композите читают аспекты внутри одной вычисленной карты. Это разные методы.'] },
    ],
    relatedTopicIds: ['synastry', 'two-chart-compatibility', 'interchart-aspects', 'aspects-overview'],
  }),
  topic({
    id: 'ephemerides', category: 'branches-tools',
    title: { ru: 'Эфемериды', en: 'Ephemerides' },
    summary: { ru: 'Эфемериды — таблицы или цифровые данные с рассчитанными положениями небесных тел на разные даты и время. По ним можно узнать долготу, скорость и другие координаты объекта.', en: 'Ephemerides are tables or data files of calculated celestial positions for specific dates and times.' },
    shortAnswer: { ru: 'Эфемериды — исходные координаты для расчёта карты, а не готовая астрологическая трактовка.', en: 'Ephemerides provide coordinates, not an astrological interpretation.' },
    aliases: { ru: ['эфемериды', 'эфемерида', 'таблица положений планет'], en: ['ephemeris', 'ephemerides', 'planet position table'] },
    ruSections: [
      { title: 'Что в них записано', kind: 'fact', paragraphs: ['Современные эфемериды содержат вычисленные координаты объектов на заданной шкале времени. Астрологические программы используют такие данные, а затем переводят их в знаки, дома и аспекты.'] },
      { title: 'Как ими пользовались раньше', kind: 'history', paragraphs: ['До компьютеров астрологи искали положения в печатных таблицах и интерполировали значения между строками. Сейчас ту же основу обычно предоставляет астрономический расчётный движок.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Эфемериды не являются прогнозом. Они сообщают, где рассчитан объект, но не что это «значит».'] },
    ],
    relatedTopicIds: ['degree-and-position', 'transits-current-sky', 'progressions', 'natal-chart-basics'],
  }),
  topic({
    id: 'degree-and-position', category: 'branches-tools',
    title: { ru: 'Градус и положение в карте', en: 'Degree and chart position' },
    summary: { ru: 'Градус — единица угла. Положение точки в зодиаке обычно записывают знаком и числом от нуля до двадцати девяти градусов внутри него; натальное положение относится к исходной карте, транзитное — к выбранному текущему моменту.', en: 'A degree measures angle; natal and transiting positions refer to different moments.' },
    shortAnswer: { ru: 'Знак показывает участок круга, градус — точное место внутри него, а слова «натальный» и «транзитный» указывают момент расчёта.', en: 'The sign gives the sector, the degree the precise location, and natal/transiting names the calculation moment.' },
    aliases: { ru: ['градус', 'натальное положение', 'транзитное положение', 'положение планеты', 'долгота'], en: ['degree', 'natal position', 'transiting position', 'longitude'] },
    ruSections: [
      { title: 'Как читается запись', kind: 'calculation', paragraphs: ['Например, пятнадцать градусов Тельца — середина тридцатиградусного участка Тельца. Для более точной записи градус делят на шестьдесят минут, а минуту — на шестьдесят секунд дуги.'] },
      { title: 'Натальное и транзитное', paragraphs: ['Натальное положение фиксирует расчётный момент рождения. Транзитное показывает небо на другую дату. Сравнение этих двух наборов координат образует метод транзитов.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Градус знака не равен градусу температуры. Положение в знаке также не сообщает дом без отдельного расчёта времени, места и системы домов.'] },
    ],
    relatedTopicIds: ['zodiac-geometry', 'ephemerides', 'transits-current-sky', 'natal-chart-basics', 'house-cusp'],
  }),
  topic({
    id: 'astrology-branches', category: 'branches-tools',
    title: { ru: 'Основные направления астрологии', en: 'Main branches of astrology' },
    summary: { ru: 'Натальная, хорарная, элективная и мунданная астрология задают карте разные вопросы. Метод определяется прежде всего тем, для какого момента строят карту и что пытаются по ней описать.', en: 'Natal, horary, electional, and mundane astrology use charts for different questions and moments.' },
    shortAnswer: { ru: 'Натальная карта относится к рождению, хорарная — к вопросу, элективная — к выбору времени, мунданная — к общественным событиям.', en: 'Natal concerns birth, horary a question, electional timing, and mundane collective events.' },
    aliases: { ru: ['натальная астрология', 'хорарная астрология', 'элективная астрология', 'мунданная астрология', 'виды астрологии'], en: ['natal astrology', 'horary astrology', 'electional astrology', 'mundane astrology', 'astrology branches'] },
    ruSections: [
      { title: 'Натальная астрология', paragraphs: ['Карту строят на момент и место рождения и используют для описания символической структуры жизни и характера. Это самый знакомый современному пользователю вид карты.'] },
      { title: 'Хорарная астрология', paragraphs: ['Карту строят на момент, когда вопрос был задан или понят астрологом. Её читают по специальным правилам, не подменяя натальной картой спрашивающего.'] },
      { title: 'Элективная астрология', paragraphs: ['Среди возможных будущих моментов выбирают время, которое по правилам школы считается более подходящим для начала конкретного дела.'] },
      { title: 'Мунданная астрология', paragraphs: ['Карты используют для обсуждения государств, общественных процессов, природных и политических событий. Слово происходит от латинского mundus — «мир».'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Это не четыре формата одного прогноза. У направлений разные исходные моменты, вопросы и правила интерпретации.'] },
    ],
    relatedTopicIds: ['astrology-overview', 'what-is-horoscope', 'natal-chart-basics', 'forecast-not-guarantee'],
    sourceIds: ['cambridge-astrology-history'],
  }),
  topic({
    id: 'astrocartography', category: 'branches-tools',
    title: { ru: 'Астрокартография', en: 'Astrocartography' },
    summary: { ru: 'Астрокартография — астрологический метод, который переносит угловые положения планет для выбранного момента на карту Земли. Линии показывают, где планета была бы на Асценденте, Десценденте, MC или IC.', en: 'Astrocartography maps where planets would be on the chart angles across Earth for a chosen moment.' },
    shortAnswer: { ru: 'Это географическое отображение углов карты, а не карта физического излучения планет на разные города.', en: 'It maps chart angles geographically, not physical planetary radiation over cities.' },
    aliases: { ru: ['астрокартография', 'астро картография', 'релокационная карта', 'карта линий планет'], en: ['astrocartography', 'astro cartography', 'relocation astrology'] },
    ruSections: [
      { title: 'Как строится карта', kind: 'calculation', paragraphs: ['Для одного момента рассчитывают, в каких точках Земли каждая планета находилась бы на одном из четырёх главных углов. Эти места соединяют линиями на географической карте.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Астрологи сравнивают линии с местами жизни, поездок или переезда и трактуют символику соответствующей планеты и угла. Часто метод дополняют отдельной релокационной картой города.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Линия не является физической границей и не гарантирует одинаковые события всем людям. Карта строится для конкретного исходного момента.'] },
    ],
    relatedTopicIds: ['angles-overview', 'ascendant', 'midheaven', 'birth-place-in-chart', 'natal-chart-basics'],
  }),
] satisfies readonly KnowledgeTopicSource[];
