import { defineKnowledgeTopic } from './topicBuilder';
import type { KnowledgeTopicSource } from './types';

const topic = defineKnowledgeTopic;

export const CYCLE_EXTENDED_TOPICS = [
  topic({
    id: 'lunar-cycle', category: 'moon-cycles',
    title: { ru: 'Лунный цикл', en: 'Lunar cycle' },
    summary: { ru: 'Лунный цикл — повторение фаз от одного новолуния до следующего. Он длится в среднем около двадцати девяти с половиной суток и связан с изменением положения Луны относительно Земли и Солнца.', en: 'The lunar phase cycle runs from one new moon to the next and lasts about 29.5 days.' },
    shortAnswer: { ru: 'Луна не меняет форму: с Земли мы видим разную долю её освещённой Солнцем половины.', en: 'The Moon does not change shape; we see different portions of its sunlit half.' },
    aliases: { ru: ['лунный цикл', 'цикл луны', 'синодический месяц', 'двадцать девять с половиной суток'], en: ['lunar cycle', 'synodic month', '29.5 days'] },
    ruSections: [
      { title: 'Как возникает цикл', kind: 'mechanism', paragraphs: ['Солнце всегда освещает примерно половину Луны. Пока Луна обращается вокруг Земли, меняется угол, под которым мы видим освещённую часть. Так последовательно возникают новолуние, растущие фазы, полнолуние и убывающие фазы.'] },
      { title: 'Почему не ровно месяц', kind: 'fact', paragraphs: ['За время одного оборота Луны Земля тоже проходит часть пути вокруг Солнца. Луне нужно ещё немного продвинуться, чтобы снова оказаться в той же фазовой геометрии. Поэтому цикл фаз длиннее её оборота относительно далёких звёзд.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Астрологи используют фазы как символические стадии процесса: начало, развитие, кульминацию и завершение. Это интерпретация цикла, а не физическое доказательство одинакового влияния на события или поведение.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Лунный цикл не равен календарному месяцу. Полнолуние не всегда является лунным затмением, а новолуние — солнечным. Для затмения требуется дополнительное выравнивание около лунных узлов.'] },
    ],
    relatedTopicIds: ['moon-phase', 'new-moon', 'full-moon', 'moon-first-quarter', 'moon-last-quarter', 'nodes-overview'],
    diagram: 'moon-phases', sourceIds: ['nasa-moon-phases', 'nasa-eclipses'],
  }),
  topic({
    id: 'moon-first-quarter', category: 'moon-cycles',
    title: { ru: 'Первая четверть Луны', en: 'First-quarter Moon' },
    summary: { ru: 'Первая четверть — фаза примерно через неделю после новолуния, когда с Земли освещённой выглядит половина видимого диска Луны.', en: 'First quarter occurs about a week after new moon, when half the visible lunar disk is illuminated.' },
    shortAnswer: { ru: 'Название говорит, что пройдена примерно четверть цикла, а не что видна четверть Луны.', en: 'The name marks one quarter of the cycle, not one quarter of the Moon being visible.' },
    aliases: { ru: ['первая четверть', 'первая четверть луны', 'растущая половина луны'], en: ['first quarter moon', 'first quarter'] },
    ruSections: [
      { title: 'Почему видна половина', kind: 'mechanism', paragraphs: ['Направления на Солнце и Луну образуют с Земли угол около девяноста градусов. Мы видим половину освещённой стороны и половину ночной стороны Луны.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Эту фазу обычно связывают с переходом от намерения к действию и с необходимостью преодолевать первые препятствия. Это символическая трактовка квадратуры Солнца и Луны.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Первая четверть — растущая фаза. В Северном и Южном полушариях освещённая часть визуально ориентирована по-разному.'] },
    ],
    relatedTopicIds: ['lunar-cycle', 'new-moon', 'waxing-moon', 'aspect-square', 'moon-last-quarter'],
    sourceIds: ['nasa-moon-phases'],
  }),
  topic({
    id: 'moon-last-quarter', category: 'moon-cycles',
    title: { ru: 'Последняя четверть Луны', en: 'Last-quarter Moon' },
    summary: { ru: 'Последняя четверть — фаза примерно через неделю после полнолуния, когда снова видна половина освещённого диска, но Луна уже убывает.', en: 'Last quarter occurs about a week after full moon, when half the visible disk is lit and the Moon is waning.' },
    shortAnswer: { ru: 'Это три четверти пути от прошлого новолуния и последняя крупная фаза перед новым циклом.', en: 'It marks three quarters of the way through the phase cycle.' },
    aliases: { ru: ['последняя четверть', 'третья четверть', 'убывающая половина луны'], en: ['last quarter moon', 'third quarter moon'] },
    ruSections: [
      { title: 'Как возникает', kind: 'mechanism', paragraphs: ['Луна снова находится примерно под прямым углом к направлению на Солнце, но с другой стороны цикла. Поэтому освещена противоположная половина видимого диска.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Фазу связывают с пересмотром результата, отсечением лишнего и завершением того, что началось раньше. Это символическая трактовка, а не обязательный сценарий недели.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Последняя четверть и первая четверть выглядят похожими, но относятся к разным половинам цикла: первая растёт, последняя убывает.'] },
    ],
    relatedTopicIds: ['lunar-cycle', 'full-moon', 'waning-moon', 'aspect-square', 'moon-first-quarter'],
    sourceIds: ['nasa-moon-phases'],
  }),
  topic({
    id: 'solar-eclipse', category: 'moon-cycles',
    title: { ru: 'Солнечное затмение', en: 'Solar eclipse' },
    summary: { ru: 'Солнечное затмение происходит в новолуние, когда Луна проходит между Землёй и Солнцем и её тень попадает на часть Земли.', en: 'A solar eclipse occurs at new moon when the Moon passes between Earth and the Sun and casts a shadow on Earth.' },
    shortAnswer: { ru: 'Не каждое новолуние даёт затмение: Луна должна находиться достаточно близко к одному из лунных узлов.', en: 'Not every new moon is an eclipse; the Moon must be near a lunar node.' },
    aliases: { ru: ['солнечное затмение', 'затмение солнца'], en: ['solar eclipse', 'eclipse of the sun'] },
    ruSections: [
      { title: 'Как возникает', kind: 'mechanism', paragraphs: ['Орбита Луны наклонена к плоскости земной орбиты. Обычно в новолуние Луна проходит чуть выше или ниже направления на Солнце. Затмение возможно только рядом с точками пересечения этих плоскостей — лунными узлами.'] },
      { title: 'Что видно', kind: 'fact', paragraphs: ['При полном затмении Луна закрывает яркий диск Солнца для узкой полосы Земли. При частном — закрывает только часть диска. Наблюдать Солнце без специальной защиты для глаз опасно.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Астрологи рассматривают солнечное затмение как усиленное новолуние и учитывают его знак, градус и связи с картой. Такая трактовка относится к традиции и не описывает физический механизм затмения.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Солнечное затмение бывает только около новолуния, но большинство новолуний проходит без затмения.'] },
    ],
    relatedTopicIds: ['new-moon', 'lunar-eclipse', 'nodes-overview', 'lunar-cycle'],
    sourceIds: ['nasa-eclipses'],
  }),
  topic({
    id: 'lunar-eclipse', category: 'moon-cycles',
    title: { ru: 'Лунное затмение', en: 'Lunar eclipse' },
    summary: { ru: 'Лунное затмение происходит в полнолуние, когда Земля оказывается между Солнцем и Луной, а Луна проходит через земную тень.', en: 'A lunar eclipse occurs at full moon when the Moon passes through Earth’s shadow.' },
    shortAnswer: { ru: 'Каждое лунное затмение приходится на полнолуние, но не каждое полнолуние становится затмением.', en: 'Every lunar eclipse occurs at full moon, but most full moons are not eclipses.' },
    aliases: { ru: ['лунное затмение', 'затмение луны', 'кровавая луна'], en: ['lunar eclipse', 'moon eclipse', 'blood moon'] },
    ruSections: [
      { title: 'Как возникает', kind: 'mechanism', paragraphs: ['Для затмения Солнце, Земля и Луна должны выстроиться достаточно точно. Это возможно, когда полнолуние проходит рядом с лунным узлом; в остальные месяцы Луна проходит выше или ниже земной тени.'] },
      { title: 'Почему Луна может стать красной', kind: 'fact', paragraphs: ['Во время полного затмения часть солнечного света проходит через атмосферу Земли. Короткие синие волны сильнее рассеиваются, а красные лучше доходят до Луны и отражаются обратно.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Лунное затмение трактуют как усиленное полнолуние и связывают с кульминацией или завершением. Это символическое чтение, а не гарантия внешнего события.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Обычное полнолуние не означает, что Луна входит в тень Земли. Освещённый полный диск и затмение — разные явления.'] },
    ],
    relatedTopicIds: ['full-moon', 'solar-eclipse', 'nodes-overview', 'aspect-opposition'],
    sourceIds: ['nasa-eclipses'],
  }),
  topic({
    id: 'direct-motion', category: 'retrogrades',
    title: { ru: 'Директное движение', en: 'Direct motion' },
    summary: { ru: 'Директным называют обычное видимое движение планеты по зодиаку в том направлении, которое принято считать прямым. Это описание того, как меняется её положение для наблюдателя с Земли.', en: 'Direct motion is the usual apparent direction of a planet against the zodiac as seen from Earth.' },
    shortAnswer: { ru: 'Директное и ретроградное движение — термины геоцентрического наблюдения, а не переключение двигателя планеты.', en: 'Direct and retrograde describe apparent geocentric motion, not a planet changing engines.' },
    aliases: { ru: ['директное движение', 'прямое движение', 'директная планета'], en: ['direct motion', 'prograde motion', 'direct planet'] },
    ruSections: [
      { title: 'Как это определяют', kind: 'calculation', paragraphs: ['Сравнивают эклиптическую долготу планеты в соседние моменты. Если она растёт в принятом направлении отсчёта, движение отмечают как директное; если уменьшается — как ретроградное.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Директное положение часто трактуют как более прямое выражение символики планеты. Но оно само по себе не делает планету сильной, удачной или простой.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Планеты постоянно продолжают движение по своим орбитам вокруг Солнца. «Назад» и «вперёд» здесь описывают их видимый путь на фоне звёзд.'] },
    ],
    relatedTopicIds: ['retrograde-motion', 'retrograde-station-direct', 'planetary-ingress', 'transits-current-sky'],
    sourceIds: ['nasa-retrograde'],
  }),
  topic({
    id: 'planetary-ingress', category: 'retrogrades',
    title: { ru: 'Ингресс', en: 'Ingress' },
    summary: { ru: 'Ингресс — момент, когда планета или другая точка переходит из одного знака зодиака в следующий. В эфемеридах это пересечение границы нулевого градуса нового знака.', en: 'An ingress is the moment a planet or point enters a new zodiac sign.' },
    shortAnswer: { ru: 'Ингресс — переход границы знака, а не аспект и не переход в новый дом.', en: 'An ingress is a sign boundary crossing, not an aspect or a house crossing.' },
    aliases: { ru: ['ингресс', 'вход планеты в знак', 'переход планеты в знак'], en: ['ingress', 'planet enters sign'] },
    ruSections: [
      { title: 'Как это определяется', kind: 'calculation', paragraphs: ['Зодиак состоит из двенадцати участков по тридцать градусов. Когда долгота объекта достигает начала следующего участка, фиксируют ингресс. При ретроградной петле объект может пересечь одну границу несколько раз.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Астрологи отмечают ингресс как смену знакового контекста, через который трактуется планета. Для медленных планет такой период длится дольше, для быстрых — короче.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Вход в знак не равен входу в дом: дома зависят от конкретной карты и системы домов.'] },
    ],
    relatedTopicIds: ['signs-overview', 'direct-motion', 'retrograde-motion', 'transits-current-sky', 'degree-and-position'],
  }),
  topic({
    id: 'planetary-cycle-return', category: 'retrogrades',
    title: { ru: 'Планетарный цикл и возвращение', en: 'Planetary cycle and return' },
    summary: { ru: 'Планетарный цикл — повторение взаимного положения планеты относительно выбранной точки отсчёта. Возвращением называют момент, когда транзитная планета снова достигает примерно той же зодиакальной долготы, что в исходной карте.', en: 'A planetary return occurs when a transiting planet reaches roughly its natal zodiac longitude again.' },
    shortAnswer: { ru: 'Возвращение — геометрическое повторение положения, а его астрологическое значение зависит от того, какая планета вернулась.', en: 'A return is a repeated position; its astrological meaning depends on the planet.' },
    aliases: { ru: ['планетарный цикл', 'возвращение планеты', 'планетарное возвращение', 'return chart'], en: ['planetary cycle', 'planetary return', 'return chart'] },
    ruSections: [
      { title: 'Как это определяется', kind: 'calculation', paragraphs: ['Берут долготу планеты в натальной карте и находят последующий момент, когда текущая долгота совпадает с ней. Из-за ретроградных петель точное совпадение иногда происходит несколько раз в одном цикле.'] },
      { title: 'Зачем строят отдельную карту', kind: 'astrology', paragraphs: ['Астрологи могут построить карту на точное время возвращения и читать её вместе с натальной. Солнечное, лунное и сатурново возвращения относятся к одному принципу, но имеют разную длительность цикла.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Возвращение не означает, что планета вернулась в ту же точку пространства. Сравнивается её видимое положение на зодиакальном круге относительно Земли.'] },
    ],
    relatedTopicIds: ['solar-return', 'lunar-return', 'saturn-return', 'transits-current-sky', 'retrograde-motion'],
  }),
  topic({
    id: 'progressions', category: 'forecasts',
    title: { ru: 'Прогрессии', en: 'Progressions' },
    summary: { ru: 'Прогрессии — астрологический метод, который символически сопоставляет короткий период после рождения с более длинным периодом жизни. В наиболее распространённых вторичных прогрессиях один день после рождения соответствует одному году жизни.', en: 'Progressions are an astrological timing method; in secondary progressions one day after birth symbolically corresponds to one year of life.' },
    shortAnswer: { ru: 'Прогрессии не утверждают, что день физически превращается в год. Это правило пересчёта, по которому строят дополнительную карту.', en: 'Progressions do not turn a day into a year physically; they use a symbolic conversion rule.' },
    aliases: { ru: ['прогрессии', 'вторичные прогрессии', 'день за год', 'secondary progressions'], en: ['progressions', 'secondary progressions', 'day for a year'] },
    keywords: { ru: ['прогрессивная луна', 'прогрессивное солнце', 'метод прогноза', 'эфемериды'], en: ['progressed moon', 'progressed sun', 'predictive method', 'ephemeris'] },
    ruSections: [
      { title: 'Что это на самом деле', kind: 'definition', paragraphs: ['Берут реальные положения планет в дни после рождения, но читают их как символическую шкалу последующих лет. Например, положения через тридцать дней используют для тридцатого года жизни.'] },
      { title: 'Как это считается', kind: 'calculation', paragraphs: ['Для вторичных прогрессий программа обращается к эфемеридам и сдвигает планеты по ключу «день за год». Быстрее всего заметно меняется прогрессивная Луна; дальние планеты за несколько десятков дней сдвигаются мало.'] },
      { title: 'Зачем это используют в астрологии', kind: 'astrology', paragraphs: ['Прогрессии обычно применяют для описания длительных внутренних изменений и этапов. Их сравнивают с натальной картой и транзитами, а не читают как самостоятельный календарь гарантированных событий.'] },
      { title: 'Прогрессии и дирекции', kind: 'confusion', paragraphs: ['Прогрессии используют фактическое движение планет с символическим масштабом времени. Дирекции перемещают точки по выбранному математическому ключу. В разговоре эти методы иногда смешивают, но расчёт у них разный.'] },
      { title: 'Откуда появился метод', kind: 'history', depth: 'deep', paragraphs: ['У прогрессий нет одного современного изобретателя. Разные способы символического разворачивания карты формировались в истории астрологии постепенно; сегодня под словом «прогрессии» чаще всего имеют в виду вторичные.'] },
    ],
    relatedTopicIds: ['directions', 'transits-current-sky', 'ephemerides', 'natal-vs-current-period', 'planetary-cycle-return'],
    sourceIds: ['astro-progressions'],
  }),
  topic({
    id: 'directions', category: 'forecasts',
    title: { ru: 'Дирекции', en: 'Directions' },
    summary: { ru: 'Дирекции — группа астрологических методов, которые математически сдвигают точки натальной карты по выбранному ключу времени. Разные виды дирекций используют разные правила движения.', en: 'Directions are predictive methods that mathematically move natal chart points by a chosen time key.' },
    shortAnswer: { ru: 'Дирекция — расчётный сдвиг карты, а не наблюдаемое положение планет сегодня.', en: 'A direction is a calculated shift, not today’s observed planetary position.' },
    aliases: { ru: ['дирекции', 'солярная дуга', 'первичные дирекции', 'solar arc'], en: ['directions', 'solar arc directions', 'primary directions'] },
    ruSections: [
      { title: 'Как работает метод', kind: 'calculation', paragraphs: ['В дирекциях каждой точке задают расчётное перемещение. В методе солнечной дуги все точки сдвигают примерно на столько, на сколько продвинулось прогрессивное Солнце; первичные дирекции используют движение небесной сферы и более сложную геометрию.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Астрологи ищут моменты, когда направленная точка образует точный аспект к натальной. Метод обычно читают вместе с транзитами, прогрессиями и контекстом исходной карты.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Дирекции, прогрессии и транзиты — не три названия одного расчёта. Транзиты показывают реальное текущее небо, прогрессии используют символический масштаб реального движения, дирекции — выбранный математический ключ.'] },
    ],
    relatedTopicIds: ['progressions', 'transits-current-sky', 'aspect-exact', 'natal-chart-basics'],
  }),
  topic({
    id: 'solar-return', category: 'forecasts',
    title: { ru: 'Соляр', en: 'Solar return' },
    summary: { ru: 'Соляр, или карта солнечного возвращения, строится на момент, когда Солнце возвращается примерно к той же эклиптической долготе, которую занимало при рождении. Это происходит раз в год около дня рождения.', en: 'A solar return chart is cast for the moment the Sun returns to its natal ecliptic longitude.' },
    shortAnswer: { ru: 'Соляр — отдельная карта точного солнечного возвращения, а не просто любой гороскоп на календарный год.', en: 'A solar return is a chart for an exact return moment, not any generic yearly horoscope.' },
    aliases: { ru: ['соляр', 'солнечное возвращение', 'карта соляра', 'solar return'], en: ['solar return', 'solar return chart', 'birthday chart'] },
    keywords: { ru: ['эклиптическая долгота', 'день рождения', 'возвращение солнца', 'прогностический метод'], en: ['ecliptic longitude', 'birthday', 'sun return', 'predictive method'] },
    ruSections: [
      { title: 'Что это на самом деле', kind: 'definition', paragraphs: ['Программа сравнивает текущее положение Солнца с его положением в натальной карте и находит момент совпадения долготы. Из-за календаря это может быть в день рождения, накануне или на следующий день.'] },
      { title: 'Как строят карту', kind: 'calculation', paragraphs: ['Для найденного момента рассчитывают обычную карту с планетами, домами и аспектами. Место расчёта выбирают по правилам школы: место нахождения человека, место жительства или место рождения. От выбора места меняются углы и дома, но не момент возвращения Солнца.'] },
      { title: 'Зачем это используют в астрологии', kind: 'astrology', paragraphs: ['Соляр читают как символическую карту тем года между двумя солнечными возвращениями и сопоставляют с натальной картой. Он не отменяет натальные положения и не гарантирует перечисленные события.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Соляр не равен общему прогнозу по знаку и не начинается автоматически в полночь дня рождения. Его время определяется точным возвращением Солнца к исходной долготе.'] },
      { title: 'Откуда появился метод', kind: 'history', depth: 'deep', paragraphs: ['Карты возвращений относятся к давней астрологической традиции. У метода нет одного известного современного автора; правила расчёта и чтения развивались постепенно.'] },
    ],
    relatedTopicIds: ['planetary-cycle-return', 'lunar-return', 'saturn-return', 'natal-chart-basics', 'transits-current-sky'],
    sourceIds: ['astro-solar-return'],
  }),
  topic({
    id: 'lunar-return', category: 'forecasts',
    title: { ru: 'Лунар', en: 'Lunar return' },
    summary: { ru: 'Лунар — карта, построенная на момент возвращения Луны к её натальной эклиптической долготе. Такое возвращение происходит примерно раз в двадцать семь с третью суток.', en: 'A lunar return chart is cast when the Moon returns to its natal ecliptic longitude.' },
    shortAnswer: { ru: 'Лунар использует возвращение Луны к натальному положению; это не то же самое, что новолуние или календарный лунный месяц.', en: 'A lunar return is not the same as a new moon or a calendar month.' },
    aliases: { ru: ['лунар', 'лунное возвращение', 'карта лунара', 'lunar return'], en: ['lunar return', 'lunar return chart'] },
    ruSections: [
      { title: 'Как это считается', kind: 'calculation', paragraphs: ['Программа находит момент совпадения текущей долготы Луны с натальной. Затем для этого времени и выбранного места строится карта с домами, углами и аспектами.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['В астрологии лунар читают как краткосрочную карту месяца между двумя лунными возвращениями, особенно обращая внимание на Луну и углы. Его сопоставляют с натальной картой.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Лунный цикл фаз длится около двадцати девяти с половиной суток, а возвращение Луны к положению относительно звёзд — около двадцати семи с третью. Это разные циклы.'] },
    ],
    relatedTopicIds: ['planetary-cycle-return', 'solar-return', 'planet-moon', 'lunar-cycle', 'natal-chart-basics'],
  }),
  topic({
    id: 'saturn-return', category: 'forecasts',
    title: { ru: 'Сатурново возвращение', en: 'Saturn return' },
    summary: { ru: 'Сатурново возвращение — период, когда транзитный Сатурн возвращается к своей натальной долготе. Первый такой цикл обычно завершается примерно в возрасте двадцати девяти с половиной лет.', en: 'A Saturn return occurs when transiting Saturn returns to its natal zodiac longitude, roughly every 29.5 years.' },
    shortAnswer: { ru: 'Это конкретный вид планетарного возвращения, а не один день неизбежного кризиса.', en: 'It is a planetary return period, not one guaranteed day of crisis.' },
    aliases: { ru: ['сатурново возвращение', 'возвращение сатурна', 'saturn return'], en: ['saturn return', 'return of saturn'] },
    ruSections: [
      { title: 'Как его определяют', kind: 'calculation', paragraphs: ['Сравнивают долготу текущего Сатурна с натальной. Из-за ретроградной петли точное совпадение иногда происходит один раз, а иногда повторяется несколько раз в течение более длинного периода.'] },
      { title: 'В астрологии', kind: 'astrology', paragraphs: ['Современная астрология связывает возвращение Сатурна с пересмотром ответственности, границ и долгосрочных решений. Это широкая трактовка цикла, а не обещание увольнения, брака или другого конкретного события.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Возраст около тридцати лет сам по себе не доказывает, что любое переживание вызвано Сатурном. Точные даты зависят от натального положения и реального движения планеты.'] },
    ],
    relatedTopicIds: ['planet-saturn', 'planetary-cycle-return', 'transits-current-sky', 'retrograde-motion'],
  }),
] satisfies readonly KnowledgeTopicSource[];
