
import { Language } from "./types";

export const APP_NAME = "Lumia";

/**
 * Lumia Oracle Chat — системная инструкция для чата с Астрой.
 * Тон согласован с Lumia: тёплый, умный, личный, без кринжа.
 */
export const SYSTEM_INSTRUCTION_ASTRA = `
Ты — Lumia: современный умный астролог, который переводит карту в ясный, личный язык. Ты отвечаешь в чате как добрый друг-эксперт.

Тон: тёплый, умный, личный, эмоционально резонирующий. Не холодный, не роботизированный, не псевдо-духовная чепуха.
Обращайся на «ты». Пиши коротко и по делу. Не запугивай, не предсказывай ужасов.
Не говори «ты должен/обязан» — используй «можно попробовать», «может быть полезно».
Используй 1–3 иконки (не эмодзи), не перегружай.

Задачи:
– объяснять натальную карту и астрологические темы понятными словами;
– давать поддержку и реалистичные советы без фатализма;
– опираться на данные карты, но переводить на язык жизни: характер, привычки, эмоции, отношения, работа;
– не использовать сухие формулировки («Солнце в 10 доме»). Говори: «по характеру ты…», «в работе тебе важно…»;
– избегать категоричных обещаний; говорить в формате тенденций и возможностей;
– не давать медицинских, юридических или финансовых диагнозов.

Структура: короткие абзацы, списки. Не повторять знаки и градусы дословно — интерпретировать.
`;

export const TRANSLATIONS = {
  ru: {
    loading: "Космическая загрузка...",
    nav: {
      home: "Главная",
      chart: "Натальная карта",
      synastry: "Союз",
      oracle: "Оракул",
      settings: "Настройки"
    },
    header: {
      back: "Назад",
      wallet: "Кошелёк Lumi"
    },
    hook: {
      analyzing: "Считываю звездную карту...",
      typing: "Lumia печатает...",
      intro: "Приветствую, {name}. Я изучила твою карту...",
      done: "Это лишь 10% потенциала вашей натальной карты. Бесплатный расчет завершен.\n\nЧтобы раскрыть всю карту, получить персональный прогноз на день, месяц и узнать о кармических задачах, активируйте подписку.",
      cta_button: "Узнать больше"
    },
    premium_preview: {
      title: "Lumia Premium",
      tagline: "Больше глубины в твоей карте",
      subtitle: "Открой второй слой чтения: больше смысла, больше контекста, больше личной глубины.",
      feature_oracle: "Личное guidance",
      feature_oracle_desc: "Oracle и прогнозы, которые продолжают чтение карты, а не живут отдельно.",
      feature_forecast: "Прогнозы с контекстом",
      feature_forecast_desc: "День, неделя и месяц через призму твоей натальной карты.",
      feature_deep: "Все темы Deep Dive",
      feature_deep_desc: "Любовь, карьера, вызовы и кармические уроки как отдельный слой анализа.",
      feature_passport: "Полное натальное чтение",
      feature_passport_desc: "Больше деталей по ключевым паттернам, планетам и внутренним противоречиям.",
      cta: "Открыть 1 неделю • 250 Stars"
    },
    paywall: {
      title: "Lumia Premium",
      subtitle: "Бесплатный слой уже открыт. Lumia Premium раскрывает любовь, карьеру, рост и более глубокую интерпретацию карты.",
      feature1: "Deep Dive: Любовь, Карьера, Вызовы и Карма",
      feature2: "Более полное натальное чтение по главным паттернам карты",
      feature3: "Более глубокая совместимость в Synastry",
      feature4: "Oracle и прогнозы как личное продолжение разбора",
      cta: "Открыть Lumia Premium • 250 Stars",
      footer: "7 дней полной глубины Lumia"
    },
    dashboard: {
      welcome: "С возвращением,",
      passport: "Космический паспорт",
      element: "Стихия",
      ruler: "Управитель",
      menu_analysis: "Натальная карта",
      menu_forecast: "Мой Прогноз",
      menu_synastry: "Совместимость",
      menu_oracle: "Личный Оракул",
      moon_impact: "Луна Сегодня",
      daily_transit: "Транзит Дня",
      daily_advice: "Совет Дня",
      premium_badge: "PRO",
      solar_system_title: "База Знаний: Планеты",
      get_premium: "Купить Premium",
      evolution: "Эволюция Души",
      level: "Уровень",
      stats_intuition: "Интуиция",
      stats_confidence: "Уверенность",
      context_weather: "Погода за окном",
      horoscope_today: "Твой день",
      forecast_date: "Дата прогноза",
      mood: "Настроение",
      color: "Цвет",
      special_day: "Сегодняшнее чтение уже готово",
      detailed_forecast: "Открыть чтение дня →",
      horoscope_footer: "Ежедневная навигация через твою натальную карту",
      chart_subtitle: "Личность, судьба, карма и прогнозы",
      synastry_subtitle: "Совместимость",
      synastry_free: "Бесплатный тизер",
      synastry_hint: "Сохранённые карты можно переиспользовать без повторного ввода.",
      oracle_subtitle: "Спроси у Lumia",
      loading_weather: "Загрузка погоды...",
      set_city_hint: "Укажите город в настройках для отображения погоды",
      tap_settings: "Нажмите, чтобы открыть настройки →",
      my_charts: "Мои карты",
      my_charts_subtitle: "Управление картами и слотами",
      charts_overview_title: "Сохранённые карты",
      charts_overview_hint: "Сохранённые карты можно быстро использовать в синастрии и других сценариях Lumia.",
      charts_overview_cta: "Открыть карты"
    },
    chart: {
      title: "Твоя Натальная Карта",
      summary: "Твоё чтение",
      deeper: "Deep Dive",
      loading_wisdom: "Загружаю космическую мудрость...",
      unlock_full: "Открыть Deep Dive с Lumia Premium",
      greeting: "Привет",
      friend: "друг",
      soul_connector: "с душой",
      soul_suffix: "",
      chart_legend: "Солнце — твоя основа и характер, Луна — эмоции и привычки, Асцендент — первое впечатление и стиль поведения.",
      loading_intro: "Твоя натальная карта",
      placements: "Полный Анализ",
      tap_to_learn: "Раскрыть",
      premium_lock: "PRO",
      section_personality: "Личность и Характер",
      section_love: "Любовь и Отношения",
      section_career: "Карьера и Самореализация",
      section_weakness: "Зоны Роста и Вызовы",
      section_karma: "Кармическая Задача",
      free_layer_label: "Бесплатный слой",
      core_title: "Опорная карта",
      core_body: "Солнце, Луна и Асцендент дают первый ясный слой понимания — как ты проявляешься, чувствуешь и входишь в мир.",
      deeper_intro: "Deep Dive — это второй слой чтения. Сначала ты видишь основу, затем раскрываешь более точные темы жизни.",
      deeper_free_label: "В бесплатном чтении",
      deeper_free_body: "Один открытый Deep Dive показывает, как Lumia читает твою карту глубже, но без перегруза.",
      deeper_premium_label: "С Lumia Premium",
      deeper_premium_body: "Любовь, карьера, вызовы и кармические уроки становятся отдельными глубокими темами вместо одного общего портрета.",
      topic_free_included: "Включено",
      topic_premium_badge: "Premium",
      topic_personality_teaser: "Какой внутренний ритм стоит за твоим характером, реакциями и способом проживать жизнь.",
      topic_love_teaser: "Как ты сближаешься, чего ждёшь от связи и где рождается настоящая близость.",
      topic_career_teaser: "Как карта показывает твой способ реализовываться, выбирать направление и удерживать смысл.",
      topic_weakness_teaser: "Где карта указывает на уязвимости, повторяющиеся паттерны и точки роста.",
      topic_karma_teaser: "Какие уроки тянут тебя в зрелость и какие темы карта возвращает снова и снова.",
      premium_value_title: "Lumia Premium открывает следующий слой",
      premium_value_body: "Не просто больше текста, а более точные темы, в которых карта начинает говорить про любовь, реализацию, вызовы и кармический вектор отдельно.",
      my_charts_title: "Мои карты",
      my_charts_body: "Основная карта, сохранённые профили и синастрия живут в одном месте.",
      my_charts_cta: "Открыть карты",
      forecast_title: "Персональный Прогноз",
      forecast_day: "На Сегодня",
      forecast_week: "На Неделю",
      forecast_month: "На Месяц",
      free_teaser_title: "Космический Паспорт"
    },
    charts: {
      title: "Мои карты",
      slots: "Слотов",
      slots_used: "карт",
      no_charts: "Пока нет сохранённых карт.",
      add_chart: "Добавить карту",
      buy_slot: "Купить слот за",
      buy_slot_lumi: "Lumi",
      limit_reached: "Достигнут лимит карт. Купите слот за Lumi.",
      balance: "Баланс",
      purchasing: "Покупка...",
      loading: "Загрузка карт...",
      value_title: "Карты в Lumia — это не просто список.",
      value_body: "Сохранённые карты можно быстро открывать, сравнивать в синастрии и использовать без повторного ввода данных.",
      action_title: "Пространство твоих карт",
      action_body: "Здесь живут основная карта, сохранённые профили и слоты для новых сравнений.",
      primary_role: "Ваша базовая карта для Lumia",
      saved_role: "Сохранённая карта для совместимости и сравнений",
      use_in_synastry: "В синастрию",
      open_chart: "Открыть",
      set_primary: "Сделать основной",
      delete: "Удалить",
      primary_badge: "Основная",
      slots_full_title: "Слоты заполнены",
      slots_full_body: "Ещё один слот нужен, чтобы сохранить карту партнёра и быстро возвращаться к синастрии.",
      slots_need_more_lumi: "Не хватает Lumi для нового слота.",
      enough_balance_hint: "Баланса хватает: можно открыть ещё один слот и сразу сохранить новую карту.",
      empty_title: "Начните со своей карты",
      empty_body: "Когда здесь появятся карты партнёра, их можно будет использовать в синастрии без повторного ввода.",
      single_chart_body: "Ещё одна сохранённая карта откроет быстрое сравнение в синастрии.",
      open_wallet: "Открыть кошелёк Lumi",
      add_form_title: "Новая карта",
      default_chart_name: "Моя карта",
      field_name: "Имя",
      field_birth_date: "Дата рождения",
      field_birth_time: "Время рождения",
      field_birth_place: "Место рождения",
      field_birth_place_placeholder: "Москва, Россия",
      error_insufficient_lumi: "Недостаточно Lumi",
      error_fill_required: "Заполните дату и место рождения",
      error_no_free_slots: "Свободных слотов для новой карты сейчас нет",
      error_create_failed: "Ошибка создания карты",
      error_generic: "Ошибка",
      error_delete_failed: "Ошибка удаления",
      create: "Создать",
      creating: "Создание...",
      cancel: "Отмена",
      saved_for_synastry_hint: "Сохранённые карты партнёров уже готовы к повторному использованию в синастрии."
    },
    synastry: {
      title: "Синастрия",
      desc: "Узнайте космическую совместимость с партнером.",
      partner_from_manual: "Ввести вручную",
      partner_from_charts: "Выбрать из моих карт",
      optional_more: "Дополнительно (для более точного анализа)",
      partner_name: "Имя Партнера",
      calc_btn: "Рассчитать Совместимость",
      score: "Совместимость",
      emotional: "Эмоциональная связь",
      intellectual: "Интеллект и общение",
      challenge: "Кармический урок",
      input_title: "Данные Партнера",
      brief_btn: "Краткий обзор (Бесплатно)",
      full_btn: "Глубокий разбор (Премиум)",
      loading: "Считываем звездную совместимость...",
      primary_title: "Ваша сторона",
      partner_title: "Партнёр",
      primary_hint: "В синастрии всегда используется текущая основная карта.",
      selected_saved: "Сохранённая карта",
      selected_manual: "Ручной ввод",
      no_saved_title: "Нет карт партнёра",
      no_saved_body: "Сохраните ещё одну карту в «Моих картах», чтобы запускать синастрию без повторного ввода данных.",
      open_charts: "Открыть «Мои карты»",
      buy_slot: "Купить слот",
      change_partner: "Сменить партнёра",
      compare_again: "Сравнить другую карту",
      result_saved_badge: "Из сохранённой карты",
      result_manual_badge: "Ручной ввод",
      saved_first_hint: "Лучше выбирать сохранённую карту: так пару можно открывать повторно без нового ввода.",
      manual_hint: "Ручной ввод подойдёт для разовой проверки, если карта ещё не сохранена.",
      mode_label: "Источник карты партнёра",
      details_label: "Данные партнёра",
      details_body: "Выберите сохранённую карту или введите данные вручную для разового сравнения.",
      cta_label: "Какой слой совместимости открыть",
      partner_name_placeholder: "Введите имя",
      birth_date_label: "Дата рождения",
      partner_sign_label: "Знак партнёра",
      birth_time_label: "Время рождения",
      relationship_type_label: "Тип отношений",
      birth_place_label: "Место рождения",
      birth_place_placeholder: "Город, страна",
      relationship_romantic: "Романтика",
      relationship_friendship: "Дружба",
      relationship_family: "Семья",
      relationship_work: "Работа",
      selected_partner_title: "Выбранный партнёр",
      saved_list_title: "Сохранённые карты",
      result_title: "Чтение совместимости"
    },
    settings: {
      title: "Настройки",
      profile: "Профиль",
      language: "Язык",
      theme: "Оформление",
      theme_dark: "Полночь",
      theme_light: "Латте",
      edit: "Редактировать",
      subscription: "Подписка",
      plan_pro: "Lumia Premium активна",
      plan_basic: "Базовый план",
      plan_active: "Активна",
      subscription_body: "Базовый слой Lumia уже открыт. Lumia Premium добавляет более глубокие чтения, синастрию и Оракул без ощущения перегруза.",
      restore: "Восстановить",
      switch_lang: "English",
      save: "Сохранить",
      admin: "Админ-панель",
      admin_body: "Внутренний доступ для управления пользователями, Lumi и уведомлениями.",
      wallet_title: "Кошелёк Lumi",
      wallet_body: "Баланс, история и пополнение Lumi",
      charts_title: "Мои карты",
      charts_body: "Управление натальными картами",
      theme_body: "Выберите более мягкий или более контрастный ритм интерфейса.",
      language_ru: "Русский",
      language_en: "English",
      language_body: "Язык основных экранов и интерпретаций Lumia.",
      weather_title: "Погода и Луна",
      weather_body: "Настройка города для погодного слоя",
      weather_city: "Город",
      weather_placeholder: "Например: Москва или Moscow",
      weather_helper: "Укажите название города от 2 до 64 символов.",
      weather_empty: "Город не указан",
      weather_ready: "Погода и фаза луны будут отображаться на главном экране",
      weather_error: "Не удалось сохранить город. Попробуйте ещё раз.",
      edit_inline: "Изменить",
      cancel: "Отмена",
      saving: "Сохранение...",
      profile_name: "Имя",
      profile_birth_place: "Место рождения",
      profile_date_time: "Дата и время"
    },
    oracle: {
      placeholder: "Задай вопрос звездам...",
      intro: "Здравствуй. Я вижу твою карту. Что тревожит твою душу сегодня?"
    },
    horoscope: {
      title: "Гороскоп на сегодня",
      subtitle: "Ежедневная навигация через твою натальную карту.",
      today_layer_label: "Ежедневный слой",
      loading: "Настраиваю твоё чтение на сегодня...",
      signals_title: "Текущая энергия",
      signals_body: "Короткие ориентиры дня, чтобы быстрее почувствовать его ритм.",
      number: "Число дня",
      reading_title: "Твоя навигация на сегодня",
      reading_body: "Это не отдельный прогноз-генератор, а сегодняшний срез твоей карты.",
      foundation_label: "Твоя основа",
      foundation_body: "Солнечный знак задаёт общий тон, а сама ежедневная интерпретация опирается на твою натальную карту.",
      context_title: "Астрологический контекст",
      context_body: "Луна и текущий транзит помогают понять, почему день ощущается именно так.",
      moon_impact_title: "Лунный акцент",
      transit_focus_title: "Фокус транзита",
      bridge_label: "Как это связано с Lumia",
      bridge_title: "Гороскоп — слой на сегодня. Натальная карта — твоя основа.",
      bridge_body: "Если хочется понять не только настроение дня, но и устойчивые паттерны характера, отношений и самореализации, вернись к натальной карте.",
      open_chart: "Открыть натальную карту",
      premium_title: "Дальше начинается Deep Dive",
      premium_body: "В Lumia Premium карта раскрывается по темам: любовь, карьера, вызовы и кармический вектор.",
      premium_cta: "Посмотреть Deep Dive",
      empty_title: "Сегодняшнее чтение пока недоступно",
      empty_body: "Дневной слой не загрузился, но натальная карта по-прежнему остаётся твоей личной основой.",
      empty_cta: "Открыть натальную карту",
      persist_notice: "Показываем свежий гороскоп, но он пока не сохранился в базе.",
      stale_notice: "Показываем последнюю доступную версию гороскопа, пока свежая загрузка недоступна.",
      fallback_error: "Не удалось загрузить гороскоп"
    },
    planets: {
      sun: "Солнце", moon: "Луна", mercury: "Меркурий", venus: "Венера", 
      mars: "Марс", jupiter: "Юпитер", saturn: "Сатурн", earth: "Земля"
    },
    zodiac: {
      Aries: "Овен",
      Taurus: "Телец",
      Gemini: "Близнецы",
      Cancer: "Рак",
      Leo: "Лев",
      Virgo: "Дева",
      Libra: "Весы",
      Scorpio: "Скорпион",
      Sagittarius: "Стрелец",
      Capricorn: "Козерог",
      Aquarius: "Водолей",
      Pisces: "Рыбы"
    },
    elements: {
      Fire: "Огонь",
      Water: "Вода",
      Air: "Воздух",
      Earth: "Земля"
    }
  },
  en: {
    loading: "Cosmic Loading...",
    nav: {
      home: "Home",
      chart: "Natal Chart",
      synastry: "Synastry",
      oracle: "Oracle",
      settings: "Settings"
    },
    header: {
      back: "Back",
      wallet: "Lumi Wallet"
    },
    hook: {
      analyzing: "Reading the star map...",
      typing: "Lumia is typing...",
      intro: "Greetings, {name}. I have studied your chart...",
      done: "This is only 10% of your chart's potential. Free calculation complete.\n\nTo reveal your full chart, get daily forecasts, and uncover karmic tasks, activate subscription.",
      cta_button: "Learn more"
    },
    premium_preview: {
      title: "Lumia Premium",
      tagline: "More depth in your chart",
      subtitle: "Unlock the second layer of interpretation: more meaning, more context, more personal depth.",
      feature_oracle: "Guidance with context",
      feature_oracle_desc: "Oracle and forecasts that continue your chart reading instead of feeling separate.",
      feature_forecast: "Forecasts with context",
      feature_forecast_desc: "Day, week, and month through the lens of your natal chart.",
      feature_deep: "All Deep Dive themes",
      feature_deep_desc: "Love, career, challenges, and karmic lessons as distinct interpretation layers.",
      feature_passport: "Full natal reading",
      feature_passport_desc: "More detail on core patterns, planetary dynamics, and inner tensions.",
      cta: "Unlock 1 Week • 250 Stars"
    },
    paywall: {
      title: "Lumia Premium",
      subtitle: "Your free layer is already open. Lumia Premium reveals love, career, growth, and a deeper interpretation of your chart.",
      feature1: "Deep Dive: Love, Career, Challenges, and Karma",
      feature2: "A fuller natal reading built around your chart’s main patterns",
      feature3: "A richer compatibility layer in Synastry",
      feature4: "Oracle and forecasts as a personal continuation of the reading",
      cta: "Unlock Lumia Premium • 250 Stars",
      footer: "7 days of full Lumia depth"
    },
    dashboard: {
      welcome: "Welcome back,",
      passport: "Cosmic Passport",
      element: "Element",
      ruler: "Ruler",
      menu_analysis: "Natal Chart",
      menu_forecast: "My Forecast",
      menu_synastry: "Compatibility",
      menu_oracle: "Personal Oracle",
      moon_impact: "Moon Today",
      daily_transit: "Daily Transit",
      daily_advice: "Daily Advice",
      premium_badge: "PRO",
      solar_system_title: "Knowledge Base: Planets",
      get_premium: "Get Premium",
      evolution: "Soul Evolution",
      level: "Level",
      stats_intuition: "Intuition",
      stats_confidence: "Confidence",
      context_weather: "Weather outside",
      horoscope_today: "Today's guidance",
      forecast_date: "Forecast date",
      mood: "Mood",
      color: "Color",
      special_day: "Today's reading is ready",
      detailed_forecast: "Open today's reading →",
      horoscope_footer: "Daily guidance through your natal chart",
      chart_subtitle: "Personality, Fate, Karma & Forecasts",
      synastry_subtitle: "Check compatibility",
      synastry_free: "Free preview",
      synastry_hint: "Reuse saved charts without entering the data again.",
      oracle_subtitle: "Ask Lumia anything",
      loading_weather: "Loading weather...",
      set_city_hint: "Set city in settings to see weather",
      tap_settings: "Tap to open settings →",
      my_charts: "My Charts",
      my_charts_subtitle: "Manage charts & slots",
      charts_overview_title: "Saved charts",
      charts_overview_hint: "Saved charts can be reused in Synastry and future Lumia flows.",
      charts_overview_cta: "Open charts"
    },
    chart: {
      title: "Natal Chart",
      summary: "Your Reading",
      deeper: "Deep Dive",
      loading_wisdom: "Loading cosmic wisdom...",
      unlock_full: "Unlock Deep Dive with Lumia Premium",
      greeting: "Hey",
      friend: "friend",
      soul_connector: "with a",
      soul_suffix: " soul",
      chart_legend: "Sun = your core, Moon = emotions and habits, Rising = first impression and style.",
      loading_intro: "Your natal chart",
      placements: "Full Analysis",
      tap_to_learn: "Reveal",
      premium_lock: "PRO",
      section_personality: "Personality & Character",
      section_love: "Love & Relationships",
      section_career: "Career & Self-Realization",
      section_weakness: "Growth Areas & Challenges",
      section_karma: "Karmic Mission",
      free_layer_label: "Free layer",
      core_title: "Core Chart",
      core_body: "Sun, Moon, and Rising give the first clear layer of understanding — how you show up, feel, and meet the world.",
      deeper_intro: "Deep Dive is the second layer of interpretation. First you see the foundation, then you open the life themes in more depth.",
      deeper_free_label: "Included in free reading",
      deeper_free_body: "One open Deep Dive topic shows how Lumia reads your chart more deeply without overwhelming the first experience.",
      deeper_premium_label: "With Lumia Premium",
      deeper_premium_body: "Love, career, challenges, and karmic lessons become distinct themes instead of one general portrait.",
      topic_free_included: "Included",
      topic_premium_badge: "Premium",
      topic_personality_teaser: "See the inner rhythm behind your character, reactions, and the way you move through life.",
      topic_love_teaser: "Understand how you bond, what closeness means to you, and where intimacy becomes real.",
      topic_career_teaser: "See how your chart points to direction, motivation, and the kind of work that feels meaningful.",
      topic_weakness_teaser: "Find where your chart shows repeating patterns, pressure points, and real growth edges.",
      topic_karma_teaser: "See which lessons keep returning and what kind of maturity your chart is pushing you toward.",
      premium_value_title: "Lumia Premium opens the next layer",
      premium_value_body: "Not just more text, but more precise themes where your chart starts speaking separately about love, purpose, challenges, and karmic direction.",
      my_charts_title: "My Charts",
      my_charts_body: "Your primary chart, saved profiles, and Synastry tools live in one place.",
      my_charts_cta: "Open charts",
      forecast_title: "Personal Forecast",
      forecast_day: "Today",
      forecast_week: "This Week",
      forecast_month: "This Month",
      free_teaser_title: "Cosmic Passport"
    },
    charts: {
      title: "My Charts",
      slots: "Slots",
      slots_used: "charts",
      no_charts: "No saved charts yet.",
      add_chart: "Add chart",
      buy_slot: "Buy slot for",
      buy_slot_lumi: "Lumi",
      limit_reached: "Chart limit reached. Buy a slot with Lumi.",
      balance: "Balance",
      purchasing: "Purchasing...",
      loading: "Loading charts...",
      value_title: "Saved charts are reusable assets in Lumia.",
      value_body: "Open them anytime, reuse them in Synastry, and stop re-entering partner birth data.",
      action_title: "Your chart space",
      action_body: "This is where your primary chart, saved profiles, and slots for future comparisons live.",
      primary_role: "Your base chart in Lumia",
      saved_role: "Reusable chart for compatibility and comparisons",
      use_in_synastry: "Use in Synastry",
      open_chart: "Open",
      set_primary: "Set primary",
      delete: "Delete",
      primary_badge: "Primary",
      slots_full_title: "Your slots are full",
      slots_full_body: "One more slot lets you save another partner chart and return to Synastry faster.",
      slots_need_more_lumi: "You need more Lumi to unlock another slot.",
      enough_balance_hint: "You have enough balance to unlock another slot and save a new chart right away.",
      empty_title: "Start with your chart",
      empty_body: "When partner charts are saved here, they can be reused in Synastry without retyping the data.",
      single_chart_body: "One more saved chart unlocks faster Synastry comparisons.",
      open_wallet: "Open Lumi Wallet",
      add_form_title: "New chart",
      default_chart_name: "My Chart",
      field_name: "Name",
      field_birth_date: "Birth date",
      field_birth_time: "Birth time",
      field_birth_place: "Birth place",
      field_birth_place_placeholder: "Moscow, Russia",
      error_insufficient_lumi: "Insufficient Lumi",
      error_fill_required: "Fill date and birth place",
      error_no_free_slots: "No free slots are available right now",
      error_create_failed: "Failed to create chart",
      error_generic: "Error",
      error_delete_failed: "Delete failed",
      create: "Create",
      creating: "Creating...",
      cancel: "Cancel",
      saved_for_synastry_hint: "Your saved partner charts are ready to reuse in Synastry."
    },
    synastry: {
      title: "Synastry",
      desc: "Discover cosmic compatibility with a partner.",
      partner_from_manual: "Enter manually",
      partner_from_charts: "Select from my charts",
      optional_more: "Optional (for more accurate analysis)",
      partner_name: "Partner Name",
      calc_btn: "Calculate Compatibility",
      score: "Compatibility",
      emotional: "Emotional Bond",
      intellectual: "Intellectual Bond",
      challenge: "Karmic Challenge",
      input_title: "Partner Details",
      brief_btn: "Brief Overview (Free)",
      full_btn: "Deep Analysis (Premium)",
      loading: "Reading star compatibility...",
      primary_title: "You",
      partner_title: "Partner",
      primary_hint: "Synastry always uses your current primary chart on your side.",
      selected_saved: "Saved chart",
      selected_manual: "Manual input",
      no_saved_title: "No partner charts saved yet",
      no_saved_body: "Save another chart in My Charts to compare again without re-entering partner details.",
      open_charts: "Open My Charts",
      buy_slot: "Buy slot",
      change_partner: "Change partner",
      compare_again: "Compare another chart",
      result_saved_badge: "From saved chart",
      result_manual_badge: "Manual input",
      saved_first_hint: "Saved charts are the fastest way to reopen Synastry later.",
      manual_hint: "Manual input is best for one-off comparisons.",
      mode_label: "Partner chart source",
      details_label: "Partner details",
      details_body: "Choose a saved chart or enter the details manually for a one-time comparison.",
      cta_label: "Choose the compatibility layer",
      partner_name_placeholder: "Enter name",
      birth_date_label: "Birth date",
      partner_sign_label: "Partner sign",
      birth_time_label: "Birth time",
      relationship_type_label: "Relationship type",
      birth_place_label: "Birth place",
      birth_place_placeholder: "City, country",
      relationship_romantic: "Romantic",
      relationship_friendship: "Friendship",
      relationship_family: "Family",
      relationship_work: "Work",
      selected_partner_title: "Selected partner",
      saved_list_title: "Saved charts",
      result_title: "Compatibility reading"
    },
    settings: {
      title: "Settings",
      profile: "Profile",
      language: "Language",
      theme: "Theme",
      theme_dark: "Midnight",
      theme_light: "Latte",
      edit: "Edit Profile",
      subscription: "Subscription",
      plan_pro: "Lumia Premium active",
      plan_basic: "Basic plan",
      plan_active: "Active",
      subscription_body: "Lumia already opens your essential reading. Premium adds deeper interpretation layers, richer synastry, and Oracle without turning the app into noise.",
      restore: "Restore",
      switch_lang: "Русский",
      save: "Save Changes",
      admin: "Admin Panel",
      admin_body: "Internal access for user management, Lumi operations, and notifications.",
      wallet_title: "Lumi Wallet",
      wallet_body: "Balance, history, and Lumi top-up",
      charts_title: "My Charts",
      charts_body: "Manage natal charts",
      theme_body: "Choose a softer or more contrast-driven interface rhythm.",
      language_ru: "Russian",
      language_en: "English",
      language_body: "Language for Lumia's main screens and readings.",
      weather_title: "Weather & Moon",
      weather_body: "Set a city for the weather layer",
      weather_city: "City",
      weather_placeholder: "e.g. Moscow or London",
      weather_helper: "Enter a city name from 2 to 64 characters.",
      weather_empty: "City not set",
      weather_ready: "Weather and moon phase will be shown on the main screen",
      weather_error: "Failed to save city. Please try again.",
      edit_inline: "Edit",
      cancel: "Cancel",
      saving: "Saving...",
      profile_name: "Name",
      profile_birth_place: "Birth place",
      profile_date_time: "Date & time"
    },
    oracle: {
      placeholder: "Ask the stars...",
      intro: "Greetings. I see your chart. What weighs on your soul today?"
    },
    horoscope: {
      title: "Today's Horoscope",
      subtitle: "Daily guidance through your natal chart.",
      today_layer_label: "Daily layer",
      loading: "Preparing your reading for today...",
      signals_title: "Current energy",
      signals_body: "A few quick signals to help you feel the rhythm of the day faster.",
      number: "Number of the day",
      reading_title: "Your guidance for today",
      reading_body: "This is not a detached forecast generator, but today’s slice of your chart.",
      foundation_label: "Your foundation",
      foundation_body: "Your Sun sign sets the overall tone, while the daily interpretation is still grounded in your natal chart.",
      context_title: "Astrological context",
      context_body: "The Moon and the current transit help explain why the day feels the way it does.",
      moon_impact_title: "Moon tone",
      transit_focus_title: "Transit focus",
      bridge_label: "How this fits Lumia",
      bridge_title: "Horoscope is today’s layer. Natal is your foundation.",
      bridge_body: "If you want to understand not just the mood of the day but the deeper patterns of character, relationships, and purpose, return to your natal chart.",
      open_chart: "Open Natal Chart",
      premium_title: "Deep Dive is the next layer",
      premium_body: "With Lumia Premium, your chart opens into distinct themes: love, career, challenges, and karmic direction.",
      premium_cta: "See Deep Dive",
      empty_title: "Today's reading is not available yet",
      empty_body: "The daily layer did not load, but your natal chart still remains your personal foundation.",
      empty_cta: "Open Natal",
      persist_notice: "Showing a fresh horoscope, but it has not been saved yet.",
      stale_notice: "Showing the latest available horoscope while a fresh one is unavailable.",
      fallback_error: "Failed to load horoscope"
    },
    planets: {
      sun: "Sun", moon: "Moon", mercury: "Mercury", venus: "Venus", 
      mars: "Mars", jupiter: "Jupiter", saturn: "Saturn", earth: "Earth"
    },
    zodiac: {
      Aries: "Aries",
      Taurus: "Taurus",
      Gemini: "Gemini",
      Cancer: "Cancer",
      Leo: "Leo",
      Virgo: "Virgo",
      Libra: "Libra",
      Scorpio: "Scorpio",
      Sagittarius: "Sagittarius",
      Capricorn: "Capricorn",
      Aquarius: "Aquarius",
      Pisces: "Pisces"
    },
    elements: {
      Fire: "Fire",
      Water: "Water",
      Air: "Air",
      Earth: "Earth"
    }
  }
};

export const getText = (lang: Language, key: string) => {
   const keys = key.split('.');
   let current: any = TRANSLATIONS[lang];
   for (const k of keys) {
       if (current[k] === undefined) return key;
       current = current[k];
   }
   return current;
};

export const getZodiacSign = (lang: Language, sign: string): string => {
  const zodiacTranslations = TRANSLATIONS[lang].zodiac as Record<string, string>;
  return zodiacTranslations[sign] || sign;
};

export const getElement = (lang: Language, element: string): string => {
  const elementTranslations = TRANSLATIONS[lang].elements as Record<string, string>;
  return elementTranslations[element] || element;
};
