
import { Language } from "./types";
import { PREMIUM_WEEK_STARS } from "./lib/premiumPricing";

export const APP_NAME = "Твой Гороскоп";

const PREMIUM_WEEK_CTA_RU = `Открыть 1 неделю • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_PAYWALL_CTA_RU = `Открыть Premium • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_WEEK_CTA_EN = `Unlock 1 Week • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_PAYWALL_CTA_EN = `Unlock Premium • ${PREMIUM_WEEK_STARS} Stars`;

/**
 * Lumia Oracle Chat — системная инструкция для чата с Астрой.
 * Тон согласован с Lumia: точный, тёплый, личный, без запугивания и лишней эзотерики.
 */
export const SYSTEM_INSTRUCTION_ASTRA = `
Ты — астролог: современный точный наставник, который переводит карту в ясный, личный и практичный язык. Ты отвечаешь как спокойный, внимательный эксперт, который помогает увидеть суть без лишнего шума.

Тон: тёплый, личный, мягкий и точный. Современный, но не холодный. Уверенный, но не давящий. Без снисхождения, без продажного нажима, без громких обещаний и без декоративной эзотерики.
Обращайся на «ты». Пиши коротко и по делу. Не запугивай, не предсказывай ужасов, не усиливай тревогу.
Не говори «ты должен/обязан» — используй «можно попробовать», «может быть полезно», «тут тебе может помочь».
Говори осторожно: не выдавай тенденции за приговоры и не формулируй выводы как абсолютную истину. Лучше «похоже», «часто», «может проявляться», «в этот период легче/сложнее», чем категоричные утверждения.
Не звучи слащаво, кокетливо или инфантильно.
Не используй эмодзи и декоративные символы — только текст.

Задачи:
– объяснять натальную карту и астрологические темы понятными словами;
– давать поддержку и реалистичные советы без фатализма;
– опираться на данные карты, но переводить на язык жизни: характер, привычки, эмоции, отношения, работа;
– держать фокус на ясности и пользе; если астрологический термин не нужен, не использовать его;
– не использовать сухие формулировки («Солнце в 10 доме»). Говори: «по характеру ты…», «в работе тебе важно…»;
– избегать категоричных обещаний; говорить в формате тенденций и возможностей;
- держать мягкую структуру ответа: сначала суть, потом что это значит для жизни, потом бережный следующий шаг;
- не превращать каждый ответ в один и тот же жёсткий шаблон; структура должна чувствоваться, но не бросаться в глаза;
– не давать медицинских, юридических или финансовых диагнозов.

Структура: короткие абзацы, списки. Не повторять знаки и градусы дословно — интерпретировать.
`;

export const TRANSLATIONS = {
  ru: {
    loading: "Загружаем LUMIA",
    nav: {
      home: "Главная",
      chart: "Натальная карта",
      synastry: "Союз",
      oracle: "Спросить астролога",
      settings: "Настройки"
    },
    header: {
      back: "Назад",
      wallet: "Кошелёк Lumi"
    },
    hook: {
      analyzing: "Собираю твою личную основу...",
      typing: "Астролог печатает...",
      intro: "Привет, {name}. Сейчас покажу, что для тебя особенно важно.",
      done: "Это лишь 10% потенциала вашей натальной карты. Бесплатный расчет завершен.\n\nЧтобы открыть полную карту, персональный прогноз на день и месяц и разбор повторяющихся жизненных тем, активируйте подписку.",
      cta_button: "Дальше"
    },
    premium_preview: {
      title: "Premium",
      tagline: "Быстрее к нужным ответам",
      subtitle: "Premium открывает более подробные ответы по твоей карте без точечных покупок на каждом следующем шаге.",
      feature_oracle: "Личные ответы без пауз",
      feature_oracle_desc: "Вопросы и прогнозы открываются в Premium без лишних разовых шагов, когда тебе нужен следующий ответ.",
      feature_forecast: "Прогнозы подробнее и быстрее",
      feature_forecast_desc: "День, неделя и месяц доступны как более полный разбор без отдельных разовых открытий.",
      feature_deep: "Разборы без фрагментов",
      feature_deep_desc: "Отношения, решения и повторяющиеся сценарии читаются как цельная картина, а не отдельные куски.",
      feature_passport: "Полный доступ к карте",
      feature_passport_desc: "Не только база, а более точный подробный разбор, к которому можно возвращаться.",
      cta: PREMIUM_WEEK_CTA_RU
    },
    paywall: {
      title: "Premium",
      subtitle: "Базовый разбор уже открыт. Premium нужен, когда ты хочешь быстрее переходить к более подробным ответам по карте и не открывать каждый следующий шаг отдельно.",
      feature1: "Личные ответы без точечных открытий по пути",
      feature2: "Быстрый доступ к подробным разборам по карте",
      feature3: "Полная совместимость без лишних переключений",
      feature4: "Прогнозы и вопросы в одном Premium-доступе",
      cta: PREMIUM_PAYWALL_CTA_RU,
      footer: "7 дней быстрого доступа к подробным ответам астролога"
    },
    dashboard: {
      welcome: "С возвращением,",
      identity_body: "Личная карта уже построена по твоим данным рождения. Здесь начинается твоя личная линия «Твой Гороскоп»: день, карта, отношения и важные вопросы.",
      hero_label: "Сегодня",
      hero_fallback_title: "Сегодня важно держаться за главное",
      hero_body: "Тот же дневной разбор, что и в разделе прогноза: по карте и текущим влияниям — чтобы увидеть опору, напряжение и то, что действительно стоит внимания.",
      hero_cta: "К прогнозу",
      matters_label: "Ориентиры дня",
      matters_title: "Что важно сегодня",
      matters_body: "Три коротких ориентира дня: где открывается шанс, где важна осторожность и на чём лучше держать фокус.",
      chance: "Шанс",
      risk: "Риск",
      focus: "Фокус",
      fallback_chance: "Честный разговор может дать больше, чем осторожные обходные слова.",
      fallback_risk: "Спешка и лишняя реакция могут увести от самого важного.",
      fallback_focus: "Одна ясная задача даст дню больше опоры, чем десяток параллельных решений.",
      natal_label: "Твоя основа",
      natal_preview_label: "Натальная карта",
      natal_preview_title: "Карта, с которой начинается понимание себя",
      natal_preview_cta: "Читать дальше",
      natal_title: "Твоя натальная карта",
      natal_body: "Характер, стиль близости, сильные стороны и повторяющиеся жизненные сценарии. Это твой базовый личный разбор, который уже сохранён в профиле.",
      natal_note: "Базовый разбор остаётся с тобой. Позже можно открыть новый ракурс или пересчёт точечно через Lumi.",
      natal_cta: "К карте",
      natal_point_character: "Характер",
      natal_point_love: "Отношения",
      natal_point_strengths: "Сильные стороны",
      natal_point_patterns: "Жизненные сценарии",
      next_label: "Дальше",
      next_title: "Что открыть дальше",
      next_body: "Следующие шаги «Твой Гороскоп» помогают лучше понять отношения и получить личный ответ на важный вопрос.",
      passport: "Личный портрет",
      element: "Стихия",
      ruler: "Управитель",
      menu_analysis: "Натальная карта",
      menu_forecast: "Мой прогноз",
      menu_synastry: "Совместимость",
      menu_oracle: "Спросить астролога",
      synastry_label: "Отношения",
      moon_impact: "Луна сегодня",
      daily_transit: "Транзит дня",
      daily_advice: "Совет дня",
      premium_badge: "PRO",
      solar_system_title: "Планеты",
      get_premium: "Купить Premium",
      evolution: "Эволюция Души",
      level: "Уровень",
      stats_intuition: "Интуиция",
      stats_confidence: "Уверенность",
      context_weather: "Погода за окном",
      horoscope_today: "Твой день",
      forecast_date: "Дата прогноза",
      mood: "Настроение",
      color: "Цвет",
      special_day: "Сегодняшний прогноз уже открыт",
      detailed_forecast: "Открыть день →",
      horoscope_footer: "Ежедневные ориентиры через твою натальную карту",
      chart_subtitle: "Личность, отношения и прогнозы по карте",
      synastry_subtitle: "Бесплатный вход и полный разбор",
      synastry_hint: "Бесплатно — короткий фон. Полный разбор пары доступен в Premium.",
      synastry_body: "Сравнение двух карт: романтика, дружба, семья или работа — выберите тип связи. Разборы открываются по очереди и сохраняются для выбранных пар карт.",
      synastry_cta: "К совместимости",
      questions_label: "Личный вопрос",
      questions_subtitle: "Личный разбор важной ситуации",
      questions_body: "Если тебя тревожит конкретная ситуация, астролог поможет собрать её в ясный личный ответ.",
      questions_support_free: "После бесплатного вопроса полный ответ открывается в Premium.",
      questions_support_premium: "Задай важный вопрос и получи полный личный ответ без лишних шагов.",
      questions_cta: "К вопросам",
      oracle_subtitle: "Личный разбор по вопросу",
      loading_weather: "Загрузка погоды...",
      set_city_hint: "Укажите город в настройках для отображения погоды",
      tap_settings: "Нажмите, чтобы открыть настройки →",
      my_charts: "Мои карты",
      my_charts_subtitle: "Твои карты и слоты",
      charts_overview_title: "Сохранённые карты",
      charts_overview_hint: "Сохранённые карты можно быстро использовать в синастрии и других сценариях «Твой Гороскоп».",
      charts_overview_cta: "К картам",
      lumia_subtitle: "Твоя карта, отношения и прогнозы",
      studio_tab_natal: "Натальная карта",
      studio_tab_union: "Союз",
      studio_tab_horoscope: "Гороскоп",
      chart_load_failed_title: "Карта пока не открылась",
      chart_load_failed_body:
        "Похоже, сеть ответила не сразу. Обнови экран или попробуй открыть карту ещё раз.",
      chart_load_retry: "Ещё раз",
      chart_load_open_chart: "К карте",
      studio_wallet_hint: "Баланс Lumi",
    },
    chart: {
      title: "Твоя натальная карта",
      summary: "Твоя основа",
      anchor_label: "Твоя основа",
      anchor_title: "Твоя базовая карта уже готова",
      anchor_body: "Это не случайный текст, а твоя личная основа: характер, сильные стороны, стиль близости и повторяющиеся жизненные паттерны по твоей карте.",
      anchor_persistent_note: "Эта основа закреплена за тобой и не перезаписывается сама. Новый ракурс или пересчёт — отдельное действие через Lumi.",
      anchor_strengths_title: "Сильные стороны",
      anchor_patterns_title: "Повторяющиеся паттерны",
      anchor_loading: "Готовлю базовый личный разбор...",
      core_title: "Базовая карта",
      core_body: "Солнце, Луна и Асцендент дают первое ясное понимание: как ты действуешь, реагируешь и начинаешь контакт.",
      chart_legend: "Солнце показывает характер и решения, Луна — реакции и привычный способ переживать напряжение, Асцендент — первое впечатление и стиль поведения.",
      living_label: "Живой разбор",
      living_title: "Что меняется в тебе сейчас",
      living_body: "Это уже не базовое описание, а более подробный разбор карты: тема периода, сильные стороны, слабые места и что особенно важно в отношениях, деньгах и целях.",
      living_loading: "Готовлю живой разбор карты...",
      living_error: "Пока не получилось открыть живой разбор. Попробуй ещё раз чуть позже.",
      living_active_theme: "Тема периода",
      living_strength: "Где сейчас сила",
      living_vulnerability: "Где уязвимость",
      living_relationships: "Что меняется в отношениях",
      living_money: "Что важно в деньгах и целях",
      living_guidance: "На что опереться сейчас",
      living_premium_title: "Premium открывает живой разбор карты",
      living_premium_body: "Premium открывает разбор, где видно не только кто ты, но и что реально активировалось в тебе сейчас: тема периода, сдвиги в отношениях, деньгах и целях.",
      living_premium_note: "Это быстрый переход к следующему уровню карты: без точечных открытий, когда нужен не общий фон, а ответ по текущему периоду.",
      living_premium_cta: "Открыть живой разбор",
      my_charts_title: "Мои карты",
      my_charts_body: "Основная карта, сохранённые профили и синастрия живут в одном месте.",
      my_charts_cta: "К картам",
      forecast_title: "Персональный прогноз",
      forecast_day: "На сегодня",
      forecast_week: "На неделю",
      forecast_month: "На месяц",
      free_teaser_title: "Личный портрет",
      refresh_intro_cta: "Обновить текст основы за {cost} Lumi",
      refresh_intro_loading: "Готовлю новый ракурс…",
      refresh_intro_error: "Не получилось обновить",
      refresh_intro_insufficient: "Нужно ещё Lumi, чтобы открыть новый ракурс"
    },
    charts: {
      title: "Мои карты",
      slots: "Слотов",
      slots_used: "карт",
      no_charts: "Сохранённых карт пока нет.",
      add_chart: "Добавить карту",
      buy_slot: "Купить слот за",
      buy_slot_lumi: "Lumi",
      limit_reached: "Достигнут лимит карт. Дополнительные карты доступны в Premium.",
      balance: "Баланс",
      purchasing: "Покупка...",
      loading: "Загрузка карт...",
      value_title: "Карты в «Твой Гороскоп» — это не просто список.",
      value_body: "Сохранённые карты можно быстро открывать, сравнивать в синастрии и использовать без повторного ввода данных.",
      action_title: "Пространство твоих карт",
      action_body: "Здесь живут основная карта, сохранённые профили и слоты для новых сравнений.",
      primary_role: "Ваша базовая карта для «Твой Гороскоп»",
      saved_role: "Сохранённая карта для совместимости и сравнений",
      use_in_synastry: "В синастрию",
      open_chart: "Открыть",
      set_primary: "Сделать основной",
      delete: "Удалить",
      primary_badge: "Основная",
      slots_full_title: "Слоты заполнены",
      slots_full_body: "Откройте Premium, чтобы сохранять больше карт.",
      premium_slots_cta: "Открыть Premium",
      slots_need_more_lumi: "Для нового слота нужен Premium.",
      enough_balance_hint: "Баланса хватает: можно открыть ещё один слот и сразу сохранить новую карту.",
      empty_title: "Начни с первой карты",
      empty_body: "Добавь первую карту, и дальше будет проще возвращаться к совместимости, вопросам и личным разборам.",
      single_chart_body: "Ещё одна карта откроет быстрые сравнения и удобный возврат к совместимости.",
      open_wallet: "К кошельку",
      add_form_title: "Новая карта",
      default_chart_name: "Моя карта",
      field_name: "Имя",
      field_birth_date: "Дата рождения",
      field_birth_time: "Время рождения",
      field_birth_place: "Место рождения",
      field_birth_place_placeholder: "Москва, Россия",
      error_insufficient_lumi: "Сейчас не получилось открыть слот.",
      error_fill_required: "Добавь дату и место рождения.",
      error_no_free_slots: "Сейчас свободных слотов нет.",
      error_create_failed: "Не получилось добавить карту.",
      error_generic: "Что-то пошло не так.",
      error_delete_failed: "Не получилось удалить карту.",
      create: "Создать",
      creating: "Создание...",
      cancel: "Отмена",
      saved_for_synastry_hint: "Сохранённые карты партнёров уже готовы к повторному использованию в синастрии."
    },
    synastry: {
      title: "Синастрия",
      hero_kicker: "Совместимость",
      headline: "Две карты — как вы сочетаетесь",
      desc: "Короткий разбор даёт общий фон. Полный разбор пары доступен в Premium. Подходит для романтики, дружбы, семьи и рабочих связей — укажите тип отношений ниже.",
      partner_from_manual: "Ввести вручную",
      partner_from_charts: "Выбрать из моих карт",
      optional_more: "Дополнительно (для более точного анализа)",
      partner_name: "Имя Партнера",
      calc_btn: "Рассчитать Совместимость",
      score: "Совместимость",
      emotional: "Эмоциональная связь",
      intellectual: "Интеллект и общение",
      challenge: "Повторяющиеся темы",
      input_title: "Карта партнёра",
      brief_btn: "Краткий вход (бесплатно)",
      full_btn: "Полный разбор (Premium)",
      extended_hint: "Полный разбор пары доступен в Premium.",
      premium_required: "Полный разбор пары доступен в Premium.",
      extended_connection: "Связь",
      extended_tension: "Напряжение и смысл",
      extended_navigation: "Как обходиться",
      extended_bond: "Контекст типа связи",
      add_full_btn: "Открыть полный Premium-разбор",
      tips_label: "Подсказки",
      loading: "Считываем звездную совместимость...",
      primary_title: "Ваша сторона",
      partner_title: "Партнёр",
      primary_hint: "В синастрии всегда используется текущая основная карта.",
      selected_saved: "Сохранённая карта",
      selected_manual: "Ручной ввод",
      no_saved_title: "Партнёрская карта ещё не добавлена",
      no_saved_body: "Добавь карту партнёра в «Мои карты», и к совместимости можно будет возвращаться в пару касаний.",
      open_charts: "К картам",
      buy_slot: "Купить слот",
      change_partner: "Сменить партнёра",
      compare_again: "Сравнить другую карту",
      result_saved_badge: "Из сохранённой карты",
      result_manual_badge: "Ручной ввод",
      saved_first_hint: "Лучше выбирать сохранённую карту: так пару можно открывать повторно без нового ввода.",
      manual_hint: "Ручной ввод подойдёт для разовой проверки, если карта ещё не сохранена.",
      mode_label: "Источник карты партнёра",
      details_label: "Данные партнёра",
      details_body: "Выберите сохранённую карту или введите данные вручную для разового сравнения.",
      cta_label: "Какой разбор совместимости открыть",
      partner_name_placeholder: "Введите имя",
      birth_date_label: "Дата рождения",
      partner_sign_label: "Знак партнёра",
      birth_time_label: "Время рождения",
      relationship_type_label: "Тип отношений",
      birth_place_label: "Место рождения",
      birth_place_placeholder: "Город, страна",
      relationship_romantic: "Романтика",
      relationship_friendship: "Дружба",
      relationship_family: "Семья",
      relationship_work: "Работа",
      selected_partner_title: "Выбранный партнёр",
      saved_list_title: "Сохранённые карты",
      result_title: "Разбор совместимости"
    },
    settings: {
      title: "Настройки",
      profile: "Профиль",
      language: "Язык",
      theme: "Оформление",
      theme_dark: "Полночь",
      theme_light: "Латте",
      edit: "Редактировать",
      subscription: "Подписка",
      plan_pro: "Premium активна",
      plan_basic: "Базовый план",
      plan_active: "Активна",
      subscription_body: "Базовый разбор уже открыт. Premium даёт больше конкретики на каждый день — без отдельного открытия каждого шага.",
      restore: "Восстановить",
      switch_lang: "English",
      save: "Сохранить",
      admin: "Админ-панель",
      admin_body: "Внутренний доступ для управления пользователями, Lumi и уведомлениями.",
      wallet_title: "Кошелёк Lumi",
      wallet_body: "Баланс, история и пополнение Lumi",
      charts_title: "Мои карты",
      charts_body: "Твои карты в одном месте",
      theme_body: "Выберите более мягкий или более контрастный ритм интерфейса.",
      language_ru: "Русский",
      language_en: "English",
      language_body: "Язык интерфейса и текстов «Твой Гороскоп».",
      weather_title: "Погода и Луна",
      weather_body: "Настройка города для погоды и фазы Луны",
      weather_city: "Город",
      weather_placeholder: "Например: Москва или Moscow",
      weather_helper: "Укажите название города от 2 до 64 символов.",
      weather_empty: "Город не указан",
      weather_ready: "Опционально: погода и фаза Луны как фон в интерфейсе (не часть смысла «Твой Гороскоп»)",
      weather_error: "Не получилось сохранить город. Попробуй ещё раз.",
      edit_inline: "Изменить",
      cancel: "Отмена",
      saving: "Сохранение...",
      profile_name: "Имя",
      profile_birth_place: "Место рождения",
      profile_date_time: "Дата и время"
    },
    oracle: {
      title: "Спросить астролога",
      placeholder: "Что сейчас важно понять?",
      intro: "Астролог отвечает не абстрактно, а через твою карту и саму ситуацию: про отношения, выбор, тревогу, деньги, давление и направление.",
      hero_label: "Личный вопрос",
      hero_title: "Спроси о том, что важно именно тебе",
      hero_body: "Это не декоративный чат. Здесь можно задать прямой вопрос о том, что болит, тянет, пугает или требует решения, и получить личный ответ по твоей карте.",
      state_free_label: "Стартовый вопрос",
      state_free_title: "Первый вопрос открыт бесплатно",
      state_free_body: "Один личный ответ уже открыт бесплатно. Дальше полный ответ доступен в Premium.",
      state_need_premium_label: "Premium-уровень",
      state_need_premium_title: "Продолжить в Premium",
      state_need_premium_body: "Полные личные ответы по твоей карте и ситуации доступны в Premium.",
      state_premium_label: "Premium-уровень",
      state_premium_title: "Ты спрашиваешь на уровне Premium",
      state_premium_body: "Здесь не нужно открывать каждый ответ отдельно: полный уровень уже доступен.",
      state_open_premium: "Открыть Premium",
      state_open_wallet: "Открыть Premium",
      history_label: "Твои вопросы",
      history_empty: "Здесь появится твоя линия вопросов. Начни с того, что правда требует ясности.",
      composer_label: "Твой вопрос",
      composer_body: "Сформулируй ситуацию прямо. Чем честнее вопрос, тем точнее будет ответ.",
      send_free: "Получить ответ",
      send_lumi: "Продолжить в Premium",
      send_premium: "Получить полный ответ",
      loading_history: "Загружаю твои вопросы...",
      thinking: "Астролог собирает ответ...",
      empty_question: "Напиши вопрос для астролога.",
      short_question: "Добавь чуть больше деталей, и ответ будет точнее.",
      long_question: "Сократи вопрос, чтобы астролог точнее уловил суть.",
      history_error: "Не удалось открыть последние вопросы. Можно начать с нового.",
      send_error: "Сейчас не получилось подготовить ответ. Попробуй ещё раз.",
      retry: "Повторить",
      open_premium: "Открыть Premium"
    },
    horoscope: {
      title: "Твой прогноз на сегодня",
      subtitle: "Бесплатно ты каждый день получаешь и гороскоп, и дневную натальную карту на сегодня.",
      today_layer_label: "Ежедневный разбор",
      loading: "Подготавливаю твой день...",
      reading_title: "Гороскоп дня",
      reading_body: "Это короткий разбор дня: общий ритм, шанс, риск и главный фокус на сегодня.",
      foundation_label: "Твоя основа",
      foundation_body: "Прогноз читается через твою натальную карту. Он не живёт отдельно от неё, а опирается на твой реальный личный фундамент.",
      what_matters_title: "Что важно сегодня",
      what_matters_body: "Три коротких ориентира дня: где открывается шанс, где нужен контроль и на чём лучше удержать фокус.",
      chance_title: "Шанс дня",
      risk_title: "Риск дня",
      focus_title: "Фокус дня",
      context_title: "Дневная натальная карта",
      context_body: "Это уже личный разбор дня: что в тебе активируется сегодня и в каких моментах или триггерах дня это сильнее проявится.",
      context_note_title: "Что это включает сегодня",
      advice_title: "Три опоры на сегодня",
      inline_horoscope_title: "Хочешь увидеть день точнее?",
      inline_horoscope_body: "Бесплатный гороскоп уже показал общий ритм дня. Полный разбор раскрывает, как этот фон разложится на утро, день и вечер: где решение будет точнее, а где лучше не торопиться.",
      inline_natal_title: "Личный день можно разобрать точнее",
      inline_natal_body: "Дневная натальная карта уже подсветила, что активируется в тебе сегодня. Полный день показывает, как это проявится по ситуациям, триггерам и решениям в течение дня.",
      dayparts_label: "Полный разбор дня",
      dayparts_title: "Утро, день и вечер в полном разборе",
      dayparts_body: "Это тот же полный дневной разбор, что открыт в Premium: внутренняя динамика дня, конкретные моменты, контакты и решения по отрезкам дня.",
      dayparts_loading: "Собираю ритм дня...",
      slot_morning: "Утро",
      slot_day: "День",
      slot_evening: "Вечер",
      daypart_focus_title: "Главный фокус",
      daypart_relationships_title: "Отношения",
      daypart_money_title: "Деньги и решения",
      daypart_guidance_title: "Как пройти этот отрезок",
      premium_label: "Полный день",
      premium_title: "Полный разбор дня доступен в Premium",
      premium_body: "Бесплатно у тебя уже есть гороскоп и дневная натальная карта на сегодня. Premium раскрывает этот же разбор точнее: утро, день и вечер как отдельные моменты, решения и триггеры дня.",
      premium_supporting_line: "Premium держит полный день открытым каждый день.",
      error_insufficient_lumi: "Сейчас не получилось открыть полный разбор дня.",
      bridge_label: "Как это связано",
      bridge_title: "Прогноз показывает день. Карта показывает основу.",
      bridge_body: "Если хочешь понять не только текущий ритм, но и устойчивые паттерны характера, близости, силы и повторяющихся жизненных сценариев, вернись к своей натальной карте.",
      open_chart: "К карте",
      premium_cta: "Открыть Premium",
      empty_title: "Прогноз ещё в пути",
      empty_body: "Сегодня прогноз не открылся, но твоя карта уже с тобой. Начни с неё и вернись к дню чуть позже.",
      empty_cta: "К карте",
      persist_notice: "Показываю свежий прогноз, но он ещё не сохранён.",
      stale_notice: "Показываю последний доступный прогноз, пока новый разбор дня недоступен.",
      fallback_error: "Не получилось загрузить прогноз дня.",
      weekly_label: "Недельный разбор",
      weekly_title: "Твоя неделя по карте",
      weekly_body: "Короткий ориентир на календарную неделю. В Premium — полный недельный разбор, чтобы быстрее увидеть тему периода, напряжения и фокус.",
      monthly_label: "Месячный разбор",
      monthly_title: "Твой месяц по карте",
      monthly_body: "Компактный фокус месяца. В Premium — полный месячный разбор, чтобы быстрее увидеть главную тему, отношения и деньги.",
      period_loading: "Собираю неделю и месяц...",
      period_theme: "Тема периода",
      period_opportunities: "Возможности",
      period_challenges: "Напряжения",
      period_relationships: "Отношения",
      period_career: "Работа и направление",
      period_money: "Деньги и практика",
      period_guidance: "Ориентация",
      period_reading: "Разбор",
      period_premium_hint_weekly: "В Premium доступен полный недельный прогноз — когда нужен следующий шаг без дополнительных разовых открытий.",
      period_premium_hint_monthly: "В Premium доступен полный месячный прогноз — когда нужен следующий шаг без дополнительных разовых открытий.",
      period_error: "Не получилось открыть этот прогноз периода."
    },
    planets: {
      sun: "Солнце", moon: "Луна", mercury: "Меркурий", venus: "Венера", 
      mars: "Марс", jupiter: "Юпитер", saturn: "Сатурн", earth: "Земля"
    },
    zodiac: {
      Aries: "Овен",
      Taurus: "Телец",
      Gemini: "Близнецы",
      Cancer: "Рак",
      Leo: "Лев",
      Virgo: "Дева",
      Libra: "Весы",
      Scorpio: "Скорпион",
      Sagittarius: "Стрелец",
      Capricorn: "Козерог",
      Aquarius: "Водолей",
      Pisces: "Рыбы"
    },
    elements: {
      Fire: "Огонь",
      Water: "Вода",
      Air: "Воздух",
      Earth: "Земля"
    }
  },
  en: {
    loading: "Loading LUMIA",
    nav: {
      home: "Home",
      chart: "Natal Chart",
      synastry: "Synastry",
      oracle: "Ask the astrologer",
      settings: "Settings"
    },
    header: {
      back: "Back",
      wallet: "Lumi Wallet"
    },
    hook: {
      analyzing: "Building your personal foundation...",
      typing: "The astrologer is typing...",
      intro: "Hi, {name}. Let me show you what matters most for you.",
      done: "This is only 10% of your chart's potential. Free calculation complete.\n\nTo open your full chart, get daily forecasts, and read recurring life themes, activate subscription.",
      cta_button: "Learn more"
    },
    premium_preview: {
      title: "Premium",
      tagline: "More depth in your chart",
      subtitle: "Unlock a fuller reading: more context, more detail, more personal clarity.",
      feature_oracle: "Guidance with context",
      feature_oracle_desc: "Oracle and forecasts that continue your chart story instead of feeling separate.",
      feature_forecast: "Forecasts with context",
      feature_forecast_desc: "Day, week, and month through the lens of your natal chart.",
      feature_deep: "All full chart themes",
      feature_deep_desc: "Love, career, challenges, and life themes as clear interpretation paths.",
      feature_passport: "Full natal chart breakdown",
      feature_passport_desc: "More detail on core patterns, planetary dynamics, and inner tensions.",
      cta: PREMIUM_WEEK_CTA_EN
    },
    paywall: {
      title: "Premium",
      subtitle: "Your essential reading is already open. Premium adds love, career, growth, and a fuller interpretation of your chart.",
      feature1: "Full chart: Love, Career, Challenges, and Life themes",
      feature2: "A fuller breakdown built around your chart’s main patterns",
      feature3: "A richer compatibility reading in Synastry",
      feature4: "Oracle and forecasts as a personal continuation of your chart",
      cta: PREMIUM_PAYWALL_CTA_EN,
      footer: "7 days of full access"
    },
    dashboard: {
      welcome: "Welcome back,",
      identity_body: "Your chart is already built from your birth data. This is where your personal line begins: today, your chart, relationships, and important questions.",
      hero_label: "Today",
      hero_fallback_title: "Today is about holding on to what matters",
      hero_body: "The same daily reading as in Forecast: grounded in your chart and current influences — support, pressure, and what deserves attention first.",
      hero_cta: "Open today’s forecast",
      matters_label: "Daily cues",
      matters_title: "What matters today",
      matters_body: "Three short cues for the day: where an opening appears, where caution matters, and what deserves your focus.",
      chance: "Chance",
      risk: "Risk",
      focus: "Focus",
      fallback_chance: "An honest conversation may move things forward faster than careful avoidance.",
      fallback_risk: "Rushing or reacting too quickly can pull you away from what matters most.",
      fallback_focus: "One clear priority will steady the day more than ten parallel reactions.",
      natal_label: "Your foundation",
      natal_preview_label: "Natal chart",
      natal_preview_title: "The chart that begins self-understanding",
      natal_preview_cta: "Continue reading",
      natal_title: "Your natal chart",
      natal_body: "Character, closeness style, strengths, and repeating life patterns. This is your personal base reading, already saved in your profile.",
      natal_note: "Your base reading stays with you. Later you can unlock a fresh angle or recalculation through Lumi.",
      natal_cta: "Open chart",
      natal_point_character: "Character",
      natal_point_love: "Relationships",
      natal_point_strengths: "Strengths",
      natal_point_patterns: "Life patterns",
      next_label: "Next",
      next_title: "What you can open next",
      next_body: "The next steps help you understand relationships better and get a personal answer to an important question.",
      passport: "Personal portrait",
      element: "Element",
      ruler: "Ruler",
      menu_analysis: "Natal Chart",
      menu_forecast: "My Forecast",
      menu_synastry: "Compatibility",
      menu_oracle: "Ask the astrologer",
      synastry_label: "Relationships",
      moon_impact: "Moon Today",
      daily_transit: "Daily Transit",
      daily_advice: "Daily Advice",
      premium_badge: "PRO",
      solar_system_title: "Knowledge Base: Planets",
      get_premium: "Get Premium",
      evolution: "Soul Evolution",
      level: "Level",
      stats_intuition: "Intuition",
      stats_confidence: "Confidence",
      context_weather: "Weather outside",
      horoscope_today: "Today's guidance",
      forecast_date: "Forecast date",
      mood: "Mood",
      color: "Color",
      special_day: "Today’s forecast is open",
      detailed_forecast: "Open today →",
      horoscope_footer: "Daily guidance through your natal chart",
      chart_subtitle: "Personality, Fate, Karma & Forecasts",
      synastry_subtitle: "Free entry and full reading",
      synastry_hint: "Free gives the short entry. The full reading is available in Premium.",
      synastry_body: "Compare two charts for romance, friendship, family, or work. Readings open step by step; saved chart pairs stay cached.",
      synastry_cta: "Open compatibility",
      questions_label: "Personal question",
      questions_subtitle: "A clear answer to what matters",
      questions_body: "If a specific situation is weighing on you, the astrologer can gather it into a clear personal answer.",
      questions_support_free: "After the free question, the full answer is available in Premium.",
      questions_support_premium: "Ask what matters and get the full personal answer.",
      questions_cta: "Open questions",
      oracle_subtitle: "Ask the astrologer",
      loading_weather: "Loading weather...",
      set_city_hint: "Set city in settings to see weather",
      tap_settings: "Tap to open settings →",
      my_charts: "My Charts",
      my_charts_subtitle: "Manage charts & slots",
      charts_overview_title: "Saved charts",
      charts_overview_hint: "Saved charts can be reused in Synastry and future flows.",
      charts_overview_cta: "Open charts",
      lumia_subtitle: "Your path inward",
      studio_tab_natal: "Natal chart",
      studio_tab_union: "Union",
      studio_tab_horoscope: "Horoscope",
      chart_load_failed_title: "Chart didn’t load",
      chart_load_failed_body:
        "The network or server is taking too long. Refresh or open your natal chart to try again.",
      chart_load_retry: "Refresh page",
      chart_load_open_chart: "Open chart",
      studio_wallet_hint: "Lumi balance",
    },
    chart: {
      title: "Natal Chart",
      summary: "Your foundation",
      anchor_label: "Your foundation",
      anchor_title: "Your base personal reading is already ready",
      anchor_body: "This is not filler text. It is your personal foundation: character, strengths, relationship style, and repeating life patterns read through your chart.",
      anchor_persistent_note: "This foundation stays with you and does not refresh on its own. A new angle or recalculation is a separate Lumi action.",
      anchor_strengths_title: "Strengths",
      anchor_patterns_title: "Repeating patterns",
      anchor_loading: "Preparing your base personal reading...",
      core_title: "Core Chart",
      core_body: "Sun, Moon, and Rising create the first clear understanding: how you show up, feel, and meet the world.",
      chart_legend: "Sun shows your core and character, Moon your emotions and inner rhythm, Rising your first impression and behavior style.",
      living_label: "Living reading",
      living_title: "What is changing in you now",
      living_body: "This is no longer just a base description. It is the living reading of your chart: the theme of the period, where your strength is now, where you are more sensitive, and what matters in relationships, money, and goals.",
      living_loading: "Preparing the living reading of your chart...",
      living_error: "Could not open the living natal reading yet.",
      living_active_theme: "Theme of the period",
      living_strength: "Where your strength is now",
      living_vulnerability: "Where you are more vulnerable",
      living_relationships: "What is changing in relationships",
      living_money: "What matters for money and goals",
      living_guidance: "What to lean on now",
      living_premium_title: "Premium opens the living reading of your chart",
      living_premium_body: "Premium shows not just who you are, but what is being activated in you now: the theme of the period, shifts in relationships, money, and goals, and where your strength and vulnerability are showing up.",
      living_premium_note: "This is a different class of interpretation: more detail, sharper, and closer to your current reality.",
      living_premium_cta: "Open the living reading",
      my_charts_title: "My Charts",
      my_charts_body: "Your primary chart, saved profiles, and Synastry tools live in one place.",
      my_charts_cta: "Open charts",
      forecast_title: "Personal Forecast",
      forecast_day: "Today",
      forecast_week: "This Week",
      forecast_month: "This Month",
      free_teaser_title: "Personal portrait",
      refresh_intro_cta: "Refresh your foundation text for {cost} Lumi",
      refresh_intro_loading: "Preparing a new angle…",
      refresh_intro_error: "Could not refresh",
      refresh_intro_insufficient: "You need more Lumi to open a new angle"
    },
    charts: {
      title: "My Charts",
      slots: "Slots",
      slots_used: "charts",
      no_charts: "No saved charts yet.",
      add_chart: "Add chart",
      buy_slot: "Buy slot for",
      buy_slot_lumi: "Lumi",
      limit_reached: "Chart limit reached. Additional charts are available in Premium.",
      balance: "Balance",
      purchasing: "Purchasing...",
      loading: "Loading charts...",
      value_title: "Saved charts are reusable assets in Your Horoscope.",
      value_body: "Open them anytime, reuse them in Synastry, and stop re-entering partner birth data.",
      action_title: "Your chart space",
      action_body: "This is where your primary chart, saved profiles, and slots for future comparisons live.",
      primary_role: "Your base chart in Your Horoscope",
      saved_role: "Reusable chart for compatibility and comparisons",
      use_in_synastry: "Use in Synastry",
      open_chart: "Open",
      set_primary: "Set primary",
      delete: "Delete",
      primary_badge: "Primary",
      slots_full_title: "Your slots are full",
      slots_full_body: "Unlock Premium to save more charts.",
      premium_slots_cta: "Open Premium",
      slots_need_more_lumi: "You need more Lumi to unlock another slot.",
      enough_balance_hint: "You have enough balance to unlock another slot and save a new chart right away.",
      empty_title: "Start with your chart",
      empty_body: "When partner charts are saved here, they can be reused in Synastry without retyping the data.",
      single_chart_body: "One more saved chart unlocks faster Synastry comparisons.",
      open_wallet: "Open Lumi Wallet",
      add_form_title: "New chart",
      default_chart_name: "My Chart",
      field_name: "Name",
      field_birth_date: "Birth date",
      field_birth_time: "Birth time",
      field_birth_place: "Birth place",
      field_birth_place_placeholder: "Moscow, Russia",
      error_insufficient_lumi: "Insufficient Lumi",
      error_fill_required: "Fill date and birth place",
      error_no_free_slots: "No free slots are available right now",
      error_create_failed: "Failed to create chart",
      error_generic: "Error",
      error_delete_failed: "Delete failed",
      create: "Create",
      creating: "Creating...",
      cancel: "Cancel",
      saved_for_synastry_hint: "Your saved partner charts are ready to reuse in Synastry."
    },
    synastry: {
      title: "Synastry",
      hero_kicker: "Compatibility",
      headline: "Two charts — how you fit together",
      desc: "The short reading sets the overall tone. The full reading is available in Premium. Works for romance, friendship, family, and work — pick the bond type below.",
      partner_from_manual: "Enter manually",
      partner_from_charts: "Select from my charts",
      optional_more: "Optional (for more accurate analysis)",
      partner_name: "Partner Name",
      calc_btn: "Calculate Compatibility",
      score: "Compatibility",
      emotional: "Emotional Bond",
      intellectual: "Intellectual Bond",
      challenge: "Karmic Challenge",
      input_title: "Partner Details",
      brief_btn: "Short entry (free)",
      full_btn: "Full reading (Premium)",
      extended_hint: "The full relationship reading is available in Premium.",
      premium_required: "The full relationship reading is available in Premium.",
      extended_connection: "Connection",
      extended_tension: "Tension and meaning",
      extended_navigation: "How to navigate",
      extended_bond: "Bond context",
      add_full_btn: "Open full Premium reading",
      tips_label: "Tips",
      loading: "Reading star compatibility...",
      primary_title: "You",
      partner_title: "Partner",
      primary_hint: "Synastry always uses your current primary chart on your side.",
      selected_saved: "Saved chart",
      selected_manual: "Manual input",
      no_saved_title: "No partner charts saved yet",
      no_saved_body: "Save another chart in My Charts to compare again without re-entering partner details.",
      open_charts: "Open My Charts",
      buy_slot: "Buy slot",
      change_partner: "Change partner",
      compare_again: "Compare another chart",
      result_saved_badge: "From saved chart",
      result_manual_badge: "Manual input",
      saved_first_hint: "Saved charts are the fastest way to reopen Synastry later.",
      manual_hint: "Manual input is best for one-off comparisons.",
      mode_label: "Partner chart source",
      details_label: "Partner details",
      details_body: "Choose a saved chart or enter the details manually for a one-time comparison.",
      cta_label: "Choose the compatibility reading",
      partner_name_placeholder: "Enter name",
      birth_date_label: "Birth date",
      partner_sign_label: "Partner sign",
      birth_time_label: "Birth time",
      relationship_type_label: "Relationship type",
      birth_place_label: "Birth place",
      birth_place_placeholder: "City, country",
      relationship_romantic: "Romantic",
      relationship_friendship: "Friendship",
      relationship_family: "Family",
      relationship_work: "Work",
      selected_partner_title: "Selected partner",
      saved_list_title: "Saved charts",
      result_title: "Compatibility overview"
    },
    settings: {
      title: "Settings",
      profile: "Profile",
      language: "Language",
      theme: "Theme",
      theme_dark: "Midnight",
      theme_light: "Latte",
      edit: "Edit Profile",
      subscription: "Subscription",
      plan_pro: "Premium active",
      plan_basic: "Basic plan",
      plan_active: "Active",
      subscription_body: "Your Horoscope already opens your essentials. Premium adds fuller readings, richer synastry, and Oracle without noise.",
      restore: "Restore",
      switch_lang: "Русский",
      save: "Save Changes",
      admin: "Admin Panel",
      admin_body: "Internal access for user management, Lumi operations, and notifications.",
      wallet_title: "Lumi Wallet",
      wallet_body: "Balance, history, and Lumi top-up",
      charts_title: "My Charts",
      charts_body: "Manage natal charts",
      theme_body: "Choose a softer or more contrast-driven interface rhythm.",
      language_ru: "Russian",
      language_en: "English",
      language_body: "Language for the astrologer’s interface and generated texts.",
      weather_title: "Weather & Moon",
      weather_body: "Set a city for weather and Moon context",
      weather_city: "City",
      weather_placeholder: "e.g. Moscow or London",
      weather_helper: "Enter a city name from 2 to 64 characters.",
      weather_empty: "City not set",
      weather_ready: "Optional: weather and moon phase as ambient UI (not the core app experience)",
      weather_error: "Failed to save city. Please try again.",
      edit_inline: "Edit",
      cancel: "Cancel",
      saving: "Saving...",
      profile_name: "Name",
      profile_birth_place: "Birth place",
      profile_date_time: "Date & time"
    },
    oracle: {
      title: "Ask the astrologer",
      placeholder: "What matters most right now?",
      intro: "The astrologer answers through your chart and the real situation itself: relationships, decisions, fear, money, pressure, and direction.",
      hero_label: "Personal question",
      hero_title: "Ask about what actually matters",
      hero_body: "This is not a decorative chat. You can ask directly about what hurts, pulls at you, scares you, or needs a decision and get a personal answer through your chart.",
      state_free_label: "Starter question",
      state_free_title: "Your first question is open for free",
      state_free_body: "You already have one personal answer available at no cost. After that, the full answer is available in Premium.",
      state_need_premium_label: "Premium level",
      state_need_premium_title: "Continue in Premium",
      state_need_premium_body: "Full personal answers through your chart are available in Premium.",
      state_premium_label: "Premium level",
      state_premium_title: "You are asking on Premium level",
      state_premium_body: "You do not need to unlock each answer separately: the full level is already open.",
      state_open_premium: "Open Premium",
      state_open_wallet: "Open Premium",
      history_label: "Your questions",
      history_empty: "Your personal questions and the astrologer’s answers will appear here.",
      composer_label: "Your question",
      composer_body: "State the situation directly. The more honest the question, the sharper the answer will be.",
      send_free: "Get an answer",
      send_lumi: "Continue in Premium",
      send_premium: "Get the full answer",
      loading_history: "Loading your questions...",
      thinking: "The astrologer is preparing an answer...",
      empty_question: "Enter a question for the astrologer.",
      short_question: "Your question is too short. Add a little more detail.",
      long_question: "Your question is too long. Shorten it and try again.",
      history_error: "Could not load recent questions. You can still ask again.",
      send_error: "The astrologer could not answer right now. Please try again.",
      retry: "Retry",
      open_premium: "Open Premium"
    },
    horoscope: {
      title: "Your forecast for today",
      subtitle: "Every free day now includes both a daily horoscope and a daily natal card for today.",
      today_layer_label: "Daily reading",
      loading: "Preparing your day...",
      reading_title: "Daily horoscope",
      reading_body: "This is the short daily reading: the general tone, opening, risk, and main focus for today.",
      foundation_label: "Your foundation",
      foundation_body: "The forecast is read through your natal chart. It does not live separately from it — it stays grounded in your real personal foundation.",
      what_matters_title: "What matters today",
      what_matters_body: "Three short cues for the day: where an opening appears, where control matters, and what deserves your focus.",
      chance_title: "Chance",
      risk_title: "Risk",
      focus_title: "Focus",
      context_title: "Daily natal card",
      context_body: "This is the personal day reading: what is being activated in you today and in which moments or triggers of the day it is likely to show up more strongly.",
      context_note_title: "What this activates today",
      advice_title: "Three anchors for today",
      inline_horoscope_title: "Want to read the day more precisely?",
      inline_horoscope_body: "The free horoscope already shows the overall rhythm. The full day breaks that tone into morning, day, and evening so you can see where to act more precisely and where not to rush.",
      inline_natal_title: "You can read the personal day more precisely",
      inline_natal_body: "The daily natal card already shows what is being activated in you today. The full day shows how that plays out across situations, triggers, and decisions through the day.",
      dayparts_label: "Full day reading",
      dayparts_title: "Morning, day, and evening in the full reading",
      dayparts_body: "This is the same full daily reading opened in Premium: inner rhythm, concrete moments, contact, and decisions across the day.",
      dayparts_loading: "Preparing your day rhythm...",
      slot_morning: "Morning",
      slot_day: "Day",
      slot_evening: "Evening",
      daypart_focus_title: "Main focus",
      daypart_relationships_title: "Relationships",
      daypart_money_title: "Money and decisions",
      daypart_guidance_title: "How to move through it",
      premium_label: "Full day",
      bridge_label: "How this fits Your Horoscope",
      bridge_title: "Forecast shows the day. Natal shows your foundation.",
      bridge_body: "If you want to understand not just today's rhythm but steady patterns of character, closeness, strength, and repeating life themes, return to your natal chart.",
      open_chart: "Open natal chart",
      premium_title: "The full day is available in Premium",
      premium_body: "Free already gives you both a daily horoscope and a daily natal card. Premium opens the same reading in more detail: morning, daytime, and evening as separate moments, choices, and triggers.",
      premium_supporting_line: "Premium keeps the full day open every day.",
      error_insufficient_lumi: "Could not unlock the full day reading right now.",
      premium_cta: "Open Premium",
      empty_title: "Today’s forecast is not available yet",
      empty_body: "Today’s reading did not load, but your natal chart is still your personal anchor.",
      empty_cta: "Open natal",
      persist_notice: "Showing a fresh forecast, but it has not been saved yet.",
      stale_notice: "Showing the latest available forecast while a fresh daily reading is unavailable.",
      fallback_error: "Failed to load today’s forecast",
      weekly_label: "Weekly reading",
      weekly_title: "Your week through the chart",
      weekly_body: "A short orientation for the calendar week. Premium adds a full reading with theme, tensions, and focus for relationships and work.",
      monthly_label: "Monthly reading",
      monthly_title: "Your month through the chart",
      monthly_body: "A compact monthly focus. Premium adds a deep read on theme, relationships, and money.",
      period_loading: "Preparing week and month...",
      period_theme: "Theme",
      period_opportunities: "Openings",
      period_challenges: "Tensions",
      period_relationships: "Relationships",
      period_career: "Work and direction",
      period_money: "Money and practice",
      period_guidance: "Guidance",
      period_reading: "Reading",
      period_premium_hint_weekly: "Premium includes the full weekly forecast — a separate class of interpretation.",
      period_premium_hint_monthly: "Premium includes the full monthly forecast.",
      period_error: "Could not load this period forecast"
    },
    planets: {
      sun: "Sun", moon: "Moon", mercury: "Mercury", venus: "Venus", 
      mars: "Mars", jupiter: "Jupiter", saturn: "Saturn", earth: "Earth"
    },
    zodiac: {
      Aries: "Aries",
      Taurus: "Taurus",
      Gemini: "Gemini",
      Cancer: "Cancer",
      Leo: "Leo",
      Virgo: "Virgo",
      Libra: "Libra",
      Scorpio: "Scorpio",
      Sagittarius: "Sagittarius",
      Capricorn: "Capricorn",
      Aquarius: "Aquarius",
      Pisces: "Pisces"
    },
    elements: {
      Fire: "Fire",
      Water: "Water",
      Air: "Air",
      Earth: "Earth"
    }
  }
};

export const getText = (lang: Language, key: string) => {
   const keys = key.split('.');
   let current: any = TRANSLATIONS[lang];
   for (const k of keys) {
       if (current[k] === undefined) return key;
       current = current[k];
   }
   return current;
};

export const getZodiacSign = (lang: Language, sign: string): string => {
  const zodiacTranslations = TRANSLATIONS[lang].zodiac as Record<string, string>;
  if (!sign) return sign;
  // Ключи карты переводов — с заглавной (Aries). Вызовы приходят и строчными (gemini),
  // и с заглавной — нормализуем регистр, иначе знак показывается на английском.
  const normalized = sign.charAt(0).toUpperCase() + sign.slice(1).toLowerCase();
  return zodiacTranslations[normalized] || zodiacTranslations[sign] || sign;
};

export const getElement = (lang: Language, element: string): string => {
  const elementTranslations = TRANSLATIONS[lang].elements as Record<string, string>;
  return elementTranslations[element] || element;
};
