import { Language } from './types';
import { PREMIUM_WEEK_STARS } from './lib/premiumPricing';

export const APP_NAME = 'Твой Гороскоп';

const PREMIUM_WEEK_CTA_RU = `Открыть 1 неделю • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_PAYWALL_CTA_RU = `Открыть Premium • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_WEEK_CTA_EN = `Unlock 1 Week • ${PREMIUM_WEEK_STARS} Stars`;
const PREMIUM_PAYWALL_CTA_EN = `Unlock Premium • ${PREMIUM_WEEK_STARS} Stars`;

export const TRANSLATIONS = {
  ru: {
    loading: 'Загружаем Твой Гороскоп',
    nav: {
      home: 'Главная',
      chart: 'Натальная карта',
      synastry: 'Совместимость',
      settings: 'Настройки',
    },
    header: {
      back: 'Назад',
    },
    hook: {
      analyzing: 'Рассчитываем натальную карту…',
      typing: 'Готовим разбор…',
      intro: 'Привет, {name}. Сначала покажем основные выводы по твоей карте.',
      done: 'Базовый расчёт готов.\n\nPremium открывает подробные разборы карты, личные прогнозы и полную совместимость.',
      cta_button: 'Продолжить',
    },
    premium_preview: {
      title: 'Premium',
      tagline: 'Что откроется',
      subtitle: 'Все личные прогнозы, ответы на вопросы, подробные разборы карты и полная совместимость.',
      feature_daily: 'Полный личный гороскоп',
      feature_daily_desc: 'Готовый прогноз на сегодня с подробностями по нужным темам.',
      feature_forecast: 'Неделя и месяц',
      feature_forecast_desc: 'Полные личные прогнозы для каждого периода.',
      feature_deep: 'Подробные разборы карты',
      feature_deep_desc: 'Отношения, деньги, работа, конфликты и другие важные разделы.',
      feature_passport: 'Полная совместимость',
      feature_passport_desc: 'Сравнение двух натальных карт для любви, дружбы, семьи или работы.',
      cta: PREMIUM_WEEK_CTA_RU,
    },
    paywall: {
      title: 'Premium',
      subtitle: 'Открой все личные прогнозы, ответы на вопросы, подробные разборы карты и полную совместимость.',
      feature1: 'Сегодня, неделя и месяц',
      feature2: 'Подробные разборы натальной карты',
      feature3: 'Полная совместимость двух карт',
      feature4: 'Ответы на личные вопросы по выбранному периоду',
      cta: PREMIUM_PAYWALL_CTA_RU,
      footer: '7 дней доступа ко всем функциям Premium',
    },
    dashboard: {
      welcome: 'С возвращением,',
      identity_body: 'Натальная карта рассчитана по твоим данным рождения. Здесь доступны прогнозы, разбор карты и совместимость.',
      hero_label: 'Сегодня',
      hero_fallback_title: 'Прогноз на сегодня',
      hero_body: 'Главный вывод дня, возможный риск и конкретные действия по расчётам твоей натальной карты.',
      hero_cta: 'Открыть прогноз',
      matters_label: 'Коротко по делу',
      matters_title: 'Что важно сегодня',
      matters_body: 'Что может помочь, что может помешать и на чём лучше сосредоточиться.',
      chance: 'Что поможет',
      risk: 'Что помешает',
      focus: 'На чём сосредоточиться',
      fallback_chance: 'Прямой вопрос даст больше, чем попытка добиться ответа намёками.',
      fallback_risk: 'Решение на эмоциях может создать лишнюю проблему.',
      fallback_focus: 'Закончи одну конкретную задачу до того, как начинать новую.',
      natal_label: 'Натальная карта',
      natal_preview_label: 'Натальная карта',
      natal_preview_title: 'Разбор по данным рождения',
      natal_preview_cta: 'Открыть разбор',
      natal_title: 'Твоя натальная карта',
      natal_body: 'Характер, привычные реакции, отношения, деньги и работа — по дате, времени и месту рождения.',
      natal_note: 'Базовый разбор сохранён в профиле. Premium открывает дополнительные подробные разделы.',
      natal_cta: 'Открыть карту',
      natal_point_character: 'Характер и реакции',
      natal_point_love: 'Отношения',
      natal_point_strengths: 'Сильные стороны',
      natal_point_patterns: 'Слабые места',
      next_label: 'Дальше',
      next_title: 'Что открыть дальше',
      next_body: 'Перейди к личному прогнозу, совместимости или сохранённым картам.',
      passport: 'Краткий разбор',
      element: 'Стихия',
      ruler: 'Управитель',
      menu_analysis: 'Натальная карта',
      menu_forecast: 'Личный гороскоп',
      menu_synastry: 'Совместимость',
      synastry_label: 'Совместимость',
      moon_impact: 'Луна сегодня',
      daily_transit: 'Расчёт дня',
      daily_advice: 'Что сделать',
      premium_badge: 'PRO',
      solar_system_title: 'Планеты',
      get_premium: 'Открыть Premium',
      evolution: 'Разбор карты',
      level: 'Уровень',
      stats_intuition: 'Интуиция',
      stats_confidence: 'Уверенность',
      horoscope_today: 'Прогноз на сегодня',
      forecast_date: 'Дата прогноза',
      mood: 'Настроение',
      color: 'Цвет',
      special_day: 'Прогноз на сегодня готов',
      detailed_forecast: 'Открыть прогноз →',
      horoscope_footer: 'Личный прогноз по натальной карте',
      chart_subtitle: 'Характер, отношения, работа и деньги',
      synastry_subtitle: 'Короткий и полный разбор',
      synastry_hint: 'Короткий разбор доступен бесплатно. Полный — в Premium.',
      synastry_body: 'Сравни две карты для любви, дружбы, семьи или работы. Выбери тип отношений и человека.',
      synastry_cta: 'Открыть совместимость',
      tap_settings: 'Открыть настройки →',
      my_charts: 'Мои карты',
      my_charts_subtitle: 'Сохранённые карты и свободные места',
      charts_overview_title: 'Сохранённые карты',
      charts_overview_hint: 'Используй сохранённые карты для повторного чтения и совместимости без нового ввода данных.',
      charts_overview_cta: 'Открыть карты',
      lumia_subtitle: 'Натальная карта, прогнозы и совместимость',
      studio_tab_natal: 'Натальная карта',
      studio_tab_union: 'Совместимость',
      studio_tab_horoscope: 'Гороскоп',
      chart_load_failed_title: 'Карта не загрузилась',
      chart_load_failed_body: 'Проверь интернет и попробуй открыть карту ещё раз.',
      chart_load_retry: 'Повторить',
      chart_load_open_chart: 'Открыть карту',
    },
    chart: {
      title: 'Твоя натальная карта',
      summary: 'Краткий разбор',
      anchor_label: 'Базовый разбор',
      anchor_title: 'Разбор натальной карты готов',
      anchor_body: 'Характер, привычные реакции, отношения, деньги и работа — по твоим данным рождения.',
      anchor_persistent_note: 'Разбор сохранён в профиле. Premium открывает дополнительные подробные разделы.',
      anchor_strengths_title: 'Сильные стороны',
      anchor_patterns_title: 'Слабые места',
      anchor_loading: 'Готовим базовый разбор…',
      core_title: 'Солнце, Луна и Асцендент',
      core_body: 'Эти три точки помогают описать решения, внутреннюю реакцию и первое впечатление.',
      chart_legend: 'Солнце связано с решениями и характером, Луна — с быстрой внутренней реакцией, Асцендент — с первым впечатлением и поведением в новой обстановке.',
      living_label: 'Подробный разбор',
      living_title: 'Отдельные разделы по важным темам',
      living_body: 'Отношения, деньги, работа, конфликты, нагрузка и другие разделы по рассчитанной карте.',
      living_loading: 'Готовим подробный разбор…',
      living_error: 'Подробный разбор не загрузился. Попробуй ещё раз позже.',
      living_active_theme: 'Главный вывод',
      living_strength: 'Что получается лучше',
      living_vulnerability: 'Где начинаются проблемы',
      living_relationships: 'Отношения',
      living_money: 'Деньги и работа',
      living_guidance: 'Практический вывод',
      living_premium_title: 'Подробные разделы доступны в Premium',
      living_premium_body: 'Открой отдельные разборы отношений, денег, работы, конфликтов, нагрузки и других тем.',
      living_premium_note: 'Все разделы входят в один доступ Premium.',
      living_premium_cta: 'Открыть подробные разделы',
      my_charts_title: 'Мои карты',
      my_charts_body: 'Основная карта и сохранённые карты других людей.',
      my_charts_cta: 'Открыть карты',
      forecast_title: 'Личный гороскоп',
      forecast_day: 'Сегодня',
      forecast_week: 'Неделя',
      forecast_month: 'Месяц',
      free_teaser_title: 'Краткий разбор',
      refresh_intro_cta: 'Открыть Premium',
      refresh_intro_loading: 'Готовим новый текст…',
      refresh_intro_error: 'Не получилось обновить',
      refresh_intro_insufficient: 'Для нового подробного разбора нужен Premium',
    },
    charts: {
      title: 'Мои карты',
      slots: 'Мест',
      slots_used: 'карт',
      no_charts: 'Сохранённых карт пока нет.',
      add_chart: 'Добавить карту',
      buy_slot: 'Купить место за',
      limit_reached: 'Свободных мест нет. Дополнительные карты доступны в Premium.',
      balance: 'Баланс',
      purchasing: 'Покупка…',
      loading: 'Загружаем карты…',
      value_title: 'Сохранённые карты',
      value_body: 'Открывай их повторно и используй для совместимости без нового ввода данных.',
      action_title: 'Мои карты',
      action_body: 'Основная карта, карты близких и свободные места для новых людей.',
      primary_role: 'Твоя основная карта',
      saved_role: 'Карта для чтения и совместимости',
      use_in_synastry: 'Сравнить карты',
      open_chart: 'Открыть',
      set_primary: 'Сделать основной',
      delete: 'Удалить',
      primary_badge: 'Основная',
      slots_full_title: 'Свободных мест нет',
      slots_full_body: 'Premium позволяет сохранять больше карт.',
      premium_slots_cta: 'Открыть Premium',
      slots_need_more_lumi: 'Для новой карты нужен Premium.',
      enough_balance_hint: 'Можно открыть ещё одно место и сохранить новую карту.',
      empty_title: 'Добавь первую карту',
      empty_body: 'Сохранённую карту можно читать и использовать для совместимости.',
      single_chart_body: 'Добавь ещё одного человека, чтобы быстро сравнивать карты.',
      add_form_title: 'Новая карта',
      default_chart_name: 'Моя карта',
      field_name: 'Имя',
      field_birth_date: 'Дата рождения',
      field_birth_time: 'Время рождения',
      field_birth_place: 'Место рождения',
      field_birth_place_placeholder: 'Москва, Россия',
      error_insufficient_lumi: 'Не получилось открыть новое место.',
      error_fill_required: 'Укажи дату и место рождения.',
      error_no_free_slots: 'Свободных мест нет.',
      error_create_failed: 'Не получилось добавить карту.',
      error_generic: 'Что-то пошло не так.',
      error_delete_failed: 'Не получилось удалить карту.',
      create: 'Создать',
      creating: 'Создаём…',
      cancel: 'Отмена',
      saved_for_synastry_hint: 'Сохранённую карту можно использовать для совместимости без повторного ввода данных.',
    },
    synastry: {
      title: 'Совместимость по картам',
      hero_kicker: 'Совместимость',
      headline: 'Сравни две натальные карты',
      desc: 'Посмотри, что помогает договориться, где чаще возникают проблемы и как каждый реагирует на конфликт. Подходит для любви, дружбы, семьи и работы.',
      partner_from_manual: 'Ввести данные',
      partner_from_charts: 'Выбрать из моих карт',
      optional_more: 'Дополнительно',
      partner_name: 'Имя человека',
      calc_btn: 'Рассчитать совместимость',
      score: 'Совместимость',
      emotional: 'Чувства и близость',
      intellectual: 'Разговоры и решения',
      challenge: 'Где начинаются проблемы',
      input_title: 'Карта другого человека',
      brief_btn: 'Короткий разбор бесплатно',
      full_btn: 'Полный разбор в Premium',
      extended_hint: 'Полный разбор двух карт доступен в Premium.',
      premium_required: 'Для полного разбора нужен Premium.',
      extended_connection: 'Что вас сближает',
      extended_tension: 'Где возникает напряжение',
      extended_navigation: 'Как договориться',
      extended_bond: 'Тип отношений',
      add_full_btn: 'Открыть полный разбор',
      tips_label: 'Что поможет',
      loading: 'Сравниваем две карты…',
      primary_title: 'Твоя карта',
      partner_title: 'Другой человек',
      primary_hint: 'Для сравнения используется твоя текущая основная карта.',
      selected_saved: 'Сохранённая карта',
      selected_manual: 'Данные введены вручную',
      no_saved_title: 'Других карт пока нет',
      no_saved_body: 'Добавь человека в «Мои карты», чтобы не вводить его данные при каждом сравнении.',
      open_charts: 'Открыть карты',
      buy_slot: 'Открыть новое место',
      change_partner: 'Выбрать другого человека',
      compare_again: 'Сравнить другую карту',
      result_saved_badge: 'Сохранённая карта',
      result_manual_badge: 'Ручной ввод',
      saved_first_hint: 'Сохранённую карту можно открыть повторно без нового ввода данных.',
      manual_hint: 'Ручной ввод подходит для одного сравнения.',
      mode_label: 'Откуда взять данные',
      details_label: 'Данные другого человека',
      details_body: 'Выбери сохранённую карту или введи данные вручную.',
      cta_label: 'Выбери вид разбора',
      partner_name_placeholder: 'Введите имя',
      birth_date_label: 'Дата рождения',
      partner_sign_label: 'Знак зодиака',
      birth_time_label: 'Время рождения',
      relationship_type_label: 'Тип отношений',
      birth_place_label: 'Место рождения',
      birth_place_placeholder: 'Город, страна',
      relationship_romantic: 'Любовь',
      relationship_friendship: 'Дружба',
      relationship_family: 'Семья',
      relationship_work: 'Работа',
      selected_partner_title: 'Выбранный человек',
      saved_list_title: 'Сохранённые карты',
      result_title: 'Разбор совместимости',
    },
    settings: {
      title: 'Настройки',
      profile: 'Профиль',
      language: 'Язык',
      theme: 'Оформление',
      theme_dark: 'Тёмное',
      theme_light: 'Светлое',
      edit: 'Редактировать',
      subscription: 'Подписка',
      plan_pro: 'Premium активен',
      plan_basic: 'Бесплатный доступ',
      plan_active: 'Активен',
      subscription_body: 'Premium открывает все личные прогнозы, вопросы, подробные разборы и полную совместимость.',
      restore: 'Восстановить покупку',
      switch_lang: 'English',
      save: 'Сохранить',
      admin: 'Админ-панель',
      admin_body: 'Управление пользователями, контентом и уведомлениями.',
      charts_title: 'Мои карты',
      charts_body: 'Основная и сохранённые карты',
      theme_body: 'Выбери светлое или тёмное оформление.',
      language_ru: 'Русский',
      language_en: 'English',
      language_body: 'Язык интерфейса и текстов приложения.',
      edit_inline: 'Изменить',
      cancel: 'Отмена',
      saving: 'Сохраняем…',
      profile_name: 'Имя',
      profile_birth_place: 'Место рождения',
      profile_date_time: 'Дата и время рождения',
    },
    horoscope: {
      title: 'Прогноз на сегодня',
      subtitle: 'Короткий готовый прогноз и подробности по темам, которые тебе нужны.',
      today_layer_label: 'Личный прогноз',
      loading: 'Готовим прогноз…',
      reading_title: 'Главное на сегодня',
      reading_body: 'Что сейчас происходит, что даст результат и где есть риск.',
      foundation_label: 'Как рассчитан прогноз',
      foundation_body: 'Для личного прогноза используются твоя натальная карта и положение планет на выбранную дату.',
      what_matters_title: 'Коротко по делу',
      what_matters_body: 'Что может помочь, что может помешать и на чём лучше сосредоточиться.',
      chance_title: 'Что поможет',
      risk_title: 'Что помешает',
      focus_title: 'На чём сосредоточиться',
      context_title: 'Подробный разбор',
      context_body: 'Ниже — объяснение по расчётам выбранной даты без обещаний и выдуманных событий.',
      context_note_title: 'Почему такой вывод',
      advice_title: 'Что сделать',
      inline_horoscope_title: 'Разобрать день подробнее',
      inline_horoscope_body: 'Открой утро, день и вечер отдельно, если нужен более точный план на сегодня.',
      inline_natal_title: 'Посмотреть расчёт подробнее',
      inline_natal_body: 'Полный прогноз показывает, в каких ситуациях дня вывод будет заметен сильнее всего.',
      dayparts_label: 'Подробный прогноз',
      dayparts_title: 'Утро, день и вечер',
      dayparts_body: 'Что лучше поставить на каждый отрезок дня, где есть риск и какие решения требуют проверки.',
      dayparts_loading: 'Готовим подробности дня…',
      slot_morning: 'Утро',
      slot_day: 'День',
      slot_evening: 'Вечер',
      daypart_focus_title: 'Главный вопрос',
      daypart_relationships_title: 'Отношения',
      daypart_money_title: 'Работа и деньги',
      daypart_guidance_title: 'Что сделать',
      premium_label: 'Полный прогноз',
      premium_title: 'Полный прогноз дня доступен в Premium',
      premium_body: 'Открой подробности по утру, дню и вечеру, все вопросы и дополнительные разделы.',
      premium_supporting_line: 'Все функции входят в один доступ Premium.',
      error_insufficient_lumi: 'Не получилось открыть полный прогноз.',
      bridge_label: 'Другой раздел',
      bridge_title: 'Открыть натальную карту',
      bridge_body: 'В натальной карте собран постоянный разбор характера, реакций, отношений, денег и работы.',
      open_chart: 'Открыть карту',
      premium_cta: 'Открыть Premium',
      empty_title: 'Прогноз не загрузился',
      empty_body: 'Попробуй открыть прогноз позже. Мы не будем подменять личный расчёт общим текстом.',
      empty_cta: 'Открыть карту',
      persist_notice: 'Показываем новый прогноз, но он ещё не сохранён.',
      stale_notice: 'Показываем последний сохранённый прогноз, пока новый не загрузился.',
      fallback_error: 'Не получилось загрузить прогноз.',
      weekly_label: 'Прогноз на неделю',
      weekly_title: 'Твоя неделя',
      weekly_body: 'Главный вопрос недели, важные дни, возможный риск и конкретные действия.',
      monthly_label: 'Прогноз на месяц',
      monthly_title: 'Твой месяц',
      monthly_body: 'Главный сюжет месяца, важные периоды, отношения, работа и деньги.',
      period_loading: 'Готовим прогнозы…',
      period_theme: 'Главный вопрос',
      period_opportunities: 'Что поможет',
      period_challenges: 'Что помешает',
      period_relationships: 'Отношения',
      period_career: 'Работа',
      period_money: 'Деньги',
      period_guidance: 'Что сделать',
      period_reading: 'Подробный разбор',
      period_premium_hint_weekly: 'Полный прогноз на неделю доступен в Premium.',
      period_premium_hint_monthly: 'Полный прогноз на месяц доступен в Premium.',
      period_error: 'Не получилось загрузить прогноз на этот период.',
    },
    planets: {
      sun: 'Солнце',
      moon: 'Луна',
      mercury: 'Меркурий',
      venus: 'Венера',
      mars: 'Марс',
      jupiter: 'Юпитер',
      saturn: 'Сатурн',
      earth: 'Земля',
    },
    zodiac: {
      Aries: 'Овен',
      Taurus: 'Телец',
      Gemini: 'Близнецы',
      Cancer: 'Рак',
      Leo: 'Лев',
      Virgo: 'Дева',
      Libra: 'Весы',
      Scorpio: 'Скорпион',
      Sagittarius: 'Стрелец',
      Capricorn: 'Козерог',
      Aquarius: 'Водолей',
      Pisces: 'Рыбы',
    },
    elements: {
      Fire: 'Огонь',
      Water: 'Вода',
      Air: 'Воздух',
      Earth: 'Земля',
    },
  },
  en: {
    loading: 'Loading Your Horoscope',
    nav: {
      home: 'Home',
      chart: 'Natal Chart',
      synastry: 'Compatibility',
      settings: 'Settings',
    },
    header: {
      back: 'Back',
    },
    hook: {
      analyzing: 'Calculating your natal chart…',
      typing: 'Preparing the reading…',
      intro: 'Hi, {name}. We will start with the main conclusions from your chart.',
      done: 'The basic calculation is ready.\n\nPremium unlocks detailed natal readings, personal forecasts, and full compatibility.',
      cta_button: 'Continue',
    },
    premium_preview: {
      title: 'Premium',
      tagline: 'What you get',
      subtitle: 'All personal forecasts, question answers, detailed natal readings, and full compatibility.',
      feature_daily: 'Full personal forecast',
      feature_daily_desc: 'A ready-to-read forecast for today with details on the subjects you need.',
      feature_forecast: 'Week and month',
      feature_forecast_desc: 'Full personal forecasts for every period.',
      feature_deep: 'Detailed natal readings',
      feature_deep_desc: 'Relationships, money, work, conflict, and other important subjects.',
      feature_passport: 'Full compatibility',
      feature_passport_desc: 'Compare two natal charts for romance, friendship, family, or work.',
      cta: PREMIUM_WEEK_CTA_EN,
    },
    paywall: {
      title: 'Premium',
      subtitle: 'Unlock all personal forecasts, question answers, detailed natal readings, and full compatibility.',
      feature1: 'Today, week, and month',
      feature2: 'Detailed natal chart readings',
      feature3: 'Full two-chart compatibility',
      feature4: 'Answers to personal questions for the selected period',
      cta: PREMIUM_PAYWALL_CTA_EN,
      footer: '7 days of access to every Premium feature',
    },
    dashboard: {
      welcome: 'Welcome back,',
      identity_body: 'Your natal chart is calculated from your birth details. Forecasts, the chart reading, and compatibility are available here.',
      hero_label: 'Today',
      hero_fallback_title: 'Today’s forecast',
      hero_body: 'The main conclusion, a possible risk, and concrete actions based on your natal chart calculation.',
      hero_cta: 'Open forecast',
      matters_label: 'The practical part',
      matters_title: 'What matters today',
      matters_body: 'What may help, what may get in the way, and where to focus.',
      chance: 'What may help',
      risk: 'What may get in the way',
      focus: 'Where to focus',
      fallback_chance: 'A direct question will work better than trying to get an answer through hints.',
      fallback_risk: 'An emotional decision may create an avoidable problem.',
      fallback_focus: 'Finish one specific task before starting another.',
      natal_label: 'Natal chart',
      natal_preview_label: 'Natal chart',
      natal_preview_title: 'A reading based on your birth details',
      natal_preview_cta: 'Open reading',
      natal_title: 'Your natal chart',
      natal_body: 'Character, usual reactions, relationships, money, and work based on your birth date, time, and place.',
      natal_note: 'The basic reading is saved in your profile. Premium unlocks additional detailed sections.',
      natal_cta: 'Open chart',
      natal_point_character: 'Character and reactions',
      natal_point_love: 'Relationships',
      natal_point_strengths: 'Strengths',
      natal_point_patterns: 'Weak points',
      next_label: 'Next',
      next_title: 'What to open next',
      next_body: 'Continue to your personal forecast, compatibility, or saved charts.',
      passport: 'Short reading',
      element: 'Element',
      ruler: 'Ruler',
      menu_analysis: 'Natal Chart',
      menu_forecast: 'Personal Forecast',
      menu_synastry: 'Compatibility',
      synastry_label: 'Compatibility',
      moon_impact: 'Moon today',
      daily_transit: 'Daily calculation',
      daily_advice: 'What to do',
      premium_badge: 'PRO',
      solar_system_title: 'Planets',
      get_premium: 'Open Premium',
      evolution: 'Chart reading',
      level: 'Level',
      stats_intuition: 'Intuition',
      stats_confidence: 'Confidence',
      horoscope_today: 'Today’s forecast',
      forecast_date: 'Forecast date',
      mood: 'Mood',
      color: 'Color',
      special_day: 'Today’s forecast is ready',
      detailed_forecast: 'Open forecast →',
      horoscope_footer: 'A personal forecast based on your natal chart',
      chart_subtitle: 'Character, relationships, work, and money',
      synastry_subtitle: 'Short and full reading',
      synastry_hint: 'The short reading is free. The full reading is available in Premium.',
      synastry_body: 'Compare two charts for romance, friendship, family, or work. Select the relationship type and the other person.',
      synastry_cta: 'Open compatibility',
      tap_settings: 'Open settings →',
      my_charts: 'My Charts',
      my_charts_subtitle: 'Saved charts and available slots',
      charts_overview_title: 'Saved charts',
      charts_overview_hint: 'Reuse saved charts for readings and compatibility without entering the details again.',
      charts_overview_cta: 'Open charts',
      lumia_subtitle: 'Natal chart, forecasts, and compatibility',
      studio_tab_natal: 'Natal chart',
      studio_tab_union: 'Compatibility',
      studio_tab_horoscope: 'Horoscope',
      chart_load_failed_title: 'Chart did not load',
      chart_load_failed_body: 'Check your connection and try opening the chart again.',
      chart_load_retry: 'Try again',
      chart_load_open_chart: 'Open chart',
    },
    chart: {
      title: 'Your natal chart',
      summary: 'Short reading',
      anchor_label: 'Basic reading',
      anchor_title: 'Your natal chart reading is ready',
      anchor_body: 'Character, usual reactions, relationships, money, and work based on your birth details.',
      anchor_persistent_note: 'The reading is saved in your profile. Premium unlocks additional detailed sections.',
      anchor_strengths_title: 'Strengths',
      anchor_patterns_title: 'Weak points',
      anchor_loading: 'Preparing the basic reading…',
      core_title: 'Sun, Moon, and Rising',
      core_body: 'These three points help describe decisions, immediate reactions, and first impressions.',
      chart_legend: 'Sun is linked to decisions and character, Moon to immediate reactions, and Rising to first impressions and behaviour in unfamiliar settings.',
      living_label: 'Detailed reading',
      living_title: 'Separate sections for important subjects',
      living_body: 'Relationships, money, work, conflict, workload, and other subjects based on the calculated chart.',
      living_loading: 'Preparing the detailed reading…',
      living_error: 'The detailed reading did not load. Try again later.',
      living_active_theme: 'Main conclusion',
      living_strength: 'What works well',
      living_vulnerability: 'Where problems start',
      living_relationships: 'Relationships',
      living_money: 'Money and work',
      living_guidance: 'Practical conclusion',
      living_premium_title: 'Detailed sections are available in Premium',
      living_premium_body: 'Unlock separate readings for relationships, money, work, conflict, workload, and other subjects.',
      living_premium_note: 'Every section is included in one Premium subscription.',
      living_premium_cta: 'Open detailed sections',
      my_charts_title: 'My Charts',
      my_charts_body: 'Your primary chart and saved charts for other people.',
      my_charts_cta: 'Open charts',
      forecast_title: 'Personal Forecast',
      forecast_day: 'Today',
      forecast_week: 'Week',
      forecast_month: 'Month',
      free_teaser_title: 'Short reading',
      refresh_intro_cta: 'Open Premium',
      refresh_intro_loading: 'Preparing new copy…',
      refresh_intro_error: 'Could not refresh',
      refresh_intro_insufficient: 'Premium is required for another detailed reading',
    },
    charts: {
      title: 'My Charts',
      slots: 'Slots',
      slots_used: 'charts',
      no_charts: 'No saved charts yet.',
      add_chart: 'Add chart',
      buy_slot: 'Buy slot for',
      limit_reached: 'No slots are available. Additional charts are included in Premium.',
      balance: 'Balance',
      purchasing: 'Purchasing…',
      loading: 'Loading charts…',
      value_title: 'Saved charts',
      value_body: 'Open them again and use them for compatibility without entering the details again.',
      action_title: 'My Charts',
      action_body: 'Your primary chart, charts for people you know, and available slots.',
      primary_role: 'Your primary chart',
      saved_role: 'Chart for readings and compatibility',
      use_in_synastry: 'Compare charts',
      open_chart: 'Open',
      set_primary: 'Set primary',
      delete: 'Delete',
      primary_badge: 'Primary',
      slots_full_title: 'No slots available',
      slots_full_body: 'Premium lets you save more charts.',
      premium_slots_cta: 'Open Premium',
      slots_need_more_lumi: 'Premium is required for another chart.',
      enough_balance_hint: 'You can unlock another slot and save a new chart.',
      empty_title: 'Add the first chart',
      empty_body: 'A saved chart can be read and used for compatibility.',
      single_chart_body: 'Add another person to compare charts quickly.',
      add_form_title: 'New chart',
      default_chart_name: 'My Chart',
      field_name: 'Name',
      field_birth_date: 'Birth date',
      field_birth_time: 'Birth time',
      field_birth_place: 'Birth place',
      field_birth_place_placeholder: 'Moscow, Russia',
      error_insufficient_lumi: 'Could not unlock another slot.',
      error_fill_required: 'Enter the birth date and place.',
      error_no_free_slots: 'No slots are available.',
      error_create_failed: 'Could not add the chart.',
      error_generic: 'Something went wrong.',
      error_delete_failed: 'Could not delete the chart.',
      create: 'Create',
      creating: 'Creating…',
      cancel: 'Cancel',
      saved_for_synastry_hint: 'A saved chart can be used for compatibility without entering the details again.',
    },
    synastry: {
      title: 'Chart Compatibility',
      hero_kicker: 'Compatibility',
      headline: 'Compare two natal charts',
      desc: 'See what helps you agree, where problems are more likely to start, and how each person reacts to conflict. Works for romance, friendship, family, and work.',
      partner_from_manual: 'Enter details',
      partner_from_charts: 'Select from My Charts',
      optional_more: 'Optional',
      partner_name: 'Person’s name',
      calc_btn: 'Calculate compatibility',
      score: 'Compatibility',
      emotional: 'Feelings and closeness',
      intellectual: 'Conversation and decisions',
      challenge: 'Where problems start',
      input_title: 'The other person’s chart',
      brief_btn: 'Short reading for free',
      full_btn: 'Full reading in Premium',
      extended_hint: 'The full two-chart reading is available in Premium.',
      premium_required: 'Premium is required for the full reading.',
      extended_connection: 'What brings you together',
      extended_tension: 'Where tension starts',
      extended_navigation: 'How to agree',
      extended_bond: 'Relationship type',
      add_full_btn: 'Open full reading',
      tips_label: 'What may help',
      loading: 'Comparing two charts…',
      primary_title: 'Your chart',
      partner_title: 'The other person',
      primary_hint: 'Your current primary chart is used for the comparison.',
      selected_saved: 'Saved chart',
      selected_manual: 'Details entered manually',
      no_saved_title: 'No other charts yet',
      no_saved_body: 'Add someone in My Charts so you do not need to enter their details for every comparison.',
      open_charts: 'Open charts',
      buy_slot: 'Unlock another slot',
      change_partner: 'Select another person',
      compare_again: 'Compare another chart',
      result_saved_badge: 'Saved chart',
      result_manual_badge: 'Manual input',
      saved_first_hint: 'A saved chart can be reopened without entering the details again.',
      manual_hint: 'Manual input is suitable for a one-time comparison.',
      mode_label: 'Where to get the details',
      details_label: 'The other person’s details',
      details_body: 'Select a saved chart or enter the details manually.',
      cta_label: 'Choose the reading',
      partner_name_placeholder: 'Enter name',
      birth_date_label: 'Birth date',
      partner_sign_label: 'Zodiac sign',
      birth_time_label: 'Birth time',
      relationship_type_label: 'Relationship type',
      birth_place_label: 'Birth place',
      birth_place_placeholder: 'City, country',
      relationship_romantic: 'Romance',
      relationship_friendship: 'Friendship',
      relationship_family: 'Family',
      relationship_work: 'Work',
      selected_partner_title: 'Selected person',
      saved_list_title: 'Saved charts',
      result_title: 'Compatibility reading',
    },
    settings: {
      title: 'Settings',
      profile: 'Profile',
      language: 'Language',
      theme: 'Appearance',
      theme_dark: 'Dark',
      theme_light: 'Light',
      edit: 'Edit',
      subscription: 'Subscription',
      plan_pro: 'Premium active',
      plan_basic: 'Free access',
      plan_active: 'Active',
      subscription_body: 'Premium unlocks all personal forecasts, questions, detailed readings, and full compatibility.',
      restore: 'Restore purchase',
      switch_lang: 'Русский',
      save: 'Save',
      admin: 'Admin Panel',
      admin_body: 'Manage users, content, and notifications.',
      charts_title: 'My Charts',
      charts_body: 'Primary and saved charts',
      theme_body: 'Choose a light or dark appearance.',
      language_ru: 'Russian',
      language_en: 'English',
      language_body: 'Language for the interface and generated text.',
      edit_inline: 'Edit',
      cancel: 'Cancel',
      saving: 'Saving…',
      profile_name: 'Name',
      profile_birth_place: 'Birth place',
      profile_date_time: 'Birth date and time',
    },
    horoscope: {
      title: 'Today’s forecast',
      subtitle: 'A short ready-to-read forecast and details on the subjects you need.',
      today_layer_label: 'Personal forecast',
      loading: 'Preparing forecast…',
      reading_title: 'The main point today',
      reading_body: 'What is happening, what may work, and where the risk is.',
      foundation_label: 'How the forecast is calculated',
      foundation_body: 'A personal forecast uses your natal chart and the planetary positions for the selected date.',
      what_matters_title: 'The practical part',
      what_matters_body: 'What may help, what may get in the way, and where to focus.',
      chance_title: 'What may help',
      risk_title: 'What may get in the way',
      focus_title: 'Where to focus',
      context_title: 'Full explanation',
      context_body: 'The explanation below uses the calculation for the selected date without guarantees or invented events.',
      context_note_title: 'Why this conclusion',
      advice_title: 'What to do',
      inline_horoscope_title: 'Read the day in more detail',
      inline_horoscope_body: 'Open morning, daytime, and evening separately when you need a more precise plan for today.',
      inline_natal_title: 'See more of the calculation',
      inline_natal_body: 'The full forecast shows which situations are most likely to reflect the conclusion.',
      dayparts_label: 'Detailed forecast',
      dayparts_title: 'Morning, daytime, and evening',
      dayparts_body: 'What to schedule in each part of the day, where the risk is, and which decisions need checking.',
      dayparts_loading: 'Preparing daily details…',
      slot_morning: 'Morning',
      slot_day: 'Day',
      slot_evening: 'Evening',
      daypart_focus_title: 'Main question',
      daypart_relationships_title: 'Relationships',
      daypart_money_title: 'Work and money',
      daypart_guidance_title: 'What to do',
      premium_label: 'Full forecast',
      premium_title: 'The full daily forecast is available in Premium',
      premium_body: 'Unlock morning, daytime, and evening details, every question, and additional sections.',
      premium_supporting_line: 'Every feature is included in one Premium subscription.',
      error_insufficient_lumi: 'Could not open the full forecast.',
      bridge_label: 'Another section',
      bridge_title: 'Open the natal chart',
      bridge_body: 'The natal chart contains the long-term reading of character, reactions, relationships, money, and work.',
      open_chart: 'Open chart',
      premium_cta: 'Open Premium',
      empty_title: 'Forecast did not load',
      empty_body: 'Try again later. We will not replace a personal calculation with generic copy.',
      empty_cta: 'Open chart',
      persist_notice: 'Showing a new forecast, but it has not been saved yet.',
      stale_notice: 'Showing the latest saved forecast while the new one is unavailable.',
      fallback_error: 'Could not load the forecast.',
      weekly_label: 'Weekly forecast',
      weekly_title: 'Your week',
      weekly_body: 'The main question, important days, a possible risk, and concrete actions.',
      monthly_label: 'Monthly forecast',
      monthly_title: 'Your month',
      monthly_body: 'The main story of the month, important periods, relationships, work, and money.',
      period_loading: 'Preparing forecasts…',
      period_theme: 'Main question',
      period_opportunities: 'What may help',
      period_challenges: 'What may get in the way',
      period_relationships: 'Relationships',
      period_career: 'Work',
      period_money: 'Money',
      period_guidance: 'What to do',
      period_reading: 'Detailed reading',
      period_premium_hint_weekly: 'The full weekly forecast is available in Premium.',
      period_premium_hint_monthly: 'The full monthly forecast is available in Premium.',
      period_error: 'Could not load the forecast for this period.',
    },
    planets: {
      sun: 'Sun',
      moon: 'Moon',
      mercury: 'Mercury',
      venus: 'Venus',
      mars: 'Mars',
      jupiter: 'Jupiter',
      saturn: 'Saturn',
      earth: 'Earth',
    },
    zodiac: {
      Aries: 'Aries',
      Taurus: 'Taurus',
      Gemini: 'Gemini',
      Cancer: 'Cancer',
      Leo: 'Leo',
      Virgo: 'Virgo',
      Libra: 'Libra',
      Scorpio: 'Scorpio',
      Sagittarius: 'Sagittarius',
      Capricorn: 'Capricorn',
      Aquarius: 'Aquarius',
      Pisces: 'Pisces',
    },
    elements: {
      Fire: 'Fire',
      Water: 'Water',
      Air: 'Air',
      Earth: 'Earth',
    },
  },
};

export const getText = (lang: Language, key: string) => {
  const keys = key.split('.');
  let current: any = TRANSLATIONS[lang];
  for (const k of keys) {
    if (current[k] === undefined) return key;
    current = current[k];
  }
  return current;
};

export const getZodiacSign = (lang: Language, sign: string): string => {
  const zodiacTranslations = TRANSLATIONS[lang].zodiac as Record<string, string>;
  if (!sign) return sign;
  const normalized = sign.charAt(0).toUpperCase() + sign.slice(1).toLowerCase();
  return zodiacTranslations[normalized] || zodiacTranslations[sign] || sign;
};

export const getElement = (lang: Language, element: string): string => {
  const elementTranslations = TRANSLATIONS[lang].elements as Record<string, string>;
  return elementTranslations[element] || element;
};
