import { defineKnowledgeTopic } from './topicBuilder';
import type { KnowledgeTopicSource } from './types';

const topic = defineKnowledgeTopic;

export const BASIC_EXTENDED_TOPICS = [
  topic({
    id: 'astrology-overview', category: 'start',
    title: { ru: 'Что такое астрология', en: 'What is astrology?' },
    summary: { ru: 'Астрология — историческая система интерпретации положений небесных тел и расчётных точек. Она использует астрономические данные, но её символические трактовки не являются частью современной астрономии.', en: 'Astrology is a historical system for interpreting positions of celestial bodies and calculated points; its symbolic claims are distinct from modern astronomy.' },
    shortAnswer: { ru: 'Астрономия измеряет и объясняет небесные объекты, а астрология приписывает рассчитанным положениям символические значения.', en: 'Astronomy studies celestial objects; astrology assigns symbolic meanings to calculated positions.' },
    aliases: { ru: ['астрология', 'что такое астрология', 'астрология простыми словами'], en: ['astrology', 'what is astrology'] },
    keywords: { ru: ['астрономия', 'гороскоп', 'традиция', 'символическая система'], en: ['astronomy', 'horoscope', 'tradition', 'symbolic system'] },
    ruSections: [
      { title: 'Что это на самом деле', kind: 'definition', paragraphs: ['Астрология объединяет расчёт карты неба с набором правил интерпретации. Координаты Солнца, Луны и планет можно вычислить астрономически; выводы о характере или событиях относятся уже к астрологической традиции.'] },
      { title: 'Как устроен метод', kind: 'mechanism', paragraphs: ['Сначала выбирают момент и место, затем рассчитывают положения объектов на зодиакальном круге, дома и углы между точками. После этого астролог читает получившуюся схему по правилам выбранной школы.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Астрология и астрономия исторически долго развивались рядом, но сегодня это разные области. Астрономия — наука о Вселенной. Астрология — культурная и интерпретационная практика, научная достоверность её предсказаний не установлена.'] },
      { title: 'Откуда это появилось', kind: 'history', depth: 'deep', paragraphs: ['У астрологии нет одного автора. Методы наблюдения и толкования неба формировались постепенно в разных культурах; привычная западная гороскопическая традиция особенно многим обязана вавилонским, эллинистическим, арабским и европейским источникам.'] },
    ],
    relatedTopicIds: ['what-is-horoscope', 'natal-chart-basics', 'zodiac-geometry', 'astrology-branches'],
    sourceIds: ['cambridge-astrology-history'],
  }),
  topic({
    id: 'what-is-horoscope', category: 'start',
    title: { ru: 'Что такое гороскоп', en: 'What is a horoscope?' },
    summary: { ru: 'Гороскоп — астрологическая карта для определённого момента и места или текст, написанный по такой карте. В разговорной речи этим словом чаще называют короткий прогноз по знаку зодиака.', en: 'A horoscope is an astrological chart for a time and place, or a text based on such a chart.' },
    shortAnswer: { ru: 'Натальная карта — один вид гороскопа; журнальный прогноз для знака — другое, сильно упрощённое употребление слова.', en: 'A natal chart is one kind of horoscope; a sign-based magazine forecast is a simplified use of the word.' },
    aliases: { ru: ['гороскоп', 'что такое гороскоп', 'астрологическая карта'], en: ['horoscope', 'astrological chart'] },
    ruSections: [
      { title: 'Два значения слова', paragraphs: ['В техническом смысле гороскопом называют схему неба, рассчитанную для момента и места. В повседневном смысле — текст «для Овна» или «для Рыб», который использует только знак Солнца и не равен полной карте.'] },
      { title: 'Зачем он используется', kind: 'astrology', paragraphs: ['Карту используют как основу натального, хорарного, элективного или прогностического разбора. Назначение зависит от того, на какой момент она построена и какой вопрос к ней задают.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Гороскоп не обязательно является прогнозом. Натальная карта описывает один момент рождения, а транзитная или возвратная карта относится к другому моменту.'] },
    ],
    relatedTopicIds: ['astrology-overview', 'natal-chart-basics', 'astrology-branches', 'transits-current-sky'],
  }),
  topic({
    id: 'zodiac-geometry', category: 'start',
    title: { ru: 'Как устроен зодиак', en: 'How the zodiac works' },
    summary: { ru: 'Зодиак в западной астрологии — круг вдоль эклиптики, разделённый на двенадцать равных участков по тридцать градусов. Эклиптика — видимый годовой путь Солнца по небу.', en: 'In Western astrology the zodiac is a circle along the ecliptic divided into twelve equal 30-degree signs.' },
    shortAnswer: { ru: 'Триста шестьдесят градусов дают удобный полный круг, а двенадцать знаков — двенадцать равных отрезков этого круга.', en: 'The 360-degree circle is divided into twelve equal signs.' },
    aliases: { ru: ['зодиак', 'эклиптика', 'почему двенадцать знаков', 'почему круг триста шестьдесят градусов', '360 градусов'], en: ['zodiac', 'ecliptic', 'why twelve signs', '360 degrees'] },
    keywords: { ru: ['круг', 'двенадцать знаков', 'тридцать градусов', 'путь солнца'], en: ['circle', 'twelve signs', 'thirty degrees', 'sun path'] },
    ruSections: [
      { title: 'Что такое эклиптика', kind: 'fact', paragraphs: ['Если в течение года отмечать положение Солнца на фоне звёзд, получится замкнутый путь. Его называют эклиптикой. Планеты и Луна обычно видны недалеко от этой линии, поэтому она стала основой зодиакальной системы.'] },
      { title: 'Почему круг делят на 360°', kind: 'calculation', paragraphs: ['Градус — единица измерения угла. Деление круга на триста шестьдесят частей пришло из древней математики и удобно делится на множество целых долей. В астрологии знак занимает одну двенадцатую круга, то есть тридцать градусов.'] },
      { title: 'Почему знаков двенадцать', kind: 'history', paragraphs: ['Двенадцатичленная система сложилась исторически и связана с календарём и ранними наблюдениями годового движения Солнца. Это соглашение традиции, а не количество современных официальных созвездий, пересекаемых эклиптикой.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Знак — равный участок зодиакального круга. Созвездие — область неба с официальными границами и неровным размером. Поэтому знак Овна и созвездие Овна — не одно и то же.'] },
    ],
    relatedTopicIds: ['signs-overview', 'zodiac-signs-vs-constellations', 'tropical-sidereal-zodiac', 'degree-and-position'],
    sourceIds: ['iau-zodiac'],
  }),
  ...([
    ['fire-element', 'Огонь', 'Fire', 'Огонь объединяет Овен, Лев и Стрелец. В астрологии эту стихию связывают с инициативой, заметным выражением воли и стремлением действовать.', ['огонь в астрологии', 'огненные знаки'], ['Овен', 'Лев', 'Стрелец']],
    ['earth-element', 'Земля', 'Earth', 'Земля объединяет Телец, Дева и Козерог. В астрологии эту стихию связывают с практичностью, конкретным результатом и вниманием к материальным условиям.', ['земля в астрологии', 'земные знаки'], ['Телец', 'Дева', 'Козерог']],
    ['air-element', 'Воздух', 'Air', 'Воздух объединяет Близнецы, Весы и Водолей. В астрологии эту стихию связывают с обменом идеями, связями между людьми и способностью видеть разные точки зрения.', ['воздух в астрологии', 'воздушные знаки'], ['Близнецы', 'Весы', 'Водолей']],
    ['water-element', 'Вода', 'Water', 'Вода объединяет Рак, Скорпион и Рыбы. В астрологии эту стихию связывают с эмоциональной восприимчивостью, привязанностью и чувствительностью к контексту.', ['вода в астрологии', 'водные знаки'], ['Рак', 'Скорпион', 'Рыбы']],
  ] as const).map(([id, ruTitle, enTitle, summary, aliases, signs]) => topic({
    id, category: 'signs',
    title: { ru: ruTitle, en: enTitle },
    summary: { ru: summary, en: `${enTitle} is one of the four elements used to group zodiac signs.` },
    shortAnswer: { ru: `${ruTitle} — не вещество внутри человека, а название одной из четырёх групп знаков.`, en: `${enTitle} is a symbolic sign group, not a physical substance in a person.` },
    aliases: { ru: aliases, en: [`${enTitle.toLowerCase()} element`, `${enTitle.toLowerCase()} signs`] },
    ruSections: [
      { title: 'Какие знаки входят', paragraphs: [`К этой группе относятся ${signs.slice(0, -1).join(', ')} и ${signs.at(-1)}. У них разные характеры, но традиция объединяет их по похожему способу проявлять качества знака.`] },
      { title: 'Как это используют в астрологии', kind: 'astrology', paragraphs: ['Стихия помогает сравнить общий стиль знаков. Она не заменяет положение планет, дома и аспекты и не делит людей на четыре готовых типа.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: [`${ruTitle} здесь — символическая категория. Это не утверждение о химическом составе, темпераменте или неизменном характере человека.`] },
    ],
    relatedTopicIds: ['sign-elements', ...signs.map((sign) => `sign-${({ Овен: 'aries', Лев: 'leo', Стрелец: 'sagittarius', Телец: 'taurus', Дева: 'virgo', Козерог: 'capricorn', Близнецы: 'gemini', Весы: 'libra', Водолей: 'aquarius', Рак: 'cancer', Скорпион: 'scorpio', Рыбы: 'pisces' } as Record<string, string>)[sign]}`)],
  })),
  ...([
    ['cardinal-modality', 'Кардинальные знаки', 'Cardinal signs', 'Овен, Рак, Весы и Козерог', 'начинать новый цикл и задавать направление'],
    ['fixed-modality', 'Фиксированные знаки', 'Fixed signs', 'Телец, Лев, Скорпион и Водолей', 'удерживать курс, закреплять и развивать начатое'],
    ['mutable-modality', 'Мутабельные знаки', 'Mutable signs', 'Близнецы, Дева, Стрелец и Рыбы', 'адаптироваться, завершать цикл и переходить к следующему'],
  ] as const).map(([id, ruTitle, enTitle, signs, meaning]) => topic({
    id, category: 'signs', title: { ru: ruTitle, en: enTitle },
    summary: { ru: `${ruTitle} — одна из трёх модальностей зодиака. К ней относятся ${signs}; в астрологии группу связывают со склонностью ${meaning}.`, en: `${enTitle} are one of the three zodiac modalities.` },
    shortAnswer: { ru: 'Модальность описывает не «хороший» или «плохой» характер, а место знака внутри сезонного цикла.', en: 'A modality describes a sign’s place in a cycle, not a good or bad personality.' },
    aliases: { ru: [ruTitle.toLowerCase(), ruTitle.replace(' знаки', '').toLowerCase()], en: [enTitle.toLowerCase()] },
    ruSections: [
      { title: 'Как устроена группа', paragraphs: [`В каждом сезоне первый знак кардинальный, средний фиксированный, последний мутабельный. Поэтому модальность — способ описать роль знака в повторяющемся цикле.`] },
      { title: 'Как это используют', kind: 'astrology', paragraphs: [`Астрологи смотрят, каких модальностей больше в карте, чтобы описать общий ритм действий: запуск, удержание или адаптацию. Один показатель не определяет человека целиком.`] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Мутабельность не означает ненадёжность, фиксированность — упрямство, а кардинальность — лидерство в каждой ситуации. Это более широкие категории.'] },
    ],
    relatedTopicIds: ['sign-modalities', 'sign-aries', 'sign-taurus', 'sign-gemini'],
  })),
  topic({
    id: 'sign-polarity', category: 'signs',
    title: { ru: 'Полярность знаков', en: 'Sign polarity' },
    summary: { ru: 'Полярность делит знаки на две чередующиеся группы. В современных текстах их часто называют активными и восприимчивыми; старые названия «мужские» и «женские» описывают традиционную символику, а не пол человека.', en: 'Polarity divides signs into two alternating groups, often described as active and receptive.' },
    shortAnswer: { ru: 'Полярность — техническая группировка знаков, не описание гендера и не оценка силы характера.', en: 'Polarity is a technical sign grouping, not a description of gender.' },
    aliases: { ru: ['полярность', 'активные и восприимчивые знаки', 'мужские и женские знаки'], en: ['polarity', 'positive and negative signs', 'active receptive signs'] },
    ruSections: [
      { title: 'Как делятся знаки', paragraphs: ['Огонь и Воздух относят к одной полярности, Землю и Воду — к другой. Группы чередуются по всему зодиаку.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Полярность помогает описать, направлена ли символика знака скорее на выражение вовне или на восприятие и ответ. Остальная карта может заметно менять общий баланс.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Исторические слова «мужской» и «женский» не означают, что знак предписывает человеку пол, гендерную роль или набор качеств.'] },
    ],
    relatedTopicIds: ['sign-elements', 'fire-element', 'earth-element', 'air-element', 'water-element'],
  }),
  topic({
    id: 'sign-rulership', category: 'signs',
    title: { ru: 'Управитель знака', en: 'Sign ruler' },
    summary: { ru: 'Управитель знака — планета, которой астрологическая традиция приписывает особую связь с этим знаком. Например, Марс считается управителем Овна, а Венера — Тельца и Весов.', en: 'A sign ruler is a planet traditionally assigned a special relationship with a zodiac sign.' },
    shortAnswer: { ru: 'Управитель — правило астрологической системы, а не физическое управление планетой участком неба.', en: 'Rulership is an astrological convention, not physical control over a region of space.' },
    aliases: { ru: ['управитель знака', 'планета управитель', 'обитель знака'], en: ['sign ruler', 'ruling planet', 'planetary ruler'] },
    ruSections: [
      { title: 'Как это работает', paragraphs: ['Когда планета находится в знаке, астролог смотрит на управителя этого знака как на связанную часть карты. Так строятся цепочки управителей и диспозиторов.'] },
      { title: 'Традиционные и современные управители', depth: 'deep', paragraphs: ['До открытия Урана, Нептуна и Плутона использовали семь видимых невооружённым глазом светил и планет. Современные школы часто добавляют новые управительства, поэтому таблицы могут отличаться.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Управитель знака и управитель дома — не всегда одна и та же запись. Управитель дома определяется знаком на его начале или, в целознаковой системе, знаком самого дома.'] },
    ],
    relatedTopicIds: ['planets-overview', 'rulers-dispositors', 'planetary-dignities', 'signs-overview'],
  }),
  topic({
    id: 'tropical-sidereal-zodiac', category: 'signs',
    title: { ru: 'Тропический и сидерический зодиак', en: 'Tropical and sidereal zodiac' },
    summary: { ru: 'Тропический и сидерический зодиаки используют одинаковые названия двенадцати знаков, но по-разному закрепляют начало круга. Тропический отсчитывает его от весеннего равноденствия, сидерический — относительно звёздного фона.', en: 'Tropical and sidereal zodiacs use the same sign names but anchor the circle differently.' },
    shortAnswer: { ru: 'Это две системы координат; расхождение между ними не означает ошибку одной программы.', en: 'They are two coordinate systems, so different placements do not automatically mean an error.' },
    aliases: { ru: ['тропический зодиак', 'сидерический зодиак', 'аянамша'], en: ['tropical zodiac', 'sidereal zodiac', 'ayanamsha'] },
    ruSections: [
      { title: 'Откуда берётся разница', kind: 'mechanism', paragraphs: ['Из-за медленного изменения направления земной оси точка равноденствия смещается относительно звёзд. Тропический круг следует за равноденствием; сидерический вводит поправку, чтобы привязать знаки к выбранной звёздной системе.'] },
      { title: 'Как это используют', kind: 'astrology', paragraphs: ['Западная астрология чаще работает с тропическим зодиаком, индийская — с сидерическим. Внутри сидерических школ существуют разные значения поправки, называемой аянамшей.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Сидерические знаки тоже являются равными секторами по тридцать градусов и не совпадают один к одному с официальными границами созвездий.'] },
    ],
    relatedTopicIds: ['zodiac-geometry', 'zodiac-signs-vs-constellations', 'signs-overview'],
    sourceIds: ['iau-zodiac'],
  }),
  topic({
    id: 'house-cusp', category: 'houses',
    title: { ru: 'Куспид дома', en: 'House cusp' },
    summary: { ru: 'Куспид — граница, с которой начинается дом в выбранной системе домов. Его положение записывают в градусах знака.', en: 'A house cusp is the boundary where a house begins in a chosen house system.' },
    shortAnswer: { ru: 'Куспид — начало сектора, а не отдельная планета или дополнительный дом.', en: 'A cusp is the start of a sector, not a planet or an extra house.' },
    aliases: { ru: ['куспид', 'граница дома', 'начало дома'], en: ['cusp', 'house cusp', 'house boundary'] },
    ruSections: [
      { title: 'Как его определяют', kind: 'calculation', paragraphs: ['Программа рассчитывает куспиды по времени, месту и правилам выбранной системы домов. В некоторых системах все границы расположены через равные тридцать градусов, в других размеры домов различаются.'] },
      { title: 'Зачем это используют', kind: 'astrology', paragraphs: ['Знак на куспиде помогает определить управителя дома. Положение планеты относительно границы решает, в какой дом она попадает в этой системе.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Рождение «на куспиде знаков» и куспид дома — разные темы. Знаки образуют один круг деления, дома — другой.'] },
    ],
    relatedTopicIds: ['houses-overview', 'house-systems', 'birth-time-and-houses', 'rulers-dispositors'],
  }),
  topic({
    id: 'house-systems', category: 'houses',
    title: { ru: 'Системы домов', en: 'House systems' },
    summary: { ru: 'Система домов — набор правил, по которым пространство вокруг места наблюдения делят на двенадцать секторов карты. Разные правила дают разные границы домов.', en: 'A house system is a set of rules for dividing a chart into twelve sectors.' },
    shortAnswer: { ru: 'Плацидус, целые знаки и равнодомная система — разные способы построить те же двенадцать домов.', en: 'Placidus, Whole Sign, and Equal House are different ways to construct the same twelve houses.' },
    aliases: { ru: ['система домов', 'системы домов', 'какую систему домов выбрать'], en: ['house system', 'house systems'] },
    ruSections: [
      { title: 'Почему систем несколько', paragraphs: ['Дом — не видимый объект на небе, а расчётный сектор. Исторически астрологи предлагали разные геометрические и временные способы разделить небесную сферу.'] },
      { title: 'Что меняется', kind: 'calculation', paragraphs: ['Обычно сохраняются сами планеты и их положения в знаках, но меняются куспиды и иногда дома планет. В угловых системах Асцендент и MC остаются важными опорами, хотя правила промежуточных домов различаются.'] },
      { title: 'Как сравнивать', kind: 'astrology', paragraphs: ['Полезно сначала выбрать одну систему и читать карту последовательно. Переключение между системами не делает одну карту «настоящей», а другую «ложной»; оно показывает различие методов.'] },
    ],
    relatedTopicIds: ['houses-overview', 'house-placidus', 'house-whole-sign', 'house-equal', 'house-cusp'],
    sourceIds: ['swiss-ephemeris-houses'],
  }),
  ...([
    ['house-placidus', 'Плацидус', 'Placidus', 'Плацидус — система домов, которая делит суточное движение точек неба на временные части. Поэтому дома обычно получаются разного размера.', ['плацидус', 'система плацидуса']],
    ['house-whole-sign', 'Целые знаки (Whole Sign)', 'Whole Sign houses', 'В системе целых знаков весь знак, в котором находится Асцендент, становится первым домом; следующий знак — вторым и так далее.', ['целые знаки', 'whole sign', 'целознаковая система']],
    ['house-equal', 'Равнодомная система', 'Equal House system', 'В равнодомной системе все дома имеют по тридцать градусов. В распространённом варианте первый дом начинается точно с градуса Асцендента.', ['равнодомная система', 'равные дома', 'equal houses']],
  ] as const).map(([id, ruTitle, enTitle, summary, aliases]) => topic({
    id, category: 'houses', title: { ru: ruTitle, en: enTitle },
    summary: { ru: summary, en: `${enTitle} is one method for dividing a chart into twelve houses.` },
    shortAnswer: { ru: `${ruTitle} — способ расчёта границ домов, а не отдельный вид натальной карты.`, en: `${enTitle} changes house boundaries, not the underlying planetary positions.` },
    aliases: { ru: aliases, en: [enTitle.toLowerCase()] },
    ruSections: [
      { title: 'Как устроена система', kind: 'calculation', paragraphs: [summary] },
      { title: 'Что меняется в карте', paragraphs: ['При смене системы могут измениться куспиды и номера домов некоторых планет. Их знаки и взаимные углы при этом остаются прежними.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Система домов не является отдельной школой астрологии и не меняет дату или место, для которых рассчитана карта.'] },
    ],
    relatedTopicIds: ['house-systems', 'houses-overview', 'house-cusp', 'ascendant'],
    sourceIds: ['swiss-ephemeris-houses'],
  })),
  topic({
    id: 'aspect-exact', category: 'aspects',
    title: { ru: 'Точный аспект', en: 'Exact aspect' },
    summary: { ru: 'Точный аспект возникает, когда угловое расстояние между двумя точками совпадает с углом аспекта или отличается от него совсем немного.', en: 'An exact aspect occurs when the angular distance closely matches the aspect angle.' },
    shortAnswer: { ru: 'Квадрат ровно в девяносто градусов точнее квадрата в восьмидесяти семи; допустимое отклонение называют орбисом.', en: 'A 90-degree square is more exact than an 87-degree square; the allowed difference is the orb.' },
    aliases: { ru: ['точный аспект', 'экзактный аспект', 'точное соединение'], en: ['exact aspect', 'partile aspect'] },
    ruSections: [
      { title: 'Как это считается', kind: 'calculation', paragraphs: ['Для соединения сравнивают расстояние с нулём градусов, для секстиля — с шестьюдесятью, для квадрата — с девяноста, для тригона — со ста двадцатью, для оппозиции — со ста восемьюдесятью.'] },
      { title: 'Зачем это отмечают', kind: 'astrology', paragraphs: ['В астрологии более точный аспект обычно считают более заметным. Но точность не говорит, будет ли смысл «хорошим» или «плохим»: сначала важны сами точки и вид аспекта.'] },
      { title: 'Часто путают', kind: 'confusion', paragraphs: ['Слово «точный» используют по-разному: иногда только для полного совпадения угла, иногда для очень малого орбиса. Поэтому полезно смотреть на конкретное число.'] },
    ],
    relatedTopicIds: ['aspects-overview', 'aspect-orb', 'aspect-square', 'aspect-conjunction'],
    sourceIds: ['astro-aspects'],
  }),
] satisfies readonly KnowledgeTopicSource[];
