export type RetentionScenarioSeed = {
  key: string;
  name: string;
  description: string;
  dayPart: 'morning' | 'day' | 'evening' | 'reactivation';
  timeWindowStart: string;
  timeWindowEnd: string;
  priority: number;
  maxPerDay: number;
  cooldownHours: number;
  segment: string;
  deepLinkSection: string;
  imageTags: string[];
  templates: Array<{
    title: string;
    body: string;
    buttonText: string;
    tags: string[];
    weight?: number;
  }>;
};

function template(title: string, body: string, buttonText: string, tags: string[]) {
  return { title, body, buttonText, tags, weight: 100 };
}

function eight(
  title: string,
  bodies: string[],
  buttonText: string,
  tags: string[],
): RetentionScenarioSeed['templates'] {
  return bodies.slice(0, 8).map((body) => template(title, body, buttonText, tags));
}

function pairs(
  items: Array<[string, string]>,
  buttonText: string,
  tags: string[],
): RetentionScenarioSeed['templates'] {
  return items.slice(0, 8).map(([title, body]) => template(title, body, buttonText, tags));
}

export const RETENTION_NOTIFICATION_SCENARIO_SEEDS: RetentionScenarioSeed[] = [
  {
    key: 'daily_card',
    name: 'Личный гороскоп дня',
    description: 'Утренний личный прогноз по натальной карте.',
    dayPart: 'morning',
    timeWindowStart: '08:00',
    timeWindowEnd: '11:00',
    priority: 860,
    maxPerDay: 1,
    cooldownHours: 20,
    segment: 'daily_active_free',
    deepLinkSection: 'daily_card',
    imageTags: ['daily_card', 'morning'],
    templates: pairs([
      ['Прогноз на сегодня готов', '{{daily_summary}}'],
      ['Что сегодня сработает', 'Открой личный прогноз: главный вывод, риск и конкретные действия.'],
      ['Перед первым решением', 'Проверь личный прогноз на сегодня. Он рассчитан по твоей натальной карте.'],
      ['{{name}}, прогноз готов', 'Сегодняшний расчёт уже в приложении. Чтение займёт пару минут.'],
      ['Что лучше сделать сегодня', 'Открой прогноз и сразу посмотри, что даст результат, а что помешает.'],
      ['Сегодня по твоей карте', '{{daily_summary}} Подробности уже в приложении.'],
    ], 'Открыть прогноз', ['daily_card', 'morning']),
  },
  {
    key: 'sign_daily',
    name: 'Гороскоп по знаку',
    description: 'Дневной прогноз по знаку зодиака.',
    dayPart: 'day',
    timeWindowStart: '11:00',
    timeWindowEnd: '15:30',
    priority: 600,
    maxPerDay: 1,
    cooldownHours: 20,
    segment: 'daily_active_free',
    deepLinkSection: 'horoscope',
    imageTags: ['horoscope', 'day'],
    templates: pairs([
      ['Гороскоп для {{sign}} готов', 'Главный вывод на сегодня уже в приложении.'],
      ['{{sign}}: что важно сегодня', 'Короткий прогноз по знаку без длинных вступлений.'],
      ['Что может помочь сегодня', 'Открой прогноз для {{sign}} и проверь главный риск дня.'],
      ['Прогноз по знаку', 'Для {{sign}} готов новый текст на сегодня.'],
      ['Перед важным разговором', 'Посмотри прогноз для {{sign}}: что поможет и что может всё испортить.'],
      ['Сегодня для {{sign}}', 'Один главный вывод и три конкретных пункта уже внутри.'],
    ], 'Открыть гороскоп', ['horoscope']),
  },
  {
    key: 'weekly_horoscope',
    name: 'Гороскоп на неделю',
    description: 'Недельный прогноз по знаку.',
    dayPart: 'morning',
    timeWindowStart: '09:00',
    timeWindowEnd: '13:00',
    priority: 770,
    maxPerDay: 1,
    cooldownHours: 120,
    segment: 'daily_active_free',
    deepLinkSection: 'horoscope',
    imageTags: ['horoscope', 'week'],
    templates: eight('Гороскоп на неделю готов', [
      'Главный сюжет недели, возможная проблема и три конкретных действия.',
      'Посмотри, на каких днях недели лучше решать важные вопросы.',
      'Недельный прогноз для твоего знака уже в приложении.',
      'Что может помочь на этой неделе и где легко ошибиться.',
      'Один понятный прогноз вместо семи одинаковых текстов на каждый день.',
      'Проверь, где стоит действовать, а где сначала нужны факты.',
    ], 'Открыть гороскоп', ['horoscope', 'week']),
  },
  {
    key: 'compatibility',
    name: 'Совместимость',
    description: 'Напоминание открыть сравнение двух людей.',
    dayPart: 'day',
    timeWindowStart: '13:00',
    timeWindowEnd: '21:00',
    priority: 540,
    maxPerDay: 1,
    cooldownHours: 96,
    segment: 'daily_active_free',
    deepLinkSection: 'synastry',
    imageTags: ['synastry'],
    templates: pairs([
      ['Сравнить две карты', 'Посмотри, где вам легко договориться и из-за чего чаще начинаются споры.'],
      ['Как вы общаетесь', 'Добавь партнёра, друга, родственника или коллегу и сравни две карты.'],
      ['Почему с ним сложно', 'Совместимость показывает разницу в общении, решениях и реакции на конфликт.'],
      ['Проверить совместимость', 'По знакам — быстро. По двум натальным картам — подробнее.'],
      ['Кто-то на уме?', 'Добавь человека и посмотри сильные и слабые места вашей связи.'],
      ['Где вы понимаете друг друга', 'Сравнение двух карт уже доступно в разделе совместимости.'],
    ], 'Проверить совместимость', ['synastry']),
  },
  {
    key: 'birthday',
    name: 'Поздравление с днём рождения',
    description: 'Поздравление и годовой прогноз в день рождения.',
    dayPart: 'morning',
    timeWindowStart: '08:00',
    timeWindowEnd: '12:00',
    priority: 900,
    maxPerDay: 1,
    cooldownHours: 48,
    segment: 'daily_active_free',
    deepLinkSection: 'horoscope',
    imageTags: ['birthday'],
    templates: pairs([
      ['С днём рождения, {{name}}', 'Годовой прогноз уже в приложении. Посмотри главные периоды и решения года.'],
      ['{{name}}, с днём рождения', 'Для тебя готов прогноз на новый личный год.'],
      ['Сегодня твой день', 'Открой годовой прогноз и посмотри, какие месяцы выделяются сильнее всего.'],
      ['С днём рождения', 'Поздравляем. В приложении уже готов твой прогноз на год.'],
    ], 'Открыть прогноз', ['birthday']),
  },
  {
    key: 'premium_expiring',
    name: 'Premium скоро закончится',
    description: 'Напоминание о завершении Premium.',
    dayPart: 'evening',
    timeWindowStart: '17:00',
    timeWindowEnd: '21:00',
    priority: 700,
    maxPerDay: 1,
    cooldownHours: 48,
    segment: 'free_natal_opened_no_premium',
    deepLinkSection: 'premium',
    imageTags: ['premium'],
    templates: eight('Premium скоро закончится', [
      'После окончания закроются полные прогнозы, ответы на вопросы и подробные разборы.',
      'До конца Premium осталось несколько дней. Продлить можно в настройках.',
      'Скоро останутся только бесплатные функции. Напоминаем заранее.',
      'Проверь дату окончания Premium и условия продления.',
      'Полные прогнозы и совместимость закроются после окончания подписки.',
    ], 'Проверить подписку', ['premium']),
  },
  {
    key: 'sunday_summary',
    name: 'Итог недели',
    description: 'Воскресный итог и переход к следующей неделе.',
    dayPart: 'evening',
    timeWindowStart: '17:00',
    timeWindowEnd: '21:30',
    priority: 600,
    maxPerDay: 1,
    cooldownHours: 120,
    segment: 'daily_active_free',
    deepLinkSection: 'horoscope',
    imageTags: ['week'],
    templates: eight('Итог недели готов', [
      'Посмотри, какой вопрос повторялся чаще всего и что перешло на следующую неделю.',
      'Короткий итог недели уже в приложении: факты, решения и незакрытые вопросы.',
      'Неделя закончилась. Проверь, что удалось и что всё ещё требует решения.',
      'Открой итог недели и сравни его с прогнозом на следующую.',
      'Главные события и вопросы недели собраны в одном месте.',
    ], 'Открыть итог', ['week']),
  },
  {
    key: 'natal_free',
    name: 'Натальная карта готова',
    description: 'Возврат к рассчитанной карте, которую пользователь ещё не открыл.',
    dayPart: 'morning',
    timeWindowStart: '09:00',
    timeWindowEnd: '20:00',
    priority: 900,
    maxPerDay: 1,
    cooldownHours: 48,
    segment: 'free_natal_ready_not_opened',
    deepLinkSection: 'natal_free',
    imageTags: ['natal', 'chart'],
    templates: pairs([
      ['Натальная карта рассчитана', 'Открой разбор характера, отношений, денег и работы.'],
      ['{{name}}, карта готова', 'Расчёт по твоим данным рождения уже завершён.'],
      ['Можно читать разбор', 'Натальная карта и первый полный раздел уже открыты.'],
      ['Твой расчёт готов', 'Посмотри основные положения карты и понятное объяснение без лишних терминов.'],
      ['Карта сохранена', 'Открой её сейчас или вернись позже — расчёт не пропадёт.'],
      ['Что получилось по карте', 'Главные выводы уже готовы. Начни с первого раздела.'],
    ], 'Открыть карту', ['natal']),
  },
  {
    key: 'love',
    name: 'Отношения',
    description: 'Уведомления для пользователей, выбравших тему отношений.',
    dayPart: 'day',
    timeWindowStart: '12:00',
    timeWindowEnd: '21:00',
    priority: 650,
    maxPerDay: 1,
    cooldownHours: 36,
    segment: 'love_interested',
    deepLinkSection: 'love',
    imageTags: ['love'],
    templates: eight('Отношения сегодня', [
      'Если нужен ответ, задай прямой вопрос. Намёки сегодня только добавят путаницы.',
      'Перед сообщением проверь, чего ты хочешь: ясности, реакции или решения.',
      'Смотри на действия, а не на одно красивое обещание.',
      'Разговор давно откладывается? В прогнозе есть ответ, стоит ли начинать его сегодня.',
      'Не додумывай ответ за другого человека. Сначала получи факты.',
      'Открой раздел отношений: что сегодня поможет и что усилит конфликт.',
    ], 'Открыть отношения', ['love']),
  },
  {
    key: 'money',
    name: 'Деньги',
    description: 'Уведомления о покупках и финансовых решениях.',
    dayPart: 'day',
    timeWindowStart: '11:00',
    timeWindowEnd: '19:00',
    priority: 640,
    maxPerDay: 1,
    cooldownHours: 36,
    segment: 'money_interested',
    deepLinkSection: 'money',
    imageTags: ['money'],
    templates: eight('Перед покупкой', [
      'Проверь цену, условия и реальную задачу покупки до оплаты.',
      'Сегодня слабое место — решение на эмоциях. Сравни хотя бы два варианта.',
      'Если покупка не была запланирована утром, сначала проверь бюджет.',
      'Не соглашайся на условия, которые не дочитал до конца.',
      'Финансовое решение требует цифр, а не хорошего первого впечатления.',
      'Открой раздел денег: что сегодня поможет и где легко переплатить.',
    ], 'Открыть деньги', ['money']),
  },
  {
    key: 'work',
    name: 'Работа',
    description: 'Уведомления о задачах, переговорах и рабочих решениях.',
    dayPart: 'day',
    timeWindowStart: '10:00',
    timeWindowEnd: '18:00',
    priority: 640,
    maxPerDay: 1,
    cooldownHours: 30,
    segment: 'work_interested',
    deepLinkSection: 'work',
    imageTags: ['work'],
    templates: eight('Работа сегодня', [
      'Выбери одну задачу с понятным результатом и закончи её до нового старта.',
      'В переговорах сегодня нужны цифры, сроки и один конкретный следующий шаг.',
      'Не бери десять задач одновременно. Определи, какая из них действительно важнее.',
      'Зависшая задача требует первого действия, а не ещё одного плана.',
      'Проверь, есть ли у тебя полномочия отвечать за результат.',
      'Открой раздел работы: что сегодня даст результат и где не стоит давить.',
    ], 'Открыть работу', ['work']),
  },
  {
    key: 'synastry',
    name: 'Связь двух людей',
    description: 'Возврат к сравнению двух конкретных карт.',
    dayPart: 'day',
    timeWindowStart: '12:00',
    timeWindowEnd: '21:00',
    priority: 600,
    maxPerDay: 1,
    cooldownHours: 72,
    segment: 'love_interested',
    deepLinkSection: 'synastry',
    imageTags: ['synastry', 'love'],
    templates: pairs([
      ['Почему вы спорите об одном и том же', 'Сравни две карты и посмотри, как каждый реагирует на давление и неопределённость.'],
      ['Как вы договариваетесь', 'Совместимость показывает сильные и слабые места общения.'],
      ['Проверить вашу связь', 'Добавь человека и сравни отношения, решения и реакцию на конфликт.'],
      ['Где вы понимаете друг друга', 'Открой полный разбор двух карт без процентов и ярлыков.'],
      ['Что один не замечает в другом', 'Сравнение карт уже доступно в разделе совместимости.'],
      ['Сравнить ещё раз', 'Сохранённая пара карт готова к повторному разбору.'],
    ], 'Открыть совместимость', ['synastry']),
  },
  {
    key: 'premium',
    name: 'Premium',
    description: 'Premium-предложение после интереса к закрытой функции.',
    dayPart: 'day',
    timeWindowStart: '11:00',
    timeWindowEnd: '20:00',
    priority: 560,
    maxPerDay: 1,
    cooldownHours: 72,
    segment: 'high_intent_premium',
    deepLinkSection: 'premium',
    imageTags: ['premium'],
    templates: eight('Что откроет Premium', [
      'Полные прогнозы на сегодня, неделю, месяц и год, вопросы и подробные разборы карты.',
      'Открой все личные вопросы дня и полные прогнозы по периодам.',
      'В Premium доступны отношения, деньги, работа, совместимость и карты близких.',
      'Один доступ открывает все подробные разборы без отдельных покупок.',
      'Проверь состав подписки и выбери срок, который подходит.',
      'Premium открывает конкретные функции. Список и цена указаны до оплаты.',
    ], 'Посмотреть Premium', ['premium']),
  },
  {
    key: 'inactive_2d',
    name: 'Возврат 2 дня',
    description: 'Возврат после двух дней без входа.',
    dayPart: 'reactivation',
    timeWindowStart: '10:00',
    timeWindowEnd: '20:00',
    priority: 700,
    maxPerDay: 1,
    cooldownHours: 72,
    segment: 'inactive_2_days',
    deepLinkSection: 'daily_card',
    imageTags: ['reactivation'],
    templates: pairs([
      ['Прогноз на сегодня готов', 'Два дня тебя не было. Новый личный прогноз уже рассчитан.'],
      ['Что изменилось за два дня', 'Открой сегодняшний прогноз и сравни его с прошлым.'],
      ['Можно продолжить с сегодня', 'Ничего перечитывать не нужно. Открой текущую дату.'],
      ['Сегодняшний расчёт готов', 'Главный вывод, риск и вопросы уже в приложении.'],
    ], 'Открыть прогноз', ['reactivation']),
  },
  {
    key: 'inactive_7d',
    name: 'Возврат 7 дней',
    description: 'Возврат после недели без входа.',
    dayPart: 'reactivation',
    timeWindowStart: '10:00',
    timeWindowEnd: '20:00',
    priority: 730,
    maxPerDay: 1,
    cooldownHours: 120,
    segment: 'inactive_7_days',
    deepLinkSection: 'daily_card',
    imageTags: ['reactivation'],
    templates: pairs([
      ['Новый прогноз уже готов', 'Открой сегодняшний расчёт. Начинать заново не придётся.'],
      ['Неделя прошла', 'Посмотри текущий день и прогноз на следующую неделю.'],
      ['Вернуться можно с сегодняшнего дня', 'Твои данные и карта сохранены.'],
      ['Что важно сейчас', 'Свежий личный прогноз уже в приложении.'],
    ], 'Вернуться', ['reactivation']),
  },
  {
    key: 'inactive_14d',
    name: 'Возврат 14 дней',
    description: 'Возврат после двух недель без входа.',
    dayPart: 'reactivation',
    timeWindowStart: '10:00',
    timeWindowEnd: '20:00',
    priority: 750,
    maxPerDay: 1,
    cooldownHours: 168,
    segment: 'inactive_14_days',
    deepLinkSection: 'daily_card',
    imageTags: ['reactivation'],
    templates: pairs([
      ['Твои данные сохранены', 'Открой свежий прогноз на сегодня. Настраивать приложение заново не нужно.'],
      ['Прогнозы обновились', 'Сегодня, неделя и месяц уже рассчитаны для текущих дат.'],
      ['Можно начать с сегодня', 'Открой главный вывод дня и нужные вопросы.'],
      ['Новый расчёт готов', 'Посмотри, что изменилось за последние две недели.'],
    ], 'Открыть прогноз', ['reactivation']),
  },
  {
    key: 'birth_data_missing',
    name: 'Нет данных рождения',
    description: 'Возврат к заполнению данных рождения.',
    dayPart: 'morning',
    timeWindowStart: '09:00',
    timeWindowEnd: '20:00',
    priority: 1000,
    maxPerDay: 1,
    cooldownHours: 24,
    segment: 'new_user_no_birth_data',
    deepLinkSection: 'natal_free',
    imageTags: ['setup'],
    templates: pairs([
      ['Рассчитать личный гороскоп', 'Укажи дату, время и место рождения. По этим данным построим натальную карту.'],
      ['Нужны данные рождения', 'Без них доступны только гороскоп и совместимость по знакам.'],
      ['Натальная карта ещё не рассчитана', 'Заполни данные и открой первый полный разбор.'],
      ['Личный прогноз начинается с карты', 'Дата, время и место рождения нужны для расчёта.'],
      ['Ввести данные можно сейчас', 'Анкета сохранится, а расчёт запустится сразу после отправки.'],
    ], 'Ввести данные', ['setup', 'natal']),
  },
  {
    key: 'birth_time_missing',
    name: 'Нет времени рождения',
    description: 'Объяснение ограничений карты без точного времени.',
    dayPart: 'morning',
    timeWindowStart: '09:00',
    timeWindowEnd: '20:00',
    priority: 950,
    maxPerDay: 1,
    cooldownHours: 48,
    segment: 'birth_data_no_time',
    deepLinkSection: 'natal_free',
    imageTags: ['setup', 'natal'],
    templates: pairs([
      ['Знаешь время рождения?', 'Добавь его, чтобы точно рассчитать Асцендент и дома.'],
      ['Время рождения не указано', 'Основная карта рассчитана, но Асцендент и дома сейчас недоступны.'],
      ['Можно указать примерное время', 'Мы учтём возможную погрешность и отметим зависимые выводы.'],
      ['Уточнить расчёт', 'Добавь время рождения, если оно стало известно.'],
      ['Без времени тоже можно', 'Основные положения планет рассчитаны. Время нужно для Асцендента и домов.'],
    ], 'Добавить время', ['setup', 'natal']),
  },
  {
    key: 'unfinished_action',
    name: 'Незавершённое действие',
    description: 'Возврат к незавершённой настройке или действию.',
    dayPart: 'day',
    timeWindowStart: '10:00',
    timeWindowEnd: '20:00',
    priority: 870,
    maxPerDay: 1,
    cooldownHours: 24,
    segment: 'need_attention',
    deepLinkSection: 'natal_free',
    imageTags: ['setup', 'natal'],
    templates: pairs([
      ['Остался один шаг', '{{unfinished_action}}. Продолжи с того же места.'],
      ['Данные сохранены', 'Начинать заново не придётся.'],
      ['Расчёт ещё не запущен', 'Заверши последний шаг, чтобы открыть результат.'],
      ['Настройка не закончена', 'Открой приложение и продолжи там, где остановился.'],
      ['Можно продолжить позже', 'Прогресс сохранён. Последний шаг всё ещё ждёт подтверждения.'],
    ], 'Продолжить', ['unfinished']),
  },
];
