import type { Locale } from './site';

export type StaticPage = {
  slug: string;
  title: string;
  description: string;
  intro: string;
  noindex?: boolean;
  sections: Array<{ title: string; body: string[] }>;
};

type Localized = Record<Locale, StaticPage>;

const pages: Localized[] = [
  {
    ru:{slug:'personal-horoscope',title:'Личный гороскоп',description:'Персональные прогнозы на сегодня, неделю, месяц и год по данным рождения.',intro:'Общий знак даёт ориентир. Личный прогноз добавляет натальную карту и расчёты выбранного периода.',sections:[{title:'Что учитывается',body:['Дата, время и место рождения.','Рассчитанные связи текущего периода с натальной картой.','Сила и уместность темы, а не случайный набор общих фраз.']},{title:'Что получает пользователь',body:['Главный разбор периода.','Любовь, настроение, дом, друзья, работа и деньги.','Понятные пояснения без технической перегрузки.']},{title:'Границы',body:['Прогноз показывает вероятности и условия, а не обещает неизбежные события.']}]},
    en:{slug:'personal-horoscope',title:'Personal horoscope',description:'Personal forecasts for today, week, month, and year using birth data.',intro:'A Sun sign gives a general direction. A personal forecast adds the natal chart and calculations for the selected period.',sections:[{title:'What it uses',body:['Birth date, time, and place.','Calculated connections between the current period and the natal chart.','Relevant themes rather than random generic statements.']},{title:'What the user receives',body:['A main period reading.','Love, mood, home, friends, work, and money.','Clear explanations without technical overload.']},{title:'Limits',body:['The forecast describes probabilities and conditions, not unavoidable events.']}]},
    es:{slug:'personal-horoscope',title:'Horóscopo personal',description:'Pronósticos personales para hoy, semana, mes y año con datos de nacimiento.',intro:'El signo solar ofrece una orientación general. El pronóstico personal añade la carta natal y cálculos del período elegido.',sections:[{title:'Qué utiliza',body:['Fecha, hora y lugar de nacimiento.','Relaciones calculadas entre el período actual y la carta natal.','Temas relevantes en lugar de frases genéricas al azar.']},{title:'Qué recibe la persona',body:['Lectura principal del período.','Amor, estado de ánimo, hogar, amistades, trabajo y dinero.','Explicaciones claras sin sobrecarga técnica.']},{title:'Límites',body:['El pronóstico describe probabilidades y condiciones, no eventos inevitables.']}]},
  },
  {
    ru:{slug:'natal-chart',title:'Натальная карта',description:'Что карта может объяснить о характере, реакциях, работе и отношениях.',intro:'Натальная карта полезна, когда её читают как систему взаимосвязей, а не как список ярлыков.',sections:[{title:'Сильные стороны',body:['Способы действовать, общаться, учиться и принимать решения.']},{title:'Повторяющиеся сценарии',body:['Внутренние противоречия, привычные реакции и темы, которые возвращаются.']},{title:'Без выдуманной точности',body:['Карта не гарантирует профессию, доход, брак или конкретную дату события.']}]},
    en:{slug:'natal-chart',title:'Natal chart',description:'What a chart may explain about personality, reactions, work, and relationships.',intro:'A natal chart is useful when read as a connected system rather than a list of labels.',sections:[{title:'Strengths',body:['Ways of acting, communicating, learning, and making decisions.']},{title:'Repeating patterns',body:['Inner contradictions, familiar reactions, and themes that return.']},{title:'No false precision',body:['A chart does not guarantee a profession, income, marriage, or exact event date.']}]},
    es:{slug:'natal-chart',title:'Carta natal',description:'Qué puede explicar una carta sobre personalidad, reacciones, trabajo y relaciones.',intro:'La carta natal resulta útil cuando se lee como un sistema relacionado, no como una lista de etiquetas.',sections:[{title:'Fortalezas',body:['Formas de actuar, comunicar, aprender y tomar decisiones.']},{title:'Patrones repetidos',body:['Contradicciones internas, reacciones habituales y temas que vuelven.']},{title:'Sin falsa precisión',body:['Una carta no garantiza profesión, ingresos, matrimonio ni fecha exacta de un evento.']}]},
  },
  {
    ru:{slug:'compatibility',title:'Совместимость',description:'Как две карты помогают понять общение, близость и сложные места.',intro:'Совместимость — не одна цифра и не приговор отношениям.',sections:[{title:'Что сравнивается',body:['Общение, эмоциональные реакции, притяжение, границы и ожидания.']},{title:'Что важнее процента',body:['Где легко договориться, где люди говорят на разных языках и что помогает после конфликта.']},{title:'Важно',body:['Астрология не оправдывает насилие, контроль или вредное поведение.']}]},
    en:{slug:'compatibility',title:'Compatibility',description:'How two charts can clarify communication, closeness, and friction.',intro:'Compatibility is not one score and not a verdict on a relationship.',sections:[{title:'What is compared',body:['Communication, emotional reactions, attraction, boundaries, and expectations.']},{title:'More useful than a score',body:['Where agreement comes easily, where people speak different languages, and what helps after conflict.']},{title:'Important',body:['Astrology never excuses abuse, control, or harmful behaviour.']}]},
    es:{slug:'compatibility',title:'Compatibilidad',description:'Cómo dos cartas pueden aclarar comunicación, cercanía y puntos de fricción.',intro:'La compatibilidad no es una sola cifra ni una sentencia sobre la relación.',sections:[{title:'Qué se compara',body:['Comunicación, reacciones emocionales, atracción, límites y expectativas.']},{title:'Más útil que un porcentaje',body:['Dónde es fácil acordar, dónde hablan lenguajes distintos y qué ayuda después del conflicto.']},{title:'Importante',body:['La astrología nunca justifica abuso, control ni conductas dañinas.']}]},
  },
  {
    ru:{slug:'zodiac-horoscope',title:'Гороскоп по знаку',description:'Быстрые общие прогнозы для всех 12 знаков зодиака.',intro:'Это удобный вход без персонального расчёта. Контент относится к знаку в целом.',sections:[{title:'Сегодня, неделя и месяц',body:['Актуальные тексты публикуются по стабильным адресам и обновляются редакцией.']},{title:'Чем отличается личный прогноз',body:['Он учитывает данные рождения и связи текущего периода с натальной картой.']}]},
    en:{slug:'zodiac-horoscope',title:'Zodiac horoscope',description:'Quick general forecasts for all 12 zodiac signs.',intro:'This is an easy way to start without a personal calculation. The content applies to the sign in general.',sections:[{title:'Today, week, and month',body:['Current readings use stable URLs and are updated by the editorial team.']},{title:'How a personal forecast differs',body:['It uses birth data and current-period connections to the natal chart.']}]},
    es:{slug:'zodiac-horoscope',title:'Horóscopo por signo',description:'Pronósticos generales para los 12 signos del zodiaco.',intro:'Es una forma sencilla de empezar sin cálculo personal. El contenido se refiere al signo en general.',sections:[{title:'Hoy, semana y mes',body:['Las lecturas actuales usan URLs estables y son actualizadas por el equipo editorial.']},{title:'Diferencia con el pronóstico personal',body:['Utiliza datos de nacimiento y relaciones del período con la carta natal.']}]},
  },
  {
    ru:{slug:'questions',title:'Персональные вопросы',description:'Ответы на утверждённые жизненные вопросы по карте и периоду.',intro:'Вопросы помогают перейти от общего текста к конкретной теме.',sections:[{title:'О чём можно спрашивать',body:['Отношения, работа, деньги, переезд, решения и личные сильные стороны.']},{title:'Как формируется ответ',body:['Учитываются натальная карта, выбранный период и уже рассчитанный прогноз.']},{title:'Без опасных обещаний',body:['Ответ не заменяет врача, юриста, финансового консультанта или экстренную помощь.']}]},
    en:{slug:'questions',title:'Personal questions',description:'Answers to approved real-life questions using the chart and selected period.',intro:'Questions help move from a general reading to a concrete topic.',sections:[{title:'What users can ask',body:['Relationships, work, money, relocation, decisions, and personal strengths.']},{title:'How an answer is created',body:['It uses the natal chart, selected period, and the already calculated forecast.']},{title:'No dangerous promises',body:['It does not replace medical, legal, financial, or emergency support.']}]},
    es:{slug:'questions',title:'Preguntas personales',description:'Respuestas a preguntas vitales aprobadas usando la carta y el período.',intro:'Las preguntas permiten pasar de una lectura general a un tema concreto.',sections:[{title:'Sobre qué preguntar',body:['Relaciones, trabajo, dinero, mudanzas, decisiones y fortalezas personales.']},{title:'Cómo se crea la respuesta',body:['Utiliza la carta natal, el período elegido y el pronóstico ya calculado.']},{title:'Sin promesas peligrosas',body:['No sustituye ayuda médica, legal, financiera ni de emergencia.']}]},
  },
  {
    ru:{slug:'about',title:'О приложении',description:'Как устроен «Твой Гороскоп» и почему он разделяет общий и личный прогноз.',intro:'Наша цель — объяснять понятно, говорить прямо и не превращать астрологию в страшилку.',sections:[{title:'Подход',body:['Расчёт отдельно, человеческое объяснение отдельно.','Технические данные не подменяются общими фразами.']},{title:'Голос',body:['Дерзкий добрый друг: честно, современно, без фатализма.']}]},
    en:{slug:'about',title:'About the app',description:'How Your Horoscope separates general content from personal calculations.',intro:'The goal is to explain clearly, speak directly, and avoid fear-based astrology.',sections:[{title:'Approach',body:['Calculation first, human explanation second.','Technical data is not replaced by generic filler.']},{title:'Voice',body:['A bold, kind friend: honest, modern, and non-fatalistic.']}]},
    es:{slug:'about',title:'Sobre la app',description:'Cómo Tu Horóscopo separa contenido general y cálculos personales.',intro:'El objetivo es explicar con claridad, hablar de frente y evitar la astrología basada en miedo.',sections:[{title:'Enfoque',body:['Primero el cálculo, después la explicación humana.','Los datos técnicos no se sustituyen por relleno genérico.']},{title:'Voz',body:['Un amigo directo y amable: honesto, moderno y sin fatalismo.']}]},
  },
  {
    ru:{slug:'faq',title:'Частые вопросы',description:'Короткие ответы о расчётах, данных рождения и границах прогнозов.',intro:'То, что стоит знать до начала.',sections:[{title:'Нужно ли точное время рождения?',body:['Для асцендента и домов — да. Если время неизвестно, приложение не должно придумывать его.']},{title:'Это предсказание будущего?',body:['Нет. Прогноз описывает вероятности, темы и условия.']},{title:'Можно начать только со знака?',body:['Да. Персональные данные можно добавить позже.']},{title:'Где управлять подпиской?',body:['В магазине, через который оформлена покупка.']}]},
    en:{slug:'faq',title:'Frequently asked questions',description:'Clear answers about calculations, birth data, and forecast limits.',intro:'What is worth knowing before you start.',sections:[{title:'Is exact birth time required?',body:['It is needed for the rising sign and houses. If it is unknown, the app should not invent it.']},{title:'Is this a prediction of the future?',body:['No. A forecast describes probabilities, themes, and conditions.']},{title:'Can I start with only my sign?',body:['Yes. Personal data can be added later.']},{title:'Where do I manage a subscription?',body:['In the store where the purchase was made.']}]},
    es:{slug:'faq',title:'Preguntas frecuentes',description:'Respuestas claras sobre cálculos, datos de nacimiento y límites.',intro:'Lo que conviene saber antes de empezar.',sections:[{title:'¿Hace falta la hora exacta?',body:['Es necesaria para ascendente y casas. Si no se conoce, la app no debe inventarla.']},{title:'¿Es una predicción del futuro?',body:['No. Describe probabilidades, temas y condiciones.']},{title:'¿Puedo empezar solo con mi signo?',body:['Sí. Los datos personales pueden añadirse después.']},{title:'¿Dónde gestiono la suscripción?',body:['En la tienda donde se realizó la compra.']}]},
  },
  {
    ru:{slug:'support',title:'Поддержка',description:'Помощь с аккаунтом, подпиской, данными рождения и работой приложения.',intro:'Опишите проблему и укажите версию приложения. Никогда не отправляйте пароль.',sections:[{title:'Контакт',body:[process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@example.com']},{title:'Что приложить',body:['Модель устройства, версия ОС, версия приложения и шаги до ошибки.']},{title:'Удаление аккаунта',body:['Используйте отдельную публичную страницу удаления аккаунта.']}]},
    en:{slug:'support',title:'Support',description:'Help with accounts, subscriptions, birth data, and app issues.',intro:'Describe the problem and include the app version. Never send a password.',sections:[{title:'Contact',body:[process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@example.com']},{title:'What to include',body:['Device model, OS version, app version, and steps leading to the issue.']},{title:'Account deletion',body:['Use the dedicated public account-deletion page.']}]},
    es:{slug:'support',title:'Ayuda',description:'Ayuda con cuenta, suscripción, datos de nacimiento y errores.',intro:'Describe el problema e indica la versión de la app. Nunca envíes la contraseña.',sections:[{title:'Contacto',body:[process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@example.com']},{title:'Qué incluir',body:['Modelo del dispositivo, versión del sistema, versión de la app y pasos hasta el error.']},{title:'Eliminar cuenta',body:['Utiliza la página pública específica para eliminar la cuenta.']}]},
  },
];

export function getStaticPages(locale: Locale): StaticPage[] { return pages.map((item) => item[locale]); }
export function getStaticPage(locale: Locale, slug: string): StaticPage | undefined { return getStaticPages(locale).find((item) => item.slug === slug); }
