import React from 'react';
import { lumiaSelectionHaptic } from '../../../lib/haptics';

type LzAskPresetsProps = {
  title: string;
  questions: string[];
  onPick: (question: string) => void;
};

export function LzAskPresets({ title, questions, onPick }: LzAskPresetsProps) {
  return (
    <section className="lz-ask-section mt-10 pb-2">
      <p className="lz-kicker">{title}</p>
      <div className="-mx-1 mt-4 flex gap-2.5 overflow-x-auto px-1 pb-1 scrollbar-hide">
        {questions.map((question) => (
          <button
            key={question}
            type="button"
            onClick={() => {
              lumiaSelectionHaptic();
              onPick(question);
            }}
            className="lz-ask-pill shrink-0 max-w-[240px] text-left active:scale-[0.98]"
          >
            {question}
          </button>
        ))}
      </div>
    </section>
  );
}

export function getAskPresetQuestions(language: 'ru' | 'en'): string[] {
  if (language === 'en') {
    return [
      'What should I focus on today?',
      'What is waiting in love?',
      'How do I talk to my partner?',
      'Where is my energy going?',
      'What should I avoid today?',
      'What am I like in relationships?',
      'What is my strongest side?',
      'What holds me back?',
      'Is today good for an important talk?',
      'How can I improve things with people close to me?',
      'What matters at work right now?',
      'Should I take a risk today?',
      'Why do I react the way I do in conflict?',
      'What gives me energy?',
      'How do I make decisions better?',
      'What should I watch this week?',
      'Is it a good time to start something new?',
      'What matters for my money right now?',
      'Where is my potential for growth?',
      'How do I get through this hard stretch?',
      'How can I take better care of myself?',
      'What lesson does today hold for me?',
      'How do I let go of what worries me?',
      'What is the right next step for me?',
      'Why do I keep attracting the same people?',
      'Am I in the right job for me?',
      'How do I stop overthinking this?',
      'What do I really want right now?',
      'How do I set boundaries without guilt?',
      'Is this person good for me?',
      'What am I avoiding that I should face?',
      'How do I rebuild my confidence?',
      'What should I prioritize this month?',
      'How do I handle this conflict calmly?',
      'Should I make the first move?',
      'How do I know if someone is right for me?',
      'Should I give a second chance?',
      'How do I get over a breakup?',
      'Why do I feel jealous?',
      'How do I stop fearing closeness?',
      'Am I ready for a serious relationship?',
      'How do we bring back the spark?',
      'Why do we argue so often?',
      'Should I text my ex?',
      'How do I understand my real feelings?',
      'Should I change jobs?',
      'How do I ask for a raise?',
      'Why am I burning out at work?',
      'How do I find my calling?',
      'Should I invest money in this?',
      'How do I stop worrying about money?',
      'Is it a good time for a big purchase?',
      'How do I beat procrastination?',
      'Should I start my own project?',
      'How do I understand myself better?',
      'Why do I underestimate myself?',
      'How do I build my self-worth?',
      'What keeps me from being happy?',
      'How do I deal with anxiety?',
      'How do I stop comparing myself to others?',
      'Where does my tiredness come from?',
      'How do I balance work and rest?',
      'How do I learn to love myself?',
      'What should I learn next?',
      'Why am I afraid of change?',
      'How do I let go of the past?',
      'How do I improve things with my parents?',
      'How do I handle criticism?',
      'Why is it hard for me to ask for help?',
      "How do I care less about others' opinions?",
      "What's ahead for me this month?",
      'What phase of life am I in?',
      'Should I wait or act?',
      'What should I watch for this year?',
      'Should I move?',
      'What matters most for me right now?',
      "How do I know I'm on the right path?",
      'What should I change in my life?',
      'How do I find motivation?',
      'What will help me calm down?',
      'How do I fix my routine?',
      'How do I get more confident in my decisions?',
      'What am I really afraid of?',
      'How do I worry less about the future?',
    ];
  }
  return [
    'На чём сфокусироваться сегодня?',
    'Что ждёт меня в любви?',
    'Как поговорить с партнёром?',
    'Куда уходит моя энергия?',
    'Чего лучше избегать сегодня?',
    'Какой я в отношениях?',
    'В чём моя сильная сторона?',
    'Что мешает мне двигаться вперёд?',
    'Подходящий ли день для важного разговора?',
    'Как наладить отношения с близкими?',
    'Что важно в работе прямо сейчас?',
    'Стоит ли рисковать сегодня?',
    'Почему я так реагирую в конфликтах?',
    'Что меня заряжает?',
    'Как лучше принимать решения?',
    'На что обратить внимание на этой неделе?',
    'Подходящее ли время начать новое?',
    'Что важно в моих финансах сейчас?',
    'Где сейчас мой потенциал роста?',
    'Как пережить этот непростой период?',
    'Как лучше заботиться о себе?',
    'Какой урок несёт мне этот день?',
    'Как отпустить то, что тревожит?',
    'Какой мой следующий шаг?',
    'Почему я притягиваю одних и тех же людей?',
    'Та ли это работа для меня?',
    'Как перестать всё время думать об этом?',
    'Чего я на самом деле хочу сейчас?',
    'Как ставить границы без чувства вины?',
    'Подходит ли мне этот человек?',
    'Чего я избегаю, но стоит посмотреть в лицо?',
    'Как вернуть уверенность в себе?',
    'На чём сосредоточиться в этом месяце?',
    'Как спокойно пройти через этот конфликт?',
    'Стоит ли мне сделать первый шаг?',
    'Как понять, что человек мне подходит?',
    'Стоит ли дать второй шанс?',
    'Как пережить расставание?',
    'Почему я ревную?',
    'Как перестать бояться близости?',
    'Готов ли я к серьёзным отношениям?',
    'Как вернуть искру в отношениях?',
    'Почему мы часто ссоримся?',
    'Стоит ли писать бывшему человеку?',
    'Как понять свои настоящие чувства?',
    'Стоит ли менять работу?',
    'Как попросить о повышении?',
    'Почему я выгораю на работе?',
    'Как найти своё призвание?',
    'Стоит ли вкладывать в это деньги?',
    'Как перестать тревожиться из-за денег?',
    'Подходящий ли момент для крупной покупки?',
    'Как побороть прокрастинацию?',
    'Стоит ли начинать своё дело?',
    'Как лучше понять себя?',
    'Почему я себя недооцениваю?',
    'Как поднять самооценку?',
    'Что мешает мне быть счастливее?',
    'Как справиться с тревогой?',
    'Как перестать сравнивать себя с другими?',
    'Откуда моя усталость?',
    'Как найти баланс между работой и отдыхом?',
    'Как научиться любить себя?',
    'Чему мне стоит научиться дальше?',
    'Почему я боюсь перемен?',
    'Как отпустить прошлое?',
    'Как наладить отношения с родителями?',
    'Как реагировать на критику?',
    'Почему мне сложно просить о помощи?',
    'Как меньше зависеть от мнения других?',
    'Что ждёт меня в ближайший месяц?',
    'Какой сейчас период в моей жизни?',
    'Ждать или действовать?',
    'На что обратить внимание в этом году?',
    'Стоит ли мне переехать?',
    'Что для меня сейчас главное?',
    'Как понять, туда ли я иду?',
    'Что мне стоит изменить в жизни?',
    'Как найти мотивацию?',
    'Что поможет мне успокоиться?',
    'Как наладить режим?',
    'Как стать увереннее в решениях?',
    'Чего я боюсь на самом деле?',
    'Как меньше тревожиться о будущем?',
  ];
}
