const getPrimary=jest.fn(),getByUser=jest.fn(),upsertByUser=jest.fn(),request=jest.fn();
jest.mock('../lib/natalChartV2Repository',()=>({natalChartV2Repository:{getPrimary}}));
jest.mock('../lib/db',()=>({db:{content_interpretations:{getByUser,upsertByUser}},getPool:()=>({query:jest.fn()})}));
jest.mock('../lib/openaiResponses',()=>({createLunaStructuredResponse:(...args:unknown[])=>request(...args)}));
jest.mock('../lib/personalForecastDateContext',()=>({buildPersonalForecastDateContext:()=>({source:'Swiss Ephemeris',samples:[]})}));
jest.mock('../lib/appSettings',()=>({getUnifiedContentModel:async()=> 'gpt-5.6-luna'}));
jest.mock('../lib/forecastDeliveryMetrics',()=>({logForecastDeliveryMetric:jest.fn()}));
jest.mock('../lib/contentGenerationLock',()=>({buildContentGenerationLockKey:()=> 'test',withContentGenerationLock:async({readCached,generate}:any)=>{const cached=await readCached();return {status:'ready',value:cached?cached.value:await generate(),fromCache:!!cached};}}));
import samples from '../components/ui-preview/readingSamples.json';
import {ensurePersonalForecast} from '../lib/personalForecastCache';
import {buildCanonicalNatalInputHash} from '../lib/natalChartCanonical';
import {isPersonalForecastPackage} from '../lib/personalForecastContract';
import type {UserProfile} from '../types';
const person=samples.people[0], profile=person.profile as UserProfile;
const context={userId:profile.id!,profile,accessTier:'premium' as const,period:'day' as const,periodKey:'2026-09-08'};
const inputHash=buildCanonicalNatalInputHash({...profile,latitude:person.chart.birth.latitude,longitude:person.chart.birth.longitude,timezone:person.chart.birth.timezone});
let stored:any;
beforeEach(()=>{jest.clearAllMocks();stored=null;getByUser.mockImplementation(async()=>stored);upsertByUser.mockImplementation(async(_:string,value:any)=>{stored=structuredClone(value);});getPrimary.mockResolvedValue({user_id:profile.id,input_hash:inputHash,chart_data:person.chart});request.mockResolvedValue({content:JSON.stringify({title:'A new offer',forecast:'An offer may arrive today. The conversation could reveal a useful detail.'})});});
it('reads the owner saved chart, writes one complete result and reuses durable cache',async()=>{
 const first=await ensurePersonalForecast(context);expect(first.status).toBe('ready');if(first.status!=='ready')throw Error('Not ready');expect(isPersonalForecastPackage(first.value)).toBe(true);expect(first.value.sections).toEqual([]);expect(request).toHaveBeenCalledTimes(1);expect(upsertByUser).toHaveBeenCalledTimes(1);
 const again=await ensurePersonalForecast(context);expect(again.status).toBe('ready');expect(request).toHaveBeenCalledTimes(1);expect(upsertByUser).toHaveBeenCalledTimes(1);
});
it.each([null,{user_id:'other',input_hash:inputHash,chart_data:person.chart}])('refuses missing or foreign saved charts before provider access',async chart=>{getPrimary.mockResolvedValue(chart);await expect(ensurePersonalForecast(context)).rejects.toThrow('PERSONAL_FORECAST_EVIDENCE_EMPTY');expect(request).not.toHaveBeenCalled();});
it('does not silently recalculate an outdated chart',async()=>{getPrimary.mockResolvedValue({user_id:profile.id,input_hash:'outdated',chart_data:person.chart});await expect(ensurePersonalForecast(context)).rejects.toThrow('PERSONAL_FORECAST_CHART_OUTDATED');expect(request).not.toHaveBeenCalled();});
it('does not persist a fabricated fallback after provider failure',async()=>{request.mockRejectedValue(new Error('quota unavailable'));await expect(ensurePersonalForecast(context)).rejects.toThrow('PERSONAL_FORECAST_WRITER_REQUEST_FAILED');expect(upsertByUser).not.toHaveBeenCalled();});
it('reports a failed durable write as failure',async()=>{upsertByUser.mockRejectedValueOnce(new Error('db unavailable'));await expect(ensurePersonalForecast(context)).rejects.toThrow('PERSONAL_FORECAST_CACHE_WRITE_FAILED');});
